### ISSUE TITLE
Slipping on Fluids can be completely avoided using tables

### ISSUE THREAD

**Issue by DakotaGay** [space-wizards/space-station-14#28320] opened 2024-05-27 16:23 UTC
## Description
If you vault onto a table and walk off into a fluid, you will not be able to slip on any fluids until you walk to a dry tile

**Reproduction**

1. Find or create a floor with lots of fluid (I recommend space lube)
2. Build a table next to it or on it
3. Vault onto the table
4. Walk off the table onto a floor with fluid
5. You can walk on Space Lube without slipping

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/72140289/7f02493b-b827-4f22-92f6-446da5c07585

**Additional context**

**Comment by DakotaGay** [comment] 2024-05-27 16:39
Video Upload, because the previous one did not seem to work

[2024-05-27 18-01-57.webm](https://github.com/space-wizards/space-station-14/assets/72140289/6a96d15d-152d-469b-ad70-7872561ec43a)

**Comment by lzk228** [comment] 2024-05-27 16:45
climbable structures have too big range of their "climbness"

**Comment by DakotaGay** [comment] 2024-05-27 16:57
I just tested. The range is quite large. It's at least the whole Food Area on Oasis.

The game considers you on a table the whole time, which is probably the reason you can't slip.
You can simply walk back onto a table without having to vault

I also tested soap and others, and you can't slip on them either

**Comment by Pok27** [comment] 2024-05-27 16:58
dupe of #27895

**Closed** 2024-06-22 14:35 UTC
Labels: Status: Untriaged
