### ISSUE TITLE
Opening bag storage and then belt storage (or vice versa) breaks the first container

### ISSUE THREAD

**Issue by maylokana** [space-wizards/space-station-14#27511] opened 2024-04-30 02:05 UTC
## Description

Title. By opening both storage containers simultaneously without closing the first one, you lose the ability to look into it and take items out of it freely. This also applies to any form of storage, provided the second container is one that's either in your bag slot or belt slot

You can still use hotkeys to take out favorite items and put new items in, or click on the container to put them in that way, but you cannot look in the storage itself without closing it through the right click menu and then re-opening it

**Reproduction**

1. Open any container
2. Do not close the first container
3. Open your bag or belt
4. Close the second container

**Screenshots**

N/A

**Additional context**

A recent commit definitely broke this as before your bag/belt would automatically close when looking into a new container, this is still true for other storage or anything not on your person (excluding hands)

**Comment by Zealith-Gamer** [comment] 2024-05-01 13:35
I was unable to reproduce this. Please let me know if I followed your steps correctly.
https://youtu.be/p1jATB4_ofQ

**Comment by EmoGarbage404** [comment] 2024-05-12 22:39
closing in favor of #27692 due to more detailed replication steps.

**Closed by EmoGarbage404** 2024-05-12 22:39 UTC
Labels: Issue: Bug, Bug: Needs Replicating
