### ISSUE TITLE
Replay ghost does not always spawn on the station

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#29725] opened 2024-07-04 23:00 UTC
## Description

Possibly #17170 issue 2

Players should not spawn in the middle of no where on replays. And idk of any ways to tp to the actual station or someone so this makes replays really annoying to players to view.

This has been happening for a bit but only now did i get told of a reproducable replay

**Reproduction**

Reproducable replays
https://moon.spacestation14.com/replays/salamander/2024/07/04/salamander-2024_07_04-17_41-round_58587.zip
https://moon.spacestation14.com/replays/lizard/2024/07/07/lizard-2024_07_07-07_21-round_58823.zip
https://moon.spacestation14.com/replays/lizard/2024/07/07/lizard-2024_07_07-06_38-round_58818.zip

**Comment by IProduceWidgets** [comment] 2024-07-05 01:37
Is it Core by chance? I think Core still has the issue where the singularity eats the observer spawn.

**Comment by VasilisThePikachu** [comment] 2024-07-07 08:32
> Is it Core by chance? I think Core still has the issue where the singularity eats the observer spawn / the tile its on.

Don't think it's map dependant, I have also been told it was also happening on oesis from another player

**Comment by VasilisThePikachu** [comment] 2024-07-11 10:59
Increasing priority, activity hurting player expirience of the replay system.

**Comment by Djungelskog2** [comment] 2024-07-11 11:19
oh thank you so much I was having trouble with this the other day

**Comment by metalgearsloth** [comment] 2024-07-11 14:00
> Increasing priority, activity hurting player expirience of the replay system.

The issue is vgroid was marked as a station grid and replays seem to pick a random one for people to use.

At any rate the vgroid is no longer a station grid.

**Comment by Errant-4** [comment] 2024-07-21 17:34
> > Increasing priority, activity hurting player expirience of the replay system.
> 
> The issue is vgroid was marked as a station grid and replays seem to pick a random one for people to use.
> 
> At any rate the vgroid is no longer a station grid.

The issue is still happening, here is an example from 2 days ago https://moon.spacestation14.com/replays/lizard/2024/07/19/lizard-2024_07_19-07_19-round_60042.zip

**Comment by LankLTE** [comment] 2024-07-21 21:20
And here's an example from about an hour ago https://moon.spacestation14.com/replays/rain_one_one_gateway/2024/07/21/rain_one_one_gateway-2024_07_21-19_01-round_60257.zip

**Comment by Errant-4** [comment] 2024-07-22 14:35
We could put an IsStation datafield on mapgridcomponent but it would only really be reliable early in the round. That would be sufficient for replay purposes though. 
(I imagine with gridsplits down the round it would become dificult or infeasible to keep track of what grid is really a station and whats not)

**Closed** 2024-07-22 19:32 UTC
Labels: Issue: Bug, Priority: 1-Urgent, Difficulty: 3-Hard, Bug: Replicated
