### ISSUE TITLE
Standardize prototype/resource naming.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#242] opened 2019-05-27 22:53 UTC
Seriously it's a mess. A mix of all case types.

**Comment by Zumorica** [comment] 2019-05-27 22:54
I propose using either PascalCase or camelCase as a convention.

**Comment by Injazz** [comment] 2019-05-30 15:15
camelCase for both IDs and parameter names, PascalCase for component names, im gonna clean it up a bit

**Comment by AJCM-git** [comment] 2020-04-29 21:56
Duplicate of #831

**Comment by Zumorica** [comment] 2020-04-29 21:57
(Closed in favour of #834)

**Closed** 2020-04-29 21:56 UTC
Labels: Junior Job, Priority: 4-wishlist, Type: Cleanup, W: Next
