### ISSUE TITLE
DragDrop shaders are broken

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#12975] opened 2022-12-11 08:45 UTC
I thought it was my PR but turns out these are broken on master, NFI how long for.

Steps to repro:
Start dragging something and never get the out of range shader to show properly.

**Comment by ElectroJr** [comment] 2023-01-01 19:31
Functionally a duplicate of #12045, which should also be moved to engine.

**Closed by ElectroJr** 2023-01-01 19:31 UTC
