### ISSUE TITLE
Standardize code layout

### ISSUE THREAD

**Issue by Ygg01** [space-wizards/space-station-14#4615] opened 2021-09-14 10:31 UTC
## Description
It seems at the moment, we depend on Rider's/Visual Studio's graces to auto-format code. 
We could update `.editorconfig` and standardize this behavior. I've offered to do it before, but @metalgearsloth said it's left for maintainers. 

## What this solves?
- Less arguing during the review if something is formatted correctly or not.
- Consistency across codebase
- Updates of Rider would toss around code less. Since these annotations are somewhat experimental some could be deprecated.
```csharp
[Dependency] private readonly _aa
```
vs
```csharp
[View]
private readonly _aa
```

Here is list of properties for Rider: https://www.jetbrains.com/help/rider/EditorConfig_Index.html

**Comment by SweptWasTaken** [comment] 2021-09-27 20:59
There's a sort of duplicate of this on the RobustToolbox repository since I still have VS and Rider installed i'll look into this some more. 

https://github.com/space-wizards/RobustToolbox/issues/886

**Comment by mirrorcult** [comment] 2023-05-24 18:21
layout is alraedy pretty standardized i dont think we need an issue for 'fix all cases of nonstandard layout'

**Closed as completed by mirrorcult** 2023-05-24 18:21 UTC
Labels: P3: Standard, T: Cleanup, D2: Medium
