### ISSUE TITLE
The Living can see the fingers of the dead

### ISSUE THREAD

**Issue by Streaky-Haddock** [space-wizards/space-station-14#5454] opened 2021-11-22 17:46 UTC
## Description
When ghosts point, the living can see it.

**Screenshots**
![image](https://user-images.githubusercontent.com/93771043/142910029-94fc0d6b-a516-4270-bb07-b4e99d5437e1.png)

**Additional context**

**Comment by Zumorica** [comment] 2021-11-22 17:46
this bug is gonna haunt us for the rest of time

**Comment by moonheart08** [comment] 2021-11-22 17:47
this is like the fourth time oh my god

**Comment by xRiriq** [comment] 2021-11-22 17:50
There's _one person_ who has been abusing the hell out of it lately. Can we put a rate limiter on it too (in case it is a hard fix)? As I usually play medical roles it's ridiculous. Thankfully one of those rounds was an antag round so I could just throw them in a locker instead of cloning.

**Comment by Acruid** [comment] 2021-11-23 00:18
Has anyone had success reproducing this locally?

**Comment by xRiriq** [comment] 2021-11-23 06:37
Yes:
1. start local debug server
2. start 2 local debug clients
3. punch one client to crit

![image](https://user-images.githubusercontent.com/94037592/142980269-e9eeb722-1ddd-4fb9-bab3-c94eb2cabda1.png)

4. punch that same client to dead

![image](https://user-images.githubusercontent.com/94037592/142980375-95d22160-4bf3-449d-9869-78a900f11ecc.png)


Seems pretty straightforward to induce the state in question.

**Comment by Acruid** [comment] 2021-11-24 03:25
Ok, so it's dead players still being able to point, before turning into ghosts. OP said it was ghosts pointing, which is not the problem.

**Comment by Streaky-Haddock** [comment] 2021-11-24 07:59
My mistake!

**Comment by ElectroJr** [comment] 2021-12-13 08:53
> My mistake!

So if I understand correctly this has nothing to do with ghosts and is just about incapacitated players. In that case this is a duplicate of #2774 so closing this.

and as for @xRiriq's comment:
> Can we put a rate limiter on it too (in case it is a hard fix)

pointing already has a 0.5s delay limiting the rate, which is fine IMO. Or was this being bypassed somehow?

**Closed by ElectroJr** 2021-12-13 08:53 UTC
Labels: Type: Bug, Bug: Replicated
