### ISSUE TITLE
WarOp

### ISSUE THREAD

**Issue by Aisu9** [space-wizards/space-station-14#25105] opened 2024-02-10 16:57 UTC
## Description
When Nukies go for a WarOp, there is a surge of players Ghosting/Suiciding/Dying/Cryo

**Additional context**
When a WarOp happen(or just from the beginning of Nukie rounds), remove the ability from people that manually ghost/suicide/die/cryo to take a ghost role until10 minutes after the end of the additional preparation time granted by WarOp
(Basically allowing only the **observers** to take ghost roles)

**Comment by VasilisThePikachu** [comment] 2024-02-14 00:30
Duplicate off one of the requests in #20064

**Closed by VasilisThePikachu** 2024-02-14 00:30 UTC
