### ISSUE TITLE
When deconstructing certain tiles, only the first step is shown in the guided construction helper

### ISSUE THREAD

**Issue by weaversam8** [space-wizards/space-station-14#6041] opened 2022-01-06 04:04 UTC
## Description
When constructing and deconstructing tiles, examining the tile (or its construction ghost) provides a tooltip instructing the user of the next step to take. The information for these steps is provided by the item's construction graph, which can specify a number of steps to transition between different states of the object's construction.

Some construction graphs, like [the one for airlocks](https://github.com/weaversam8/space-station-14/blob/master/Resources/Prototypes/Recipes/Construction/Graphs/structures/airlock.yml) provide each step of an object's construction or deconstruction as a "node" in the construction graph, where each edge between said nodes requires a single step to construct or deconstruct.

Some graphs though, like [the deconstruction graph for reinforced windows](https://github.com/weaversam8/space-station-14/blob/master/Resources/Prototypes/Recipes/Construction/Graphs/structures/window.yml#L46-L63) or [the deconstruction graph for reinforced walls](https://github.com/weaversam8/space-station-14/blob/master/Resources/Prototypes/Recipes/Construction/Graphs/structures/girder.yml#L97-L143) contain **multiple "steps"** for an edge to deconstruct an object.

When this happens, only the first step is shown in the "examine" window for an object. For example: to deconstruct a reinforced window, you must:

1. Use a screwdriver
2. Use a crowbar
3. Use a screwdriver
4. Use a wrench

But only the first step is shown while deconstructing. After the first step, the examine window is incomplete. Take a look at the screenshots below:

**Screenshots**

Before step 1:
![image](https://user-images.githubusercontent.com/2546219/148326431-3d777490-c6c8-4924-8594-e3099fcbc8f7.png)

After step 1, before step 2:
![image](https://user-images.githubusercontent.com/2546219/148326471-6f97ee13-fb40-406c-a646-c09042097603.png)

**Additional context**

I'm working on a PR.

**Comment by Zumorica** [comment] 2022-01-06 14:54
Dupe of #5486, but since this issue is more in-depth I'll keep it open

**Closed** 2022-01-13 14:33 UTC
