### ISSUE TITLE
Double-clicking any item in the "spawn tiles" menu in mapping mode throws an exception

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3938] opened 2021-05-06 22:51 UTC
How to reproduce:

- Start SS14 in your dev environment. 
- Go into mapping mode on a new map.
- Click the "spawn tiles" option in the spawn menu.
- Double-click any item in the tiles menu.
- The game will throw a seemingly fatal exception.

![image](https://user-images.githubusercontent.com/7907891/117374881-fc3dbb00-ae9b-11eb-859c-7eb8d81be8fa.png)

**Comment by 20kdc** [comment] 2021-05-12 21:52
This *might* be solved by https://github.com/space-wizards/RobustToolbox/pull/1755 but I'm unsure. There are definitely very related bugs that I solved with that, but I don't know if this specific one was.

**Comment by TimrodDX** [comment] 2021-05-12 22:23
Nope, I just updated my dev environment (and all submodules) and it looks like the crash still happens.

**Comment by PaulRitter** [comment] 2021-05-21 12:22
a stacktrace would be interesting since i cant test it rn

**Comment by 20kdc** [comment] 2021-05-21 22:14
Notably, while it was merged at that point, did you ensure that you used RobustToolbox master (and/or the one with), or the version selected in the current repository state of space-station-14? (keeping in mind the build script will automatically change it back for some reason)?

**Comment by TimrodDX** [comment] 2021-05-22 01:13
I think I used the one in the current repository state, but I'm not sure. Turning it from "debug" to "release" makes it so the error isn't  fatal, so it's not much of a problem as it turns out.

**Comment by PaulRitter** [comment] 2021-05-26 09:31
> 
> 
> I think I used the one in the current repository state, but I'm not sure. Turning it from "debug" to "release" makes it so the error isn't fatal, so it's not much of a problem as it turns out.

this should be noted in the mapping doc too that you should **always map in release** since it catches errors. debug will not do that

**Comment by 20kdc** [comment] 2021-05-26 11:30
The mapping command also has a warning already for this. However to be fair these exceptions imply underlying problems, so it should still be looked into.

**Comment by AJCM-git** [comment] 2021-11-06 22:44
Cant reproduce anymore

**Closed by AJCM-git** 2021-11-06 22:44 UTC
Labels: Type: Bug, Priority: 3-Not Required, Changes: UI, Difficulty: 2-Medium
