### ISSUE TITLE
gun bolt debug assert

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#19782] opened 2023-09-03 07:18 UTC
## Description
it trying to do something on a bullet that was already fired or something

**Reproduction**
0. dev
1. take akms
2. close bolt
3. magdump, chamber included
4. press e on it
5. client debug assert

**Stacktrace**
```
Unhandled exception. System.ArgumentException: Entity 11885 is not valid. (Parameter 'uid')
   at Robust.Shared.GameObjects.EntityManager.AddComponent[T](EntityUid uid, T component, Boolean overwrite) in RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 261
   at Robust.Shared.GameObjects.EntityManager.AddComponent[T](EntityUid uid) in RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 200
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.EnsureShootable(EntityUid uid) in Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs:line 419
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.OnBallisticTakeAmmo(EntityUid uid, BallisticAmmoProviderComponent component, TakeAmmoEvent args) in Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.Ballistic.cs:line 242
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass47_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 255
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass58_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 393
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args, Boolean dispatchByReference) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 554
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast, Boolean byRef) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 222
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 182
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in RobustToolbox/Robust.Shared/GameObjects/EntitySystem.cs:line 150
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.CycleCartridge(EntityUid uid, ChamberMagazineAmmoProviderComponent component, Nullable`1 user, AppearanceComponent appearance) in Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.ChamberMagazine.cs:line 219
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.SetBoltClosed(EntityUid uid, ChamberMagazineAmmoProviderComponent component, Boolean value, Nullable`1 user, AppearanceComponent appearance, ItemSlotsComponent slots) in Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.ChamberMagazine.cs:line 155
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.ToggleBolt(EntityUid uid, ChamberMagazineAmmoProviderComponent component, Nullable`1 user) in Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.ChamberMagazine.cs:line 254
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.OnChamberActivate(EntityUid uid, ChamberMagazineAmmoProviderComponent component, ActivateInWorldEvent args) in Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.ChamberMagazine.cs:line 58
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass47_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 255
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass58_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 393
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass67_1.<EntCollectOrdered>b__0(Unit& ev) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 572
   at Robust.Shared.GameObjects.EntityEventBus.DispatchOrderedEvents(Unit& eventArgs, ValueList`1& found) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Ordering.cs:line 54
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalOrdered(EntityUid uid, Type eventType, EventData subs, Unit& unitRef, Boolean broadcast, Boolean byRef) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Ordering.cs:line 45
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast, Boolean byRef) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 218
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 182
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in RobustToolbox/Robust.Shared/GameObjects/EntitySystem.cs:line 150
   at Content.Shared.Interaction.SharedInteractionSystem.InteractionActivate(EntityUid user, EntityUid used, Boolean checkCanInteract, Boolean checkUseDelay, Boolean checkAccess) in Content.Shared/Interaction/SharedInteractionSystem.cs:line 934
   at Content.Shared.Hands.EntitySystems.SharedHandsSystem.TryActivateItemInHand(EntityUid uid, HandsComponent handsComp, String handName) in Content.Shared/Hands/EntitySystems/SharedHandsSystem.Interactions.cs:line 114
   at Content.Shared.Hands.EntitySystems.SharedHandsSystem.HandleActivateItemInHand(RequestActivateInHandEvent msg, EntitySessionEventArgs args) in Content.Shared/Hands/EntitySystems/SharedHandsSystem.Interactions.cs:line 60
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in RobustToolbox/Robust.Shared/GameObjects/EventBusExt.cs:line 46
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass4_0`1.<SubscribeEvent>b__0(Unit& ev) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 169
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs, Boolean byRef) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 332
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType, Boolean byRef) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 317
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 263
   at Robust.Client.GameStates.ClientGameStateManager.PredictTicks(GameTick predictionTarget) in RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 442
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 386
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in RobustToolbox/Robust.Client/GameController/GameController.cs:line 604
   at Robust.Client.GameController.<StartupContinue>b__57_0(Object sender, FrameEventArgs args) in RobustToolbox/Robust.Client/GameController/GameController.cs:line 220
   at Robust.Shared.Timing.GameLoop.Run() in RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 240
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 134
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 119
   at Robust.Client.GameController.<>c__DisplayClass100_0.<Run>b__0() in RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 86
```

**Comment by Slava0135** [comment] 2023-11-12 19:43
duplicate of #19165

**Closed by Slava0135** 2023-11-12 19:43 UTC
