### ISSUE TITLE
/me messages from containers are shown to people on the outside

### ISSUE THREAD

**Issue by exp111** [space-wizards/space-station-14#5211] opened 2021-11-07 22:23 UTC
## Steps
* Go into container
* Do a /me
* People outside can see the /me

**Screenshots**
See timestamp: https://youtu.be/65JQ0A-l-WI?t=99

**Additional context**
May also occur if person is occluded by walls and such but I didn't check

**Comment by AJCM-git** [comment] 2022-06-30 18:28
dupe of #2825

**Closed by AJCM-git** 2022-06-30 18:28 UTC
