### ISSUE TITLE
Alert crash when using godmode

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#4555] opened 2021-09-02 01:42 UTC
If you take damage, enable godmode, then rejuvenate, often the game crashes because of an alert severity not being found.

**Comment by mirrorcult** [comment] 2021-09-02 01:56
pretty sure this is just cause of the master tests failing

**Comment by metalgearsloth** [comment] 2021-09-02 02:00
This is something different to your issue I think. It's been crashing my game locally for a while, I just keep forgetting about it.

**Comment by ElectroJr** [comment] 2021-09-02 06:59
I can't seem to reproduce that crash by following those steps using either the rejuvenate verb or command. Is there anything more specific you are doing?

On a somewhat related note though, I think godmode isn't actually working properly after the damageable refactor,  you can still take damage. So that's another bug that I let through :/

This is already fixed in #4529, so probably not work creating a separate issue or PR for.

**Comment by AJCM-git** [comment] 2021-11-07 06:22
I cant reproduce either. Closing

**Closed by AJCM-git** 2021-11-07 06:22 UTC
Labels: Type: Bug, Priority: 2-Before Release, Size: 1-Tiny, Difficulty: 2-Medium
