### ISSUE TITLE
Job icons are sort of bugged at the moment

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#25997] opened 2024-03-11 13:36 UTC
## Description

As a borg, you can see everyone's icons. But job icons are just... appearing and disappearing now based on where you walk on the map?

**Reproduction**

**Screenshots**

Round #48509 for Lizard
https://github.com/space-wizards/space-station-14/assets/58439124/1eb5bcc2-a391-46b6-b2c6-717e03a6ea75

**Additional context**

**Comment by Tayrtahn** [comment] 2024-03-11 14:44
This might get fixed by #26001

**Comment by Plykiya** [comment] 2024-03-12 09:58
It did not get fixed

**Comment by AzureWildfire** [comment] 2024-03-12 18:04
As a note this job icons in general (both borg and sec-hud) and this is caused by someone having any status on the criminal records (except for none).
If that person is in your vision range even trough walls, it breaks almost all other icons.

**Comment by AzureWildfire** [comment] 2024-03-12 20:58
Just tested it in a previous round and at least as a sec it seems fixed.

**Closed** 2024-07-03 22:55 UTC
