### ISSUE TITLE
Swap hands secondary keybind needs to be manually set every time i launch the game if set to Middle Mouse Button

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#27141] opened 2024-04-19 20:26 UTC
## Description
I like to set my secondary keybind on swap hands to "Middle Mosuse Button". Everytime I reopen the game, my secondary button for the keybind will not work. When i open my keybinds, i can see that it is indeed still set, however it will not take effect untill i manually clear the line, and reset the bind back to "Middle Mouse Button".

**Reproduction**
Set secondary button to middle mouse
Relaunch game
Middle mouse button will not swap hands

**Screenshots**
Opening up my keybinds shows that the game remembers that i set it to mmb, however i have to still reset the field to get it to work:
![image](https://github.com/space-wizards/space-station-14/assets/106507028/c8ec5a7f-ba71-4469-a28e-1f28fdc8317f)

**Additional context**
Potentially related to https://github.com/space-wizards/space-station-14/issues/26728#issue-2226149246

**Comment by thebadman4662** [comment] 2024-04-19 21:16
https://github.com/space-wizards/space-station-14/issues/26142#issuecomment-2041047092

Same here except I use it for pointing.

**Comment by nikthechampiongr** [comment] 2024-04-19 23:27
This is because you have conflicting keys. Middle click by default rotates construction ghosts  I believe.

**Comment by thebadman4662** [comment] 2024-04-20 00:50
> This is because you have conflicting keys. Middle click by default rotates construction ghosts I believe.

It started acting up after MMB was added to locking in grid items or around that time so I would assume its the cause.

**Comment by deltanedas** [comment] 2024-04-20 02:30
rebinding specifically fixes it which is weird, in my case i can then examine anything with mmb and rotate ghosts when not hovering something that can be examined

**Comment by VasilisThePikachu** [comment] 2024-04-20 12:49
Dupe of #26728

**Closed by VasilisThePikachu** 2024-04-20 12:49 UTC
Labels: Status: Untriaged
