### ISSUE TITLE
music fucks performance

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#22266] opened 2023-12-09 07:48 UTC
I dont know how, I dont know why, but its gotten so bad that people have started banning music IC and declared instruments contraband

**Comment by Jarmer123** [comment] 2023-12-09 07:51
#22265 says basically the same thing.

**Comment by GoodWheatley** [comment] 2023-12-09 15:48
Dupe of https://github.com/space-wizards/RobustToolbox/issues/4642

**Closed by GoodWheatley** 2023-12-09 15:48 UTC
