### ISSUE TITLE
Problem for settings

### ISSUE THREAD

**Issue by Stefan10201** [space-wizards/space-station-14#12735] opened 2022-11-23 15:40 UTC
I ran into a problem that I physically can't play on my monitor, I set the "UI scale" to 200% and I can't play
![Снимок экрана 2022-11-23 в 18 36 15](https://user-images.githubusercontent.com/118917029/203587672-4b879423-f2d7-45da-b0db-b2c733951d45.png)

**Comment by dmnct** [comment] 2022-12-20 18:37
Duplicate of #4065

**Comment by ElectroJr** [comment] 2022-12-20 19:14
To reset your UI scale yo can either use the console commands /cvar display.uiScale 1.0 and then /saveconfig, or you can open %AppData%/Space Station 14/data/client_config.toml in a text editor and change uiScale to 1.0

**Closed by ElectroJr** 2022-12-20 19:14 UTC
