### ISSUE TITLE
If you put a muzzle on a person, he can still scream

### ISSUE THREAD

**Issue by Ser11y** [space-wizards/space-station-14#16249] opened 2023-05-08 13:26 UTC
## Description

If you put a muzzle on a person, he can still scream.

**Reproduction**

>Put a muzzle on the person
>The person screams.
>Be Caught by Security

**Screenshots**

![image](https://user-images.githubusercontent.com/99765361/236836253-e606b758-30a0-453f-8e68-a4bc2631736a.png)

**Additional context**

**Comment by deltanedas** [comment] 2023-05-08 13:27
dupe of #14710 i think

**Comment by JoeTheJanitor** [comment] 2023-05-08 14:19
> dupe of #14710 i think

I think that issue is specifically about screaming with the mute component, which muzzles don’t apply. They just give you the ‘mumble’ accent.

**Comment by deltanedas** [comment] 2023-05-08 14:54
oh true

**Comment by VasilisThePikachu** [comment] 2024-02-05 23:54
Fixed at one point

**Closed by VasilisThePikachu** 2024-02-05 23:54 UTC
