### ISSUE TITLE
Sandbox Panel can be opened in main menu

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#616] opened 2020-02-07 17:18 UTC
The sandbox panel can be opened in main menu by pressing the 'B' hotkey.

**Comment by AJCM-git** [comment] 2020-04-29 23:11
Duplicate of #399

**Comment by SweptWasTaken** [comment] 2020-11-20 23:05
Merged into #2598

**Closed by SweptWasTaken** 2020-11-20 23:05 UTC
Labels: Priority: 3-low, Type: Bug
