### ISSUE TITLE
Render ContextMenu and Examine popup on top of SS14Window

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#504] opened 2020-01-13 00:42 UTC
The ContextMenu and Examine popup should be rendered on top of UI windows.

When the right clicking (OpenContextMenu) on an item in the Inventory window, the ContextMenu renders behind the Inventory window, which makes it difficult or impossible to click the ContextMenu buttons.

The Examine popup also has the same problem, rendering behind the Inventory window.

**Comment by SpaghettiTec** [comment] 2020-10-02 20:08
I can't reproduce this behavior.
Is this still a thing?

**Comment by SweptWasTaken** [comment] 2021-01-31 19:03
> 
> 
> I can't reproduce this behavior.
> Is this still a thing?

Nope, closing.

**Closed by SweptWasTaken** 2021-01-31 19:03 UTC
