### ISSUE TITLE
Backpack fills for jobs are different depending on preference(backpack/satchel/duffelbag)

### ISSUE THREAD

**Issue by Fishfish458** [space-wizards/space-station-14#7393] opened 2022-04-02 17:02 UTC
## Description

Roles don't have matching fills for satchels and sometimes duffel bags compared to backpacks.

Example:
 clown with backpack will spawn ClothingBackpackClownFilled which is giggles von honkerton which has a box of hugs in it.
 if instead they choose a satchel, they will get a generic ClothingBackpackSatchelFilled which contains the survival kit.

Pack fills for jobs should be the same no matter what container is chosen.

**Comment by AugustEymann** [comment] 2022-05-06 16:47
https://github.com/space-wizards/space-station-14/pull/7976

**Comment by Mervill** [comment] 2022-10-01 22:30
Cannot reproduce as of d43ed3210c254caeacf2ca1e7e2056e15c9fb73e

**Comment by ElectroJr** [comment] 2022-10-09 05:04
>Cannot reproduce as of https://github.com/space-wizards/space-station-14/commit/d43ed3210c254caeacf2ca1e7e2056e15c9fb73e

Haven't tried reproducing, but just based on the yaml this is still an issue.

Either #7976 needs to be revived (which is missing a `ClothingBackpackSatchelClown` prototype), or the satchel customization option just needs to be removed from the clown's starting gear.

**Comment by Willhelm53** [comment] 2022-10-26 15:45
#3743 would likely help with part of this one.

**Comment by IProduceWidgets** [comment] 2024-05-13 08:12
I think this is resolved? At least I have not seen anyone complain about it in thousands of rounds.

Maybe also partially addressed by https://github.com/space-wizards/space-station-14/pull/25715

**Comment by mirrorcult** [comment] 2024-05-14 06:40
loadout fixd

**Closed by mirrorcult** 2024-05-14 06:40 UTC
Labels: Issue: Bug, Priority: 2-Before Release, No C#, Difficulty: 1-Easy
