### ISSUE TITLE
Bible healing/bonking other players currently non functional.

### ISSUE THREAD

**Issue by PolarTundra** [space-wizards/space-station-14#27315] opened 2024-04-25 15:47 UTC
Healing with the Bible is currently bugged. Clicking someone with the bible, whether they have a hat or not, will cause a cooldown on the bible and do absolutely nothing, it will not hit them nor heal them.

Making holy water still works.

to reproduce, just try to left click with the bible as a Bible compatible role attempting to heal or hit someone with the bible does not work and will incur a visible cooldown on the bible's icon.

**Comment by Tayrtahn** [comment] 2024-04-25 23:48
Duplicate of #27815

A fix is PRed and awaiting re-review.

**Closed** 2024-04-25 23:48 UTC
Labels: Status: Untriaged
