### ISSUE TITLE
Respawn is no longer a recognized command, despite existing

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#28850] opened 2024-06-11 05:33 UTC
## Description
A recent update changed the perms of multiple commands, including respawn.

**Reproduction**
1. Attempt to respawn a person thru console or verb
2. Seethe.

**Screenshots**
![20240611003232_1](https://github.com/space-wizards/space-station-14/assets/104110869/b6c643c3-266c-4619-b8f7-3166f227f2bf)

**Additional context**
(thanks tsjiptsjip) Consoles erroneously report commands you don't have permissions for as unrecognized

**Comment by TsjipTsjip** [comment] 2024-06-11 05:43
Ran into this bug in relation to https://forum.spacestation14.com/t/permission-changes-should-be-included-in-codebase-changes/8813 , was going to file a GitHub issue for this.

For full clarity, the reporter did not configure the new +MOD permission for their admin ranks. The commands still exist. The issue however is the fact that the client does not recognise this as a command which you have no permissions for instead stating erroneously that the command doesn't exist, that being bad feedback for the issuer of the command.

**Comment by slarticodefast** [comment] 2024-12-10 01:42
This was caused by https://github.com/space-wizards/space-station-14/pull/28451 which introduced the new "Moderator" admin flag which is needed to use the respawn command.
I'm closing this issue since this is working as intended.
However, I agree that the communication with fork admins should have been better for this change.

**Closed by slarticodefast** 2024-12-10 01:42 UTC
Labels: S: Untriaged
