### ISSUE TITLE
Reinforced walls are too easy to destroy

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#11813] opened 2022-10-10 07:45 UTC
## Description
Reinforced walls can be destroyed very quickly using melee. The mini hoe found in perma can destroy one in 20 hits. Toolboxes take 29 hits. At a rate of one melee strike per second, it is currently quicker to use crude melee weapons to destroy a wall than it is to actually deconstruct it with tools.

This also brings up alot of other issues since perma prisoners can easily bust their way out of perma with simple garden tools, usually in under a minute. 

**Additional context**
Reinforced walls should either have more health, or damage reducing properties so that only the strongest of melee weapons can break through them in a reasonable amount of time.

**Comment by Scribbles0** [comment] 2022-10-10 18:16
using heavy or light attacks?

**Comment by asperger-sind** [comment] 2022-10-11 04:20
> using heavy or light attacks?

I believe after melee rework you can only deal damage to structures such as walls with heavy attacks.

**Comment by Kayek14** [comment] 2022-10-13 05:33
This was all using light attacks.

**Comment by keronshb** [comment] 2022-10-13 13:52
This seems like a dupe of your other issue #11812

**Closed** 2022-10-14 02:17 UTC
