### ISSUE TITLE
Medscanners don't like players

### ISSUE THREAD

**Issue by partyaddict** [space-wizards/space-station-14#632] opened 2020-02-08 13:26 UTC
![image](https://user-images.githubusercontent.com/31222036/74085907-e1e91780-4a75-11ea-86dd-b6851194c7cb.png)
Medscanners get you stuck when you eject from them.

Medscanners also prevents you firing guns after you eject from one.
Melee works though

**Comment by ShadowCommander** [comment] 2020-02-08 15:56
Duplicate of #385

**Closed by ShadowCommander** 2020-02-08 15:56 UTC
Labels: Type: Bug
