### ISSUE TITLE
Dead spiders appear under scrubbers

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#17203] opened 2023-06-08 06:19 UTC
## Description

This likely affects many other mobs/items, but I only tested with spiders/scrubbers

**Reproduction**

1. Have an anchored scrubber with a tile on it
2. Kill a spider, crit isn't enough
3. Drag it over the scrubber a bit, it doesn't happen in all positions but does in most/many

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/119664036/c0ce39d1-af9b-4b03-bc7e-f4693163e88c)

**Comment by metalgearsloth** [comment] 2023-06-08 14:42
More or less dupe of https://github.com/space-wizards/space-station-14/issues/17034

**Closed by metalgearsloth** 2023-06-08 14:42 UTC
