### ISSUE TITLE
Hotkeys vanish while playing

### ISSUE THREAD

**Issue by MissKay1994** [space-wizards/space-station-14#24791] opened 2024-02-01 02:39 UTC
While playing, your hotkeys will disappear, leaving you unable to do any actions with your outfit tools, and so on. I've seen this talked about various times, and was told to make a report out it happening.

The only current fix, is closing the game out and restarting it. I am going to guess, it is related to the game desyncing the client from the server, and forgetting anything the client has in the hotkeys bar

[client.stdout(HUD gone).log](https://github.com/space-wizards/space-station-14/files/14119570/client.stdout.HUD.gone.log)

**Comment by VasilisThePikachu** [comment] 2024-02-03 14:38
Duplicate of #20483

**Closed by VasilisThePikachu** 2024-02-03 14:38 UTC
