### ISSUE TITLE
Space dragons freeze to death in space

### ISSUE THREAD

**Issue by Veritius** [space-wizards/space-station-14#31620] opened 2024-08-29 10:44 UTC
Salamander round 64112.

**Comment by Veritius** [comment] 2024-08-29 10:53
this probably also happens by just being in a spaced area

**Comment by Everturning** [comment] 2024-08-29 15:35
they're space dragons wdym they need to be able to survive in space. they are DEPENDENT on stations. its in their name. station dragons.

**Comment by godisdeadLOL** [comment] 2024-09-01 14:38
If you play as a space dragon and do nothing it gets deleted after some time even in warm environment. It's `coldDamageThreshold` is 0 which means it doesn't get any cold damage. Yet UI says it's too cold.

**Comment by Veritius** [comment] 2024-09-15 04:48
well the UI didn't say I was bleeding so... what the hell killed me

**Comment by JIPDawg** [comment] 2024-09-15 04:56
Did you have an active portal? You slowly die without one.

**Comment by JIPDawg** [comment] 2024-09-15 05:10
Just tested on deb build. Flew around in space no problem. 0 damage. I did get the cold ui warning, but it didn't affect me in the slightest.

**Comment by muburu** [comment] 2024-09-15 05:27
> Did you have an active portal? You slowly die without one.

pretty sure you just despawn after 5 mins without a portal, no damage over time taken

**Comment by JIPDawg** [comment] 2024-09-15 05:49
> well the UI didn't say I was bleeding so... what the hell killed me

Alright I watched the replay. You died due to lack of blood. You were not bleeding, but your blood levels were under 90% which is when I believe you start taking Airloss: Bloodloss damage. Issue can be closed as everything is working as intended.

https://github.com/user-attachments/assets/b04815fe-809d-4636-8a32-4c822bd50c8b

**Comment by Errant-4** [comment] 2024-09-15 05:58
This sounds like a UI issue to me, then

**Comment by JIPDawg** [comment] 2024-09-15 06:03
> This sounds like a UI issue to me, then. Perhaps something should still be done about it

Yeah, it's always been like this afaik. I think it's because when you are low on blood you screen gets Shakey which is usually the tell for low blood, but I guess dragon isn't affected?

**Comment by Errant-4** [comment] 2024-09-15 06:25
> > This sounds like a UI issue to me, then. Perhaps something should still be done about it
> 
> Yeah, it's always been like this afaik. I think it's because when you are low on blood you screen gets Shakey which is usually the tell for low blood, but I guess dragon isn't affected?

Also, thank you for the investigation.

**Comment by Errant-4** [comment] 2024-09-15 06:27
Space damage was disproven, cause of dragon death was unrelated pre-existing medical trauma.

**Closed by Errant-4** 2024-09-15 06:27 UTC
Labels: Issue: Bug
