### ISSUE TITLE
Personal AI apparently gets o2 Loss and lose vision

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#16780] opened 2023-05-24 16:59 UTC
## Description

**Reproduction**

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment] 2023-05-24 17:06
![18:06:34](https://github.com/space-wizards/space-station-14/assets/39013340/2304a3c8-89ef-4694-a439-321a563065cb)
cant reproduce on master

**Comment by Geekyhobo** [comment] 2023-05-26 20:58
Can we close this?

**Closed** 2023-09-01 16:31 UTC
