### ISSUE TITLE
Disable butchering for humanoids

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#10678] opened 2022-08-18 05:27 UTC
While a neat gameplay mechanic way too many griefers on LRP to facilitate this mechanic.

**Comment by Elijahrane** [comment] 2022-08-18 10:45
> Oh, yeah, almost forgot. Just removing meat spike feature will exacerbate problems with miasma gas through removal one of ways medbay can remove useless bodies.

fixed by biomass whenever that gets merged

**Comment by Elijahrane** [comment] 2022-08-18 10:47
> I do assume biomass conversion can round-remove...

only unsouled bodies with the default cvar

**Comment by Elijahrane** [comment] 2022-08-18 10:51
> Not being able to biomass some L6 SAW murderboner traitor seems counter-intuitive. Or rather, "hugbox".

that's something I trust a whitelisted MRP server to be able to handle but not 65 player NRP

**Comment by metalgearsloth** [comment] 2022-08-18 10:52
Chefs roundending players has been a problem for a long time. When the do_after got made 10 seconds it got better but as the playerbase has gotten worse so too has this problem.

> just pull out banhammer.

Admins are not omnipresent and we shouldn't try to skirt every griefing issue with throwing more staff at a problem.

**Comment by OldDanceJacket** [comment] 2022-08-18 17:29
The proper solution is not to balance, or consider LRP(NRP) in any serious way and to actually balance and focus around MRP instead.

The game and it's systems are not intended for LRP(NRP), and time and time again this is proven to be the case.

Here lets think for a moment.

"I don't want people butchering other players to grief."
Okay, lets see why this is happening:
"Chef role is barely functional, and need to be constantly outputting food, meat is a great source of food."
So this is a problem. Let's see...

"Human meat doesn't make you sick."
"Server is NRP."
So because human meat doesn't make you sick, and the server is NRP, dead bodies are constantly tossed to the Chef for them to make food(it is also encouraged), throw this atop of the 'hehe, special meat' and 'what does SSD mean' and you get people on meat spikes being too common. 
How about instead of trying to go about removing a function of the game that's fun and benefits stealth traitors we can make Chef not suck, human meat toxic, and as a community(admins and players) actually step up and tell people to stop eating human meat as if its an okay thing to do?

.

Also being permanently taken out of the round is only a mega serious issue because there's no ghost roles/mid round stuff to wait around for, and because of the server cap you don't want to bounce otherwise you might not get back in on the next round.
Everything is connected.

**Comment by keronshb** [comment] 2022-08-18 17:59
Citadel solved this issue by not allowing the brain to be deleted during explosions/gibbing. I'm not sure how far along SS14 is with medical but if we have cloning and surgery, it's usually as simple as throwing the brain into the cloner or in a new body.

**Comment by JustinTrotter** [comment] 2022-08-18 18:51
Why not just make it optional? We could just tie it to ccvar flag to enable/disable it and the admins of each server could decide if it's worth the trouble.

**Comment by retequizzle** [comment] 2022-08-18 19:52
> Why not just make it optional? We could just tie it to ccvar flag to enable/disable it and the admins of each server could decide if it's worth the trouble.

Seems the most reasonable in theory. 

I'd also be down for butchering with a meatspike to take longer. I'd rather punish a singular role with longer do-afters or even implement a soul check of some kind. If the game can differentiate between clonable and not clonable when it comes to cloning machines, a similar principle might work with spiking as well.

**Comment by HoidC** [comment] 2022-08-18 20:02
> > Why not just make it optional? We could just tie it to ccvar flag to enable/disable it and the admins of each server could decide if it's worth the trouble.
> 
> Seems the most reasonable in theory.
> 
> I'd also be down for butchering with a meatspike to take longer. I'd rather punish a singular role with longer do-afters or even implement a soul check of some kind. If the game can differentiate between clonable and not clonable when it comes to cloning machines, a similar principle might work with spiking as well.

May I ask what making it longer actually achieves? If a chef needs meat/wants to gib a player they're going to gib a player using the meatspike. Just makes it take longer for legit chefs. Role is already sucky. Soul check sounds like a good idea. This isn't meant to be me pointing holes in your argument, just wondering what a longer doafter does. Is it to discourage?

**Comment by asperger-sind** [comment] 2022-08-18 22:40
> I'd also be down for butchering with a meatspike to take longer. I'd rather punish a singular role with longer do-afters.

Honestly, I'm against this, unless its unique for specific entities, or weight-based, so butchering a simple monkey with a spike, which were genetically modified to be the near-perfect source of renewable meat shouldn't take as long as butchering a full on cow or a human, even then meatspike do-afters already take around 20~ seconds of standing completely still without doing anything AND your position is universally revealed to the players around you in the radius of your entire screen and then some.

**Comment by Renlou** [comment] 2022-08-18 23:09
Man I knew this was gonna cause a kerfuffle the moment I saw it  😂  Not gonna be ideaguy tho Ill say I would indeed very much miss the meat spike so I hope it makes a comeback in some shape or form down the line. (If it does get removed)

**Comment by deltanedas** [comment] 2023-11-16 19:32
soul check fixed this

**Comment by Ron-the-wizzard** [comment] 2023-11-22 18:19
i suggest the meatspike not gib; however take meat as intended. 
 the Real way to gib bodies should be a hacked meatball maker or trash compactor thingy
 this problem is very trickey however there is always seeing how ss13 did it
 also maybe we should put the "dont kill SuddenSleepDisorder'd people its very rude" as a warning to new ss14 players

**Closed** 2024-01-15 01:54 UTC
Labels: Priority: 2-Before Release, Difficulty: 1-Easy, Issue: Balance
