### ISSUE TITLE
Revenants can spill liquid containers

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#30141] opened 2024-07-18 04:26 UTC
## Description
Revenants have access to the spill liquid verb. This allows them to grief medbay by spam spilling chem jugs with no risk to themself.

**Video**

https://github.com/user-attachments/assets/ff05745e-1416-46bb-8842-8ef1eb1278ef

**Additional context**
From the report it seems that revs can also spill jugs that are inside closed lockers and duffle bags, but i was unable to replicate this. I believe it is possible however if the rev opens the right click context menu before the locker is closed or the jugs are placed inside a bag and then clicks on the spill verb.

![image](https://github.com/user-attachments/assets/4a00dbd5-6bd7-46c8-8219-2dfe8469b871)

**Comment by UbaserB** [comment] 2024-07-18 04:33
Dupe of #24861

**Closed by UbaserB** 2024-07-18 04:33 UTC
Labels: Status: Untriaged
