### ISSUE TITLE
cant save item locations in storage anymore

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#30947] opened 2024-08-12 16:24 UTC
## Description
simply doesnt do anything, even if rebinding the key to something else

**Comment by lzk228** [comment] 2024-09-03 14:54
well it's actually a dupe of #30947 :trollface:

**Comment by deltanedas** [comment] 2024-09-03 14:56
dupe of my own issue so true

**Closed** 2024-10-17 04:00 UTC
Labels: Issue: Bug
