### ISSUE TITLE
Combine device configurator into multitool

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#16594] opened 2023-05-19 06:56 UTC
I think emisse and I both want it iunno bout other maints if I get time ill get around to it soonTM.

**Comment by juliangiebel** [comment] 2023-05-19 07:24
This is a duplicate of: #16241 
And has already been addressed in: #16289 which has been discussed on discord.
This is the end of that discussion which had been going for a bit already:
![image](https://github.com/space-wizards/space-station-14/assets/8915246/871b3c69-3110-415c-a77d-21f35a071ff7)

**Comment by juliangiebel** [comment] 2023-05-22 13:23
@metalgearsloth can I close this or is there still something you're not happy about with how linking is put back into the multitool

**Closed** 2023-05-23 08:58 UTC
Labels: Priority: 3-Not Required, Issue: Feature Request, Difficulty: 1-Easy
