### ISSUE TITLE
Issues when dragging and things being stuck in your hand

### ISSUE THREAD

**Issue by Elysium206** [space-wizards/space-station-14#24921] opened 2024-02-03 16:53 UTC
## Description

Had about 7-8 seperate people ahelp me over this issue over the course of 2 rounds. People are loosing use of their hand and relogging does not fix it. i also tried "resetent" and it didnt fix it either.
 the bug seems to be when you are dragging something and someone drags you. or possibly two people dragging the same thing as well. examples i saw were doctors dragging bodies and janitors pulling their janicarts. Effects were that they lost use of one of their hands and i could not seem to find anything in their hand on my end.
**Reproduction**

unsure as to how to reproduce at the moment. i asked the reporters to describe the situations at the time of the bug happening and these are the ones that might be useful
**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/151651971/9086b8a6-96a0-4b4e-9102-3cac430e7090)
![image](https://github.com/space-wizards/space-station-14/assets/151651971/f3f66e1b-5f66-42f8-8e42-03a14a9721e7)
![image](https://github.com/space-wizards/space-station-14/assets/151651971/4eaaf2b2-eb98-4a16-b12e-763e3797878b)
![image](https://github.com/space-wizards/space-station-14/assets/151651971/d90f4b29-88f0-48f8-bfc9-e4d806a593bc)
![image](https://github.com/space-wizards/space-station-14/assets/151651971/a60a45c2-c1f6-4239-b00e-a0d1635ce6f3)
![image](https://github.com/space-wizards/space-station-14/assets/151651971/dbc7fdc1-8d28-4d65-aea1-ae453e0e7049)

**Additional context**

**Comment by deltanedas** [comment] 2024-02-03 17:29
dupe of #24900

**Closed** 2024-02-14 00:39 UTC
