### ISSUE TITLE
ViewVariables as is does not work with ECS

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#4587] opened 2021-09-10 18:01 UTC
How should we design the new vv system?

Discuss.

**Comment by Ygg01** [comment] 2021-09-12 09:37
The view part of VV is working, the problem is changing the properties. 

Changing stuff outside of EntitySystem in ECS is always going to be awkward.

**Comment by Ygg01** [comment] 2021-09-12 09:42
@Zumorica you had some ideas regarding this, right?

**Comment by Zumorica** [comment] 2021-09-13 08:59
Duplicate of https://github.com/space-wizards/RobustToolbox/issues/1772, this is not the repo for this

**Closed by Zumorica** 2021-09-13 08:59 UTC
Labels: Priority: 1-Urgent, Type: Discussion, Type: Refactor, Difficulty: 3-Hard
