### ISSUE TITLE
you can install netprobe multiple times

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#22437] opened 2023-12-13 05:18 UTC
![image](https://github.com/space-wizards/space-station-14/assets/130668733/ef478732-0354-4ff0-9c55-8a0a7fd896ec)

**Comment by Tunguso4ka** [comment] 2023-12-13 08:19
duplicate of #21561
:trollface:

**Closed** 2023-12-13 09:08 UTC

**Comment by JoeHammad1844** [comment] 2023-12-13 22:46
oopsie poopsie
