### ISSUE TITLE
Dwarves having   noRot: true

### ISSUE THREAD

**Issue by Myakot** [space-wizards/space-station-14#15971] opened 2023-05-01 11:37 UTC
## Description
Almost every single unique feature of dwarves is great, they have next to none weaknesses, besides carrying somebody and being disarmed due to their mass. Turns out, they also have   noRot: true
Dionas also have   noRot: true, but they have so many negatives, that it's almost fine and a unique ability of theirs.

The only reason I can see dwarves having   noRot: true is that they drank so much alcohol in their lives, that they are essentially alcohol itself. Then change their bloodstream to ethanol.

**Comment by EmoGarbage404** [comment] 2023-05-01 12:10
By `noRot: true`, do you mean that the sprites do not rotate with the camera?

**Comment by Myakot** [comment] 2023-05-01 12:21
> By `noRot: true`, do you mean that the sprites do not rotate with the camera?

I think I made quite a fool of myself, I thought that answers whether the body rots or not. My bad.
Then the actual bug is that dwarves just don't rot, at all. Launched local server, alt-tabbed for 30+ minutes and they were still fresh to clone.

**Comment by crazybrain23** [comment] 2023-05-01 13:30
This is a prime example of why abbreviations are confusing.

**Comment by deltanedas** [comment] 2023-05-01 13:30
its not dwarf specific happens to everyone, dupe of 15968

**Closed** 2023-05-01 15:54 UTC
