### ISSUE TITLE
When the low wall under a window is destroyed it should cause the window to break

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#4520] opened 2021-08-24 05:23 UTC
## Description

I'm not sure if this is the *right* way.

Otherwise you get stuff like V

**Screenshots**

![](https://media.discordapp.net/attachments/790656972801572905/879596024019157052/yat8sN3.png)
**Additional context**

**Comment by mirrorcult** [comment] 2021-09-15 21:41
dupe of #3919

**Closed by mirrorcult** 2021-09-15 21:41 UTC
