### ISSUE TITLE
You are able to swap batteries on Ninja once.

### ISSUE THREAD

**Issue by JIPDawg** [space-wizards/space-station-14#30083] opened 2024-07-16 03:51 UTC
## Description

As Ninja you are able to swap out your battery for a bigger capacity battery, it seems you are only able to do this once and I'm being told you shouldn't be able to at all.

**Reproduction**

1. Find bigger battery.
2. Swap battery, enjoy bigger battery
3. Unable to swap battery again.

**Screenshots**

https://github.com/user-attachments/assets/cc0c2217-afe6-4c0a-842d-7f9b18933494

**Additional context**

It seems that you are able to change out your battery, but only once sometimes even twice, it seemed really hit or miss on that. It does not appear to be a mispredict. Only time it does look like a mispredict is after the first time swapping out the battery.

**Comment by Radezolid** [comment] 2024-07-16 05:11
Dupe of https://github.com/space-wizards/space-station-14/issues/29477. But you are able to upgrade your battery, never go one down or one of the same tier.

Low cap -> Mid cap -> High cap

**Comment by IProduceWidgets** [comment] 2024-07-21 19:50
> Dupe of https://github.com/space-wizards/space-station-14/issues/29477

**Closed by IProduceWidgets** 2024-07-21 19:50 UTC
Labels: Status: Untriaged
