### ISSUE TITLE
StorageVisualizer/StorageCounter/BagOpenCloseVisualizer issues

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3287] opened 2021-02-18 04:15 UTC
## Description

Bugs

- If you have an entity with valid storage counter inside of another entity without storage counter, your console will be spammed with error logs about "No need for tags" etc. on spawning the nest entity.
- If you open an entity, (cig packet) then switch to your other empty hand and move the open cig packet to that hand the cig packet will close and refuse to show and open sprite again. Also spams your console with errors about layers not existing.
- If you open an entity (cig packet) then place it on the ground and close the window, it'll close and refuse to open like the above. This also is the case with throwing, getting stunned etc.

**Comment by SweptWasTaken** [comment] 2021-02-18 04:15
@Ygg01

**Comment by Ygg01** [comment] 2021-02-19 14:33
Assign this to me

**Comment by Ygg01** [comment] 2021-02-21 15:16
Root Cause 1: There's a `DefaultSerializer` that is invoked I just need to not log for it.
Root Cause 2 & 3: Missing `netsync: false`

**Comment by PaulRitter** [comment] 2021-02-27 11:11
can i close this? cause 1 is fixed, what about the others?

**Comment by Ygg01** [comment] 2021-02-27 11:13
Yeah. Other were missing netsync false.

**Closed** 2021-02-27 11:36 UTC
