### ISSUE TITLE
shiva can pry bolted doors

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#27087] opened 2024-04-18 09:44 UTC
## Description
wtf real

**Comment by nikthechampiongr** [comment] 2024-04-18 09:51
Unfathomably based. Anyways that's because Shiva inherits from the spider proto which has the prying component with pryPowered(pry powered doors) and force(pry bolted doors) bools to true.

**Comment by nikthechampiongr** [comment] 2024-04-18 09:53
See #23449

**Comment by Brandon-Huu** [comment] 2024-06-20 15:41
Should this issue be closed?

**Comment by eoineoineoin** [comment] 2024-12-20 11:11
Duplicate of https://github.com/space-wizards/space-station-14/issues/30157

**Closed by eoineoineoin** 2024-12-20 11:11 UTC
Labels: S: Untriaged
