### ISSUE TITLE
Tapping a borg once to unlock it repeats the action a bunch of times.

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#29488] opened 2024-06-26 11:46 UTC
**Reproduction**

1. Have the borg locked, and don't have access to unlock it
2. Left click the borg once
3. Notice that you just tried to unlock the borg a bunch of times (???)

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/ed3a0aec-b745-4aa4-83c7-2f6c26fa30b6)

**Comment by Tayrtahn** [comment] 2024-06-26 13:30
Duplicate of #28746

**Closed** 2024-06-26 13:33 UTC
Labels: Issue: Bug
