### ISSUE TITLE
ghost warping out of a test area deletes all your actions

### ISSUE THREAD

**Issue by QuietlyWhisper** [space-wizards/space-station-14#21012] opened 2023-10-15 14:51 UTC
## Description

Not sure what causes this.
As far as I can test on a live server, it's only a bug with the admin test area...

**Reproduction**

I use the verb to teleport to the test area, then use the ghost warp menu to go to any location on the station. I lose all my actions.

**Comment by ElectroJr** [comment] 2023-10-28 17:34
Closing this as it is likely a duplicate of #21063

**Closed by ElectroJr** 2023-10-28 17:34 UTC
