### ISSUE TITLE
Grids can spawn within eachother at round start.

### ISSUE THREAD

**Issue by Mirino97** [space-wizards/space-station-14#28413] opened 2024-05-30 16:16 UTC
Server: Lizard
RoundID: 54953

Sindy Puddle spawned inside the station's maints, requiring griddragging to fix it.

I'll paste some pics after replay's out, I forgor.

**Comment by ShadowCommander** [comment] 2024-05-30 18:16
Duplicate of #27667

**Closed by ShadowCommander** 2024-05-30 18:16 UTC
Labels: Status: Untriaged
