### ISSUE TITLE
In-hand sprites don't update properly after being stunned.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4412] opened 2021-08-02 17:23 UTC
![image](https://user-images.githubusercontent.com/7907891/127899826-50fd6899-cf04-4dfc-9063-1c1bf3700139.png)

This was originally reported by CrudeWax#6287 on Discord. I have replicated it successfully on a fully-updated local environment.

How to reproduce:

- Have a powered and active stun baton in your hand.
- Click yourself. It may take a few tries to achieve stun.
- You will drop the stun baton, but your sprite will still show an active stun baton in-hand.
- This state will end if you are stunned again, pick up an item, or switch hands.

It appears that it doesn't matter if you have combat mode on or not when you do this, as I've tested in both states.

**Comment by mirrorcult** [comment] 2021-08-06 05:28
does it also occur for other items that you have inhand after being stunned? not just the baton?

**Comment by TimrodDX** [comment] 2021-08-06 21:25
Yes it does. I had not thought to test it with other items, but now that I have, it definitely does. I'll change the report's title.

![image](https://user-images.githubusercontent.com/7907891/128572545-a37c83cc-4858-4820-af46-2b868ba99234.png)

**Comment by metalgearsloth** [comment] 2021-08-07 02:51
Dupe of https://github.com/space-wizards/space-station-14/issues/4233 visualizers for hands don't update properly.

**Closed by metalgearsloth** 2021-08-07 02:51 UTC
Labels: Type: Bug, Difficulty: 1-Easy, Bug: Replicated
