### ISSUE TITLE
Cargo shuttle sometimes fuses with station during docking

### ISSUE THREAD

**Issue by martin69420** [space-wizards/space-station-14#10751] opened 2022-08-21 08:08 UTC
## Description
Title

**Reproduction**
Dock with station

**Screenshots**
![ship fused with station 2](https://user-images.githubusercontent.com/63034378/185781955-11b7dbd9-2c31-462a-9e42-eb801aabd2c2.PNG)
![ship fused with station](https://user-images.githubusercontent.com/63034378/185781962-a1b9266b-c9b4-413e-ad44-9c2dea380813.PNG)

**Comment by Just-a-Unity-Dev** [comment] 2022-08-21 08:11
![image](https://user-images.githubusercontent.com/67359748/185782053-0a78e15e-a9b7-4bf2-b9fc-7a68a34e26c8.png)

Additional imagery

**Comment by metalgearsloth** [comment] 2022-08-21 09:01
https://github.com/space-wizards/space-station-14/issues/9055 is more about making the joints softer and adding breakage but it is a dupe of https://github.com/space-wizards/space-station-14/issues/10406

**Closed by metalgearsloth** 2022-08-21 09:01 UTC
