### ISSUE TITLE
Flying mobs take damage when moving over glass shards

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#12066] opened 2022-10-20 06:14 UTC
## Description
Flying mobs such as Remilia and bees take damage when they move over glass shards.

**Reproduction**
1. Spawn in a glass shard.
2. Spawn in Remilia or a bee
3. watch as they take damage when moving over the glass shard.

**Additional context**
Normally, glass shards do damage to players if they are not wearing shoes. Flying mobs should be immune to this.

**Comment by Elijahrane** [comment] 2022-10-20 07:58
Duplicate of https://github.com/space-wizards/space-station-14/issues/9864

**Closed** 2022-10-31 05:24 UTC
