### ISSUE TITLE
Carpets on tables issue

### ISSUE THREAD

**Issue by Stares-at-sun** [space-wizards/space-station-14#25866] opened 2024-03-05 19:16 UTC
Using carpets on a table in a stack will consume the entire stack.

Noticed the bug yesterday, no idea if this has been reported at all but  as someone who loves making the station pretty its an annoying thing to work with.

**Comment by Tayrtahn** [comment] 2024-03-05 20:42
Duplicate of #25687

**Comment by TheShuEd** [comment] 2024-03-06 23:48
Yep, duplicate

**Closed as not planned by TheShuEd** 2024-03-06 23:48 UTC
