### ISSUE TITLE
Certain announcements don't play sounds like they're supposed to 

### ISSUE THREAD

**Issue by baddiePRO** [space-wizards/space-station-14#26186] opened 2024-03-16 19:24 UTC
## Description
when certain station wide announcements are sent, they do not play the bell sound like they are supposed to, also applies to the soundbytes for antag roles

**Reproduction**
join round, wait for command/centcomm/antag message in chat

**Comment by Dutch-VanDerLinde** [comment] 2024-03-16 19:31
dupe of https://github.com/space-wizards/RobustToolbox/issues/4970, should be fiexd next update

**Comment by baddiePRO** [comment] 2024-03-16 19:36
awesome, thanks

**Closed** 2024-03-17 00:48 UTC
