### ISSUE TITLE
Attacking is broken in debug mode (sometimes)

### ISSUE THREAD

**Issue by keronshb** [space-wizards/space-station-14#15113] opened 2023-04-03 21:37 UTC
## Description

In debug mode I can attack with my fists, but not with a spear, captains sword, crowbar, welder, etc. But this doesn't happen all the time?

EDIT: Apparently none of the pre spawned items can be used to attack. If you spawn in a different item (IE crowbar) you can attack with the newly spawned crowbar but not the old one.

**Reproduction**

Grab any of the starting items, go into combat mode, and try clicking.

**Screenshots**

https://user-images.githubusercontent.com/54602815/229632875-c68ece21-2f42-4ee7-9b05-e40b393408fd.mp4

**Additional context**

**Comment by ElectroJr** [comment] 2023-04-04 05:36
Pinging @metalgearsloth cause its related to pause time & TimeOffsetSerializer.

The cause seems to be a combination of the fact that picking up weapons while mapping causes  the next-attack-time to be set, along with some side effects due to how TimeOffsetSerializer includes pause time.

E.g.,
- pause map at t=10
- at t=20 pick up weapon, starts a 1-second delay, so next-attack-time is set to t=21
- at t=30 save map. Map has been paused for 20 seconds.
- TimeOffsetSerializer saves next attack time as nextAttack-(curTime-pausedTime) = 21-(30-20) = 11.
- The result is that when map is loaded, cannot use weapon to attack for first 11 seconds.

I don't really know of a good general fix for this other than always checking if an entity is currently paused before setting any offset-serializer fields, but there's no way of enforcing this and this will probably cause more bugs later on.

**Comment by metalgearsloth** [comment] 2023-04-04 05:43
This is also https://github.com/space-wizards/space-station-14/issues/13008

Ideally mapping wouldn't do any sorts of container changes as other hidden bugs are likely happening in map files as well (occasionally I'll see random datafields get added or removed as it is to entities) and mappers would just drag the entity around. Even if melee is fixed stuff like interaction cooldown or guns or any other number of systems may have unexpected issues.

What's best is probably removing aghost hands and adding a separate system for it. If they need to change a few entities at once then let them select them for bulk movement.

**Comment by keronshb** [comment] 2023-04-04 16:42
It's also #15096

**Closed** 2023-04-05 23:37 UTC
