### ISSUE TITLE
Rejuvenate doesn't cure diseases.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14#7879] opened 2022-04-30 11:33 UTC

**Comment by Peptide90** [comment] 2022-04-30 15:24
#5743 also related to rejuvenate for anyone taking a look.

**Comment by Elijahrane** [comment] 2022-04-30 19:38
Works on my machine, I closed https://github.com/space-wizards/space-station-14/issues/7485 via https://github.com/space-wizards/space-station-14/pull/7495 a while ago. Did it stop working? I can't reproduce

**Comment by UKNOWH** [comment] 2022-05-01 02:20
Pretty sure it does cure

**Comment by Peptide90** [comment] 2022-05-02 10:32
Just tested locally and it seems to work. Tested by giving myself OwO and rejuventaing. It still shows under all diseases but passes it to "past diseases" so closing.

**Closed by Peptide90** 2022-05-02 10:32 UTC
Labels: Issue: Bug, Priority: 2-Before Release, Difficulty: 1-Easy
