### ISSUE TITLE
RCD cant place things under things it should

### ISSUE THREAD

**Issue by XxSWAG-MASTER-OVERLORDxX** [space-wizards/space-station-14#28449] opened 2024-05-31 14:21 UTC
## Description
With the RCD you cant place glass or walls under blast doors or shutter, you can build them by hand in those spots and they come mapped in those spots but you are unable to use the RCD to construct them

**Reproduction**
1 Try to use RCD to fix HoP line windows/ HoS windows to space or anyother instance of a window and a blastdoor/shutter overlap
2 be sad as construction is blocked

**Comment by Lamrr** [comment] 2024-06-01 02:37
Duplicate of #27167

**Closed** 2024-09-14 01:53 UTC
Labels: Status: Untriaged
