### ISSUE TITLE
The smite that turns someone into a lizard does not work.

### ISSUE THREAD

**Issue by Madformoose** [space-wizards/space-station-14#29651] opened 2024-07-01 20:13 UTC
## Description
The smite that turns someone into a lizard does everything except changing their actual sprite, which may be fine if you wanna scream funny or eat rats without getting sick but not very good for actually turning someone into a lizard.

**Reproduction**
Smite someone with being a reptilian, observe that their sprite remains as that of a human, observe that they have the lizard typing indicator, observe that they have the lizard scream, observe that they can select the option to wag their tail (although it doesn't do anything), cry, make an issue on github

**Comment by bruhmogus** [comment] 2024-07-02 11:50
i have no clue but it might be related to the humanoidappearance component?

**Comment by IProduceWidgets** [comment] 2024-07-05 16:54
Dupe of 21337

**Closed by IProduceWidgets** 2024-07-05 16:54 UTC
Labels: Status: Untriaged
