### ISSUE TITLE
Salvage Shuttle Console makes you wait FOREVER (sometimes) before letting you FTL to a planet.

### ISSUE THREAD

**Issue by Aexxie** [space-wizards/space-station-14#29452] opened 2024-06-25 09:59 UTC
## Description

Title says it all. No clue how this seemingly hasn't been reported yet. First started appearing after the shuttle console refactor.

**Reproduction**

1: Accept an exped
2: Insert disk into shuttle computer
3: Click "Scan" under the "Map" menu on the shuttle console. FTL for the planet should take a while to show up. The time for it to show up can range anywhere between 30 seconds and 10 minutes if you're unlucky.

**Screenshots**

**Additional context**

Seems to be caused by the scan gradually revealing objects that are further away.

**Comment by ShadowCommander** [comment] 2024-06-25 15:01
Duplicate of #26348

**Closed by ShadowCommander** 2024-06-25 15:02 UTC
Labels: Issue: Bug, Priority: 3-Not Required, Difficulty: 2-Medium, Bug: Replicated
