### ISSUE TITLE
Stun batons don't go into their "off" sprite if they lose charge from being thrown

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3832] opened 2021-04-12 02:29 UTC
Very minor bug, but very fun to reproduce.

![image](https://user-images.githubusercontent.com/7907891/114332891-18587180-9b15-11eb-9890-f649b15e921e.png)

- Spawn a bunch of Urists in a close formation like this.
- Turn on your stun baton and throw it at them.
- The baton will rapidly lose charge after hitting a few of them (though the fact that one thrown stun baton can down more than 10 people in a single throw is kind of ridiculous). You'll know when it's out of charge because it'll stop colliding with people when thrown.
- The baton won't go into its "off" sprite unless you turn it off, at which point the baton will inform you that the cell is dead. Note that even if you recharge it, the baton will stay "off" unless you turn it "off" and then back "on" again, meaning you can be walking around with what appears to be an active baton that isn't actually active.

**Comment by michaelcooke** [comment] 2021-07-30 23:11
Can't reproduce on my end:

- Throwing a stun baton does not collide with the Urists regardless of whether it's powered
- After ~50 or so hits with a fresh stun baton turned on, the stun baton sprites illustrate an off state, and a power down sound is played

**Comment by mirrorcult** [comment] 2021-07-30 23:11
throw collide stunbaton may have been broken by ECSing it @metalgearsloth

**Comment by AJCM-git** [comment] 2021-11-07 05:14
Cant reproduce either. Closing.

https://user-images.githubusercontent.com/60196617/140633204-a3195ba3-fac9-47f7-841d-163991a9d338.mp4

**Closed by AJCM-git** 2021-11-07 05:14 UTC
Labels: Type: Bug, Priority: 3-Not Required, Difficulty: 1-Easy
