### ISSUE TITLE
Torches cause a seizure-inducing flashing

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#4943] opened 2021-10-18 17:16 UTC
https://user-images.githubusercontent.com/43253663/137777156-2f0919be-918f-41dd-a574-9f28da0e5c15.mp4

**Comment by thevinter** [comment] 2021-11-07 10:58
I'm taking it. Also it looks like torches turn off after a couple of seconds in my build, not sure if someone else can replicate it as well.

**Comment by thevinter** [comment] 2021-11-07 19:56
It has been confirmed on Discord that the light does indeed disappear after ~10 seconds

**Comment by Zumorica** [comment] 2021-12-24 17:13
Fixed by a67c866319104e178c7ff500bb45e5288190f28f

**Closed by Zumorica** 2021-12-24 17:13 UTC
Labels: Type: Bug, Priority: 2-Before Release, Difficulty: 1-Easy, Changes: Sprites
