### ISSUE TITLE
Suggestion: Reduce strength of shuttle thrusters and gyroscopes

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9812] opened 2022-07-16 18:22 UTC
## Description
Reduce strength of shuttle thrusters and gyroscopes. Compact shuttle designs have insane acceleration with just one thruster serving direction and one gyro handling rotation.

**Screenshots**
This thing reaches around 40 units on linear velocity top (why do we have top speeds in vacuum) and does that in about 1 second:
![fast_and_furious](https://user-images.githubusercontent.com/108953437/179367441-ff6e0b90-1664-414d-891d-f016610f2440.png)

**Comment by metalgearsloth** [comment] 2022-07-16 18:30
Dupe of either https://github.com/space-wizards/space-station-14/issues/7685 or https://github.com/space-wizards/space-station-14/issues/5465 or https://github.com/space-wizards/space-station-14/issues/8663

**Closed by metalgearsloth** 2022-07-16 18:31 UTC
