### ISSUE TITLE
Inhaling Tritium/Plasma insta-crits you.

### ISSUE THREAD

**Issue by LordEclipse** [space-wizards/space-station-14#20382] opened 2023-09-20 23:58 UTC
**Screenshots**

https://github.com/space-wizards/space-station-14/assets/106132477/66f0b442-14c9-4919-9b11-74daf0aa243a

**Comment by Flareguy** [comment] 2023-09-21 00:02
Duplicate of #13671?

**Comment by metalgearsloth** [comment] 2023-09-21 00:03
Yeah, it's needed looking at for a long time.

**Closed by metalgearsloth** 2023-09-21 00:03 UTC
