### ISSUE TITLE
Wood fence gates have opposite build results

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#26370] opened 2024-03-24 00:10 UTC
## Description
wooden small fence gate builds to wooden high fence gate and same of for the opposite.

**Reproduction**
- build a fence gate of each type and see it build the wrong thing.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/cbfe0740-e8db-4a44-b5d3-56e8af714782)

**Additional context**
NA

**Comment by UbaserB** [comment] 2024-03-24 00:14
oh. my. god. shu literally just posted a duplicate seconds ago
Duplicate of #26363

**Closed by UbaserB** 2024-03-24 00:14 UTC

**Comment by Titian3** [comment] 2024-03-24 00:45
my bad shoulda checked first 🧷
