### ISSUE TITLE
Crowbar always gives a steel floor. 

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#973] opened 2020-05-23 18:47 UTC
1. Place any floor that isnt the steel floor
2. Use the crowbar on it
3. Now you have a steel floor tile
![image](https://user-images.githubusercontent.com/60196617/82738258-6188b280-9d04-11ea-838c-5da0e898d883.png)

**Comment by Zumorica** [comment] 2020-05-23 18:48
Duplicate of #812

**Closed by Zumorica** 2020-05-23 18:48 UTC

**Comment by FL-OZ** [comment] 2020-05-31 06:04
Steel floor is a fallback.
