### ISSUE TITLE
Something caused shuttle to violently spazz out upon docking

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#10406] opened 2022-08-08 00:21 UTC
## Description
Something caused shuttle to violently spazz out upon docking. Absolutely no idea what went wrong, I think shuttle was rotating rapidly around docking port with which it made joint upon docking.

**Reproduction**
- Dunno! Play game, I guess, this is incredibly rare and I saw this happen only once (but I did see shuttles just clip through station multiple times).

**Screenshots**
![glitched_spinny_shuttle](https://user-images.githubusercontent.com/108953437/183317007-829ff489-7441-4c4a-9183-0978b54827ec.png)

**Additional context**
Somewhat related with more physics woes: issue #10394.

**Comment by metalgearsloth** [comment] 2022-08-08 00:23
Without more info it's not getting fixed as it just seems to be a dupe of https://github.com/space-wizards/space-station-14/issues/9055

**Comment by EmoGarbage404** [comment] 2022-08-08 00:23
This issue is so incredibly vague that it is completely unhelpful. Shuttles clipping, spazzing out, and other woes are already well reported. Theres no need to open an issue with no information that could help anyone fix it.

**Closed by EmoGarbage404** 2022-08-08 00:23 UTC

**Comment by metalgearsloth** [comment] 2022-08-21 09:02
Also to note that whoever was piloting the cargo shuttle was forcing the spin which would've been useful.
