### ISSUE TITLE
Airlocks get scared from puddles in them and don't close

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#16167] opened 2023-05-06 14:01 UTC
## Description

**Reproduction**

1. get something to splash under airlock
2. door is scared too close, even if you force it with jaws

**Screenshots**

![image](https://user-images.githubusercontent.com/34938708/236628247-d9f6df12-75a4-4db9-a3ea-d39e87ebc656.png)

**Additional context**

**Comment by themias** [comment] 2023-05-06 18:08
Same root cause as #15253, the fixture used for collision detection for slipping also blocks the door from closing.

**Comment by deltanedas** [comment] 2023-05-06 18:12
could it be fixed by collision layer something something on the fixture

**Comment by keronshb** [comment] 2023-05-06 18:48
https://github.com/space-wizards/space-station-14/pull/16079 probably broke this

**Comment by VasilisThePikachu** [comment] 2023-09-04 09:55
Should this get closed?

**Closed** 2023-11-07 22:33 UTC
Labels: Issue: Bug, Status: DO NOT MERGE, Priority: 2-Before Release, Difficulty: 2-Medium
