### ISSUE TITLE
Some popup text moves when the station is in motion

### ISSUE THREAD

**Issue by jessicamaybe** [space-wizards/space-station-14#8295] opened 2022-05-19 23:12 UTC
https://user-images.githubusercontent.com/31836813/169418946-ef7edf9a-cd04-4887-9ad3-2646f3b6f516.mp4

**Comment by Vordenburg** [comment] 2023-08-06 13:49
I think this might've been fixed by #11591. I spun a station grid around and couldn't reproduce now at least. Seems to be fixed.

**Closed** 2023-08-06 13:53 UTC
