### ISSUE TITLE
RCDs suck

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [space-wizards/space-station-14#20940] opened 2023-10-12 06:12 UTC
## Description

RCDs aren't as powerful as they were in 13, being able to only create a small variety of objects (airlock/floor/solid wall/remove the above) with a *limited & small ammo charge* but as how rare they are, they are not worth anything

I propose we allow RCDs to deconstruct and reconstruct additionally: reinforced walls, reinforced windows, deconstruct airlocks, shorten the do-after time, add an animation (very important!!!) and generally just make them not worse than regularly constructing with metal.

**Comment by deltanedas** [comment] 2023-10-12 07:36
wyci :trollface:

**Comment by Just-a-Unity-Dev** [comment] 2023-10-12 15:13
feedback post not a feature request post

**Comment by keronshb** [comment] 2023-10-12 21:56
Dupe of #15708

Regular RCDs should never be able to build/decon reinforced walls. Mech RCDs should be given this.

**Closed** 2023-10-12 21:56 UTC
