### ISSUE TITLE
Lobby Screen lies about the current map

### ISSUE THREAD

**Issue by LordEclipse** [space-wizards/space-station-14#10446] opened 2022-08-08 22:35 UTC
## Description
The lobby screen could say "lighthouse" but the station is bagel station instead, this seems to happen frequently.

![image](https://user-images.githubusercontent.com/106132477/183519873-d68e7744-d1bf-46fe-a6f7-9b08d3beed54.png)
![image](https://user-images.githubusercontent.com/106132477/183520221-7a819696-6762-45d3-ac4c-4fe2392b4302.png)

As you can see, the station itself is definitely not Meta Station, but rather Lighthouse.

**Comment by ike709** [comment] 2022-08-08 22:36
Pretty sure this is a dupe

**Comment by EmoGarbage404** [comment] 2022-08-08 22:55
this is a dupe of several other issues

**Closed by EmoGarbage404** 2022-08-08 22:55 UTC
