### ISSUE TITLE
Food trash/finisher teleports to player from (0,0) after the food is consumed.

### ISSUE THREAD

**Issue by Ephememory** [space-wizards/space-station-14#3941] opened 2021-05-08 05:03 UTC
## Description

Food trash/finisher teleports to player from (0,0) after the food is consumed.
**Screenshots**

https://user-images.githubusercontent.com/66768086/117527330-c5959c80-af90-11eb-9b44-d238f0ea59ea.mp4

**Additional context**

I sorta know why this is happening but  something changed between when I wrote the food code and now lol.

**Comment by SweptWasTaken** [comment] 2021-05-08 05:07
Sorta clone of #3290

**Comment by SweptWasTaken** [comment] 2021-05-08 05:14
Here's links to the lines of code that spawn the entities [FoodComponent.cs](https://github.com/space-wizards/space-station-14/blob/2c5102b85d626c54a3a5fa40b3245769b213dd34/Content.Server/GameObjects/Components/Nutrition/FoodComponent.cs#L194) and [FoodContainerComponent.cs](https://github.com/space-wizards/space-station-14/blob/2c5102b85d626c54a3a5fa40b3245769b213dd34/Content.Server/GameObjects/Components/Nutrition/FoodContainerComponent.cs#L56). It's not a problem with just food code.

**Comment by SweptWasTaken** [comment] 2021-05-08 05:15
> 
> 
> Isn't it it just the pickup lerping?

You have to be more specific than this.

**Comment by PaulRitter** [comment] 2021-05-08 23:10
i hate this

**Comment by Ephememory** [comment] 2021-05-10 17:28
is there no way to cheaply and sanely disable lerping on an entity either temp or permanently?

**Comment by Acruid** [comment] 2021-05-11 22:55
I cannot reproduce this in the live server, was it fixed?

**Comment by ShadowCommander** [comment] 2021-05-11 23:14
Fixed by #3944

**Closed by ShadowCommander** 2021-05-11 23:14 UTC
Labels: Priority: 1-high
