### ISSUE TITLE
Need a way to set clown/mime/borg preset names

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#28199] opened 2024-05-22 06:43 UTC
## Description
Clowns, mimes, and borgs often have different naming archetypes than your regular charcter. We need a way to be able to set personalized names for your character if you roll one of these roles. 

## Reasons why 
Clowns and mimes have leeway for wacky and funny names that fit their character. At this moment, players are unable to use a different names for clowns and mimes if you round start. Only way to gaurentee you have a funny name is if you make a dedicated character and then only latejoin as a clown/mime.

I dont want to be a clown with my main charcters, or a normal name such as "Micheal Bruizer" 

If i set clown to high and name myself "Wacky Slipper" and then roll janitor, i might be in violation of the naming rules since i did not roll clown.

It would be nice to preset borg names but since borgs have randomized names this is not much as a worry.

**Comment by lzk228** [comment] 2024-05-22 07:31
how i see it for good
- datafield with names dataset in jobprototype
- for every role that has setPreference true and datafield for special names isn't null we add line for that role in character editor

**Comment by UbaserB** [comment] 2024-05-22 08:48
Dupe of #10351

**Closed by UbaserB** 2024-05-22 08:48 UTC
Labels: Status: Untriaged
