### ISSUE TITLE
Mass scanner labels do not respect maximum range

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9802] opened 2022-07-16 16:08 UTC
## Description
Mass scanner labels do not respect maximum range. RIP stealthops.

Introduced by #9685

**Reproduction**
- Drive cargo shuttle far away
- Watch nukie shuttle warp in with cargo's shuttle console

**Screenshots**
![out_of_range](https://user-images.githubusercontent.com/108953437/179362811-74306217-c652-420d-8784-7d9f090283f8.png)

**Additional context**
If not-a-bug, what "Max radar range" refers to? On "no more cargo shuttle getting lost" from PR introducing the issue, what remote pilot console and coordinates are for?

Closely related to issue #9561.

**Comment by metalgearsloth** [comment] 2022-07-17 08:30
Max radar range is how far it zooms out. I think the actual cap for labels is 2km which is intended. This is a dupe of https://github.com/space-wizards/space-station-14/issues/9561 in terms of what needs doing.

**Closed by metalgearsloth** 2022-07-17 08:30 UTC
