### ISSUE TITLE
Please... What the f**king SS14's protocol working ?!?!?!??!

### ISSUE THREAD

**Issue by Lines115** [space-wizards/space-station-14#22086] opened 2023-12-02 14:52 UTC
I trying to write some programs with Space Station 14's (Robust ToolBox's) protocol on python, but NOTHING NOT HELPING ME WITH THIS. (**I trying like a month**)
I readed the official Robust ToolBox Docs on the Robust.Shared/Network.... Nothing...
I trying this with ChatGPT 4... Nothing...
Please, help me with this...
I don't have the nerve to try anymore !!...

**Comment by deltanedas** [comment] 2023-12-02 15:11
pro

**Comment by PJB3005** [comment] 2023-12-02 18:57
Duplicate of https://github.com/space-wizards/RobustToolbox/issues/4657

**Closed by PJB3005** 2023-12-02 18:57 UTC
