### ISSUE TITLE
Wand of instant death does not perform as advertised against things able to survive 300 damage

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9924] opened 2022-07-20 16:17 UTC
## Description
Wand of instant death does not perform as advertised against things able to survive 300 damage. That appears to be things like space dragon (takes 2 shots) or xeno queen (takes 5 shots).

**Reproduction**
- Spawn the wand
- Spawn dubiously balanced mobs
- Click mobs with wand in combat mode

**Comment by HoofedEar** [comment] 2022-07-21 19:32
Is this intended or should this just be upped to 9999? It's easily modified in YAML, but I want to find out if 300 is the intended value

**Comment by EmoGarbage404** [comment] 2022-07-21 19:44
If you just keep upping the number, eventually it's going to just destroy walls and stuff. It should probably have unique behavior to instantly kill a mob.

**Comment by HoofedEar** [comment] 2022-07-21 19:46
> If you just keep upping the number, eventually it's going to just destroy walls and stuff. It should probably have unique behavior to instantly kill a mob.

Agreed, but I'm not sure why #9925 was closed as intended then...

**Comment by Elijahrane** [comment] 2022-07-21 20:31
Make it directly kill a mob bypassing the damage system entirely.

**Comment by moonheart08** [comment] 2022-07-21 20:58
> Is this intended or should this just be upped to 9999? It's easily modified in YAML, but I want to find out if 300 is the intended value

It's intended.

**Closed by moonheart08** 2022-07-21 20:58 UTC
Labels: Priority: 3-Not Required, Difficulty: 1-Easy, Issue: Balance
