### ISSUE TITLE
Remove space dragon as a carp boss from expedition

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#17001] opened 2023-05-31 18:51 UTC
## Description

They can easily overwhelm salvagers with a lot of carps(that are also ghost roles), it's really not balanced for like four people
**Reproduction**

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment] 2023-05-31 19:05
dupe of #16989

**Closed** 2023-06-04 11:06 UTC
