### ISSUE TITLE
RGB plushies will sometimes not shift colors at all and stay black

### ISSUE THREAD

**Issue by deepdarkdepths** [space-wizards/space-station-14#26817] opened 2024-04-08 08:52 UTC
Seems client side, as I've had plushies work just fine on my end but other people see it as pitch black.
![image](https://github.com/space-wizards/space-station-14/assets/155149356/17041bc3-bd3a-4206-b44c-a0acb58514c1)

**Comment by Golinth** [comment] 2024-04-08 19:23
duplicate of #20698

**Closed** 2024-04-09 13:49 UTC
Labels: Status: Untriaged
