### ISSUE TITLE
You can see mods of locked borgs

### ISSUE THREAD

**Issue by Kovlar-ghost** [space-wizards/space-station-14#27987] opened 2024-05-13 19:24 UTC
## Description
When you press E on a borg for a brief moment you can see all the mods inside it potentially giving away any syndicate modules 

**Reproduction**
just press E on any borg

**Additional context**
another note maybe its a feature but you can also see the self destruct mod when a borg has it equipped in its hand

**Comment by deltanedas** [comment] 2024-05-13 19:51
dupe of #27594

**Closed** 2024-05-13 21:39 UTC
Labels: Status: Untriaged
