### ISSUE TITLE
Clicking on a stack of anything with metal rods will forcibly spawn in lattice under your position.

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#10620] opened 2022-08-15 20:48 UTC
## Description
If you hold a stack of something in one hand, and a stack of metal rods in the other, and click on the stack with the metal rods you will force spawn lattice under your position. This causes a WHOLE bunch of issues ranging from a solid lattice welding itself into the floor, to adding a new grid under the station.

**Reproduction**
1. Hold a stack of metal rods
2. Hold a stack of something else in your second hand.
3. Click on the stack with your metal rods.
4. Lattice will be spawned in under your position.

**Screenshots**
![lattice bug1](https://user-images.githubusercontent.com/106507028/184715558-6e7bd6e6-2afd-4153-9788-d7436115b7eb.png)

**Additional context**
Somehow this doesn't use up the metal rods and you can indefinitely spawn in lattice.
Send help.

**Comment by Mervill** [comment] 2022-10-04 23:21
Can't reproduce on 28cd7dc764d9c5deb2d3312aece4b3ae9198e900
Duplicate of #10619

**Closed** 2022-10-04 23:33 UTC
