### ISSUE TITLE
Shuttles occasionally spawn inside the station

### ISSUE THREAD

**Issue by engineer-pearl** [space-wizards/space-station-14#29104] opened 2024-06-16 18:13 UTC
## Description
On round start, it is not unusual for a shuttle to spawn inside the station. The shuttle may have no air or gravity, but block travel through the station or prevent access to vital machinery

**Reproduction**
Can be experienced on Salamander.

**Comment by crazybrain23** [comment] 2024-06-17 11:56
Duplicate of #27667.

**Closed by crazybrain23** 2024-06-17 11:56 UTC
Labels: Status: Untriaged
