### ISSUE TITLE
Items close to walls can sometimes be grabbed or deconstructed through walls.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#5119] opened 2021-11-01 03:10 UTC
## Description

This is an inconsistent bug that I have reproduced on local without any simulated lag. It's 100% consistent for light bulbs and light fixtures, but not for items.

How to reproduce:

- Put on a set of insulated gloves.
- Find a spot where you know there are lights on the other side of a wall. This works for both windows (such as in the below screenshots) and walls (Chemistry is a good example, I've also gotten this to work in Sec and Cargo).
- Spam clicks on the edge of the wall. You will grab the light bulbs from the sockets.
- You can also deconstruct the light fixtures, though this takes a bit of finessing.
- Occasionally, doing this with an empty hand can pick up items through walls.

I've also noticed you can attack things through walls if they're close enough to the wall. As an example, if you grab a melee weapon with decent damage it's entirely possible to destroy the Chem Dispenser/ChemMaster through the wall.

**Screenshots**

![Content Client_X0qsEYmONU](https://user-images.githubusercontent.com/7907891/139616041-27d7d57c-4430-4cb1-8222-d644c11bc2dd.png)

![Content Client_pSD93Orz8b](https://user-images.githubusercontent.com/7907891/139616045-a173837b-d4f6-4c40-a13e-dcf09eb0f3d2.png)

![Content Client_BUDxqOCtko](https://user-images.githubusercontent.com/7907891/139616563-256406e8-f7f3-4dc2-b7cd-96e7dda6a88d.png)

**Additional context**

**Comment by thevinter** [comment] 2021-11-07 21:37
#5089 and #4918 are probably the same problem. We should select one Issue to track

**Comment by mirrorcult** [comment] 2021-11-07 21:38
this one is probably a different issue but those are the same ye

**Comment by thevinter** [comment] 2021-11-07 23:15
Is interacting trough windows with lightbulbs an intended behaviour? It gets fixed with the change in #5089

**Closed** 2022-02-17 02:40 UTC
Labels: Type: Bug, Priority: 2-Before Release, Difficulty: 2-Medium
