### ISSUE TITLE
Inventory closes when opening containers

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#31497] opened 2024-08-26 23:14 UTC
## Description
All kinds of containers constantly break and need to be closed(Toolbox stayed open so game thinks they are open) and opened again to get a chance to properly open them again. When you open different container, old one might not close properly, if you try to open it via verb it will give you option to close it instead.

**Reproduction**
Just open different containers

**Screenshots**
![obraz](https://github.com/user-attachments/assets/adc63efb-590a-431f-bbdf-1268b2fd87df)
![obraz](https://github.com/user-attachments/assets/c913a484-7078-4b93-8744-97afd3024972)

**Comment by Winkarst-cpu** [comment] 2024-08-26 23:18
Duplicate of #31466.

**Closed** 2024-08-26 23:21 UTC
Labels: Status: Untriaged
