### ISSUE TITLE
Grav Anomaly Stops Movement

### ISSUE THREAD

**Issue by Kezu02** [space-wizards/space-station-14#21902] opened 2023-11-26 08:43 UTC
## Description

Happens for both pulses and crit. When pulsing, it temporarily stops movement while it permanently rubberbands you when in close proximity to a crit grav anom. Vaulting over tables and buckling into chairs does not fix it, but getting put in a disposals chute does.

**Comment by 0x6273** [comment] 2023-11-26 12:17
Dupe of #21747

**Closed** 2023-11-26 15:04 UTC
