### ISSUE TITLE
Airlocks don't automically open/stay open when a player is underneath one

### ISSUE THREAD

**Issue by partyaddict** [space-wizards/space-station-14#636] opened 2020-02-08 13:58 UTC
![](https://i.imgur.com/Lk3aVlx.gif)

They just close underneath you, probably should automatically open or stay open until the player moves.

**Comment by PKPenguin321** [comment] 2020-02-08 18:19
This if() check is failing somehow:
https://github.com/space-wizards/space-station-14/blob/32103979ed3ba8d968d3846add43db68a23e32a7/Content.Server/GameObjects/Components/Doors/ServerDoorComponent.cs#L176-L182

**Comment by PJB3005** [comment] 2020-02-08 18:22
It's probably the same bug that's breaking collision checks against people, #637

**Comment by PKPenguin321** [comment] 2020-02-08 18:23
Was gonna say the same, probably caused by https://github.com/space-wizards/space-station-14/pull/625 since it disabled player collision

**Comment by partyaddict** [comment] 2020-02-09 10:25
It's working now but is it intended that it works for items now?

![image](https://user-images.githubusercontent.com/52793290/74100401-6c894f80-4b26-11ea-86aa-2f279d981065.png)

**Comment by AJCM-git** [comment] 2020-05-23 19:04
Duplicate of #970

**Closed by AJCM-git** 2020-05-23 19:04 UTC
Labels: Priority: 3-low, Type: Feature
