### ISSUE TITLE
issue with the new hardsuit toggle helmet thing

### ISSUE THREAD

**Issue by Kromabae** [space-wizards/space-station-14#7774] opened 2022-04-25 15:24 UTC
## Description
Helmet cannot be taken of by the person that has the hardsuit on with the new toggle feature
third party needs to help remove it currently

When attempting to take it of it promts you to first take of the helmet but it is glued to your head so you cant

**Comment by Elijahrane** [comment] 2022-04-25 17:03
Duplicate of https://github.com/space-wizards/space-station-14/issues/7762

**Closed** 2022-04-26 11:18 UTC
