### ISSUE TITLE
emergency shuttle from previous round can end a new round early

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#22637] opened 2023-12-17 06:41 UTC
## Description

shuttle gets launched in the lobby (say, from early end to zombies) and will end the next round early when it arrives
![image](https://github.com/space-wizards/space-station-14/assets/130668733/8d9e05ca-4856-492c-8225-5a8655d39e21)
get these guys an antag token
![20231217173841_1](https://github.com/space-wizards/space-station-14/assets/130668733/e8557c99-2115-44f8-921c-3feac8273e64)

**Comment by UbaserB** [comment] 2023-12-17 06:45
Yea ive experienced this too lol

**Comment by deltanedas** [comment] 2023-12-17 07:46
the poor goober thinking tiders cant be antag:

**Comment by VasilisThePikachu** [comment] 2023-12-17 16:47
Dupe of #18584

**Closed by VasilisThePikachu** 2023-12-17 16:47 UTC
