### ISSUE TITLE
Mac Launcher crashes immediately after opening 

### ISSUE THREAD

**Issue by AeORockin36** [space-wizards/space-station-14#745] opened 2020-02-25 21:02 UTC
The Mac Launcher keeps crashing when opened for some reason, I'll link the crash report below

https://pastebin.com/ewx7XZWH

**Comment by PJB3005** [comment] 2020-02-25 21:13
SIGABRT so means we're gonna need stdout logs. Dangit.

**Comment by AeORockin36** [comment] 2020-02-25 21:31
How would I go about getting stdout logs?

**Comment by PJB3005** [comment] 2020-02-25 21:34
If you've got some technical experience you can run `Space Station 14 Launcher.app/Contents/MacOS/SS14` with a terminal and screenshot what it dumps out.

Either way I think I'm gonna make the launcher logs get dumped to a file so if you can wait a bit I can make a modified version of the client I guess.

**Comment by AeORockin36** [comment] 2020-02-25 22:20
![Screen Shot 2020-02-25 at 6 18 41 PM](https://user-images.githubusercontent.com/45568684/75292856-6b7d4100-57fb-11ea-9966-ac0aeda6e674.png)

Is this what you need? I'm not sure I did it correctly

**Comment by PJB3005** [comment] 2020-02-25 22:25
That's good enough. I double checked your crash log and the issue is that your macOS version is too old. Right now the game needs a minimum of High Sierra (because .NET Core 3 does) and you're still on Sierra.

Not much we can do here, sorry. Maybe .NET 5's integration of Mono would allow us to run on older macOS versions again.

**Comment by PJB3005** [comment] 2020-02-25 22:32
I've updated the downloads page on the website to list that macOS needs at least High Sierra, since I think you're not the first person to have a problem with this.

Otherwise, there's not much we can do to fix this so closing.

**Closed by PJB3005** 2020-02-25 22:32 UTC
