### ISSUE TITLE
do_after needs a refactor for prediction

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#3742] opened 2021-03-29 00:03 UTC

**Comment by metalgearsloth** [comment] 2021-04-28 10:20
Also thought about making it unique based on: user entity, target entity, target component, which might help with prediction + cleanliness.

Also probably combine DoAfterEventArgs with DoAfter as well for simplicity.

**Comment by Visne** [comment] 2021-07-15 21:11
Duplicate of #3088

**Closed** 2021-07-16 14:17 UTC
Labels: Difficulty: 4 - Hard, Priority: 2-medium, Size: 3 - Medium, Type: Refactor
