### ISSUE TITLE
Sometimes the ID card computer won't let you change the job icon

### ISSUE THREAD

**Issue by jessicamaybe** [space-wizards/space-station-14#34019] opened 2024-12-23 04:03 UTC
## Description
When using the drop down menu to change the job title and job icon on a fresh passenger ID, sometimes after selecting a job it will quickly switch back to Passenger in the dropdown label. The job title will still change in the job title field, but the Icon will be stuck on passenger.

**Comment by Tayrtahn** [comment] 2024-12-23 04:59
I think this might be a duplicate of #33738?

**Comment by beck-thompson** [comment] 2024-12-23 20:20
Looks like its the same! Thanks for the report 🫡

**Closed by beck-thompson** 2024-12-23 20:20 UTC
Labels: S: Untriaged
