### ISSUE TITLE
Mirrors on walls cannot be interacted with

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/space-station-14#29489] opened 2024-06-26 12:09 UTC
## Description

Works if you deconstruct the wall, UI opens for a millisecond before closing instantly if inside a wall

**Reproduction**

**Screenshots**

**Additional context**

**Comment by UbaserB** [comment] 2024-06-26 12:11
Dupe of #28172

**Closed by UbaserB** 2024-06-26 12:11 UTC
Labels: Status: Untriaged
