### ISSUE TITLE
Teleporting to other players is broken

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3940] opened 2021-05-08 01:13 UTC
## Description

![image](https://user-images.githubusercontent.com/49448379/117520923-810efe80-af9a-11eb-87e5-7b5e1fe9f9f7.png)

**Comment by PaulRitter** [comment] 2021-05-08 23:12
im just gonna hijack this to complain about the admin teleport window also, look at this:
- no names other than my own
- the fucking thing doesn't scale when i pull the window bigger
![grafik](https://user-images.githubusercontent.com/16618384/117555905-900db380-b063-11eb-8ee8-543899728091.png)

**Comment by AJCM-git** [comment] 2021-11-07 05:26
dupe of #3393

**Closed by AJCM-git** 2021-11-07 05:26 UTC
Labels: Type: Bug, Priority: 2-Before Release, Difficulty: 2-Medium
