### ISSUE TITLE
End Of Round Summary window shows gamemode preset instead of actual gamemode

### ISSUE THREAD

**Issue by baddiePRO** [space-wizards/space-station-14#31721] opened 2024-09-01 15:20 UTC
## Description
on the end of round summary, instead of saying the actual gamemode it says the gamemode preset, which usually means it says "secret" instead of "traitors", "revolutionaries", "survival", etc

**Reproduction**

>finish round
>look at end of round screen
>"gamemode was secret"
>:mistake:

**Comment by UbaserB** [comment] 2024-09-01 15:25
Dupe of #31592

**Closed by UbaserB** 2024-09-01 15:25 UTC
Labels: Status: Untriaged

**Comment by baddiePRO** [comment] 2024-09-01 15:29
![4hJDNJI.png](https://github.com/user-attachments/assets/419fade1-0455-4665-ae58-9190e2ccfee6)
