### ISSUE TITLE
Cant eat or drink anything while the bandana is being worn as a hat

### ISSUE THREAD

**Issue by XxSWAG-MASTER-OVERLORDxX** [space-wizards/space-station-14#27203] opened 2024-04-21 08:22 UTC
As per the title, you cant eat or drink when it is being worn as a hat

1. grab bandana
2. Alt click bandana to make it wearable on hat slot
3. put it on, and be unable to eat or drink

it may have something to do with going from terminal to the main station, i could only get it to work with bandanas i got from terminal and brought to the station.

**Comment by UbaserB** [comment] 2024-04-21 08:24
Duplicate of #27163

**Closed by UbaserB** 2024-04-21 08:24 UTC
Labels: Status: Untriaged
