### ISSUE TITLE
Random graphical glitches while playing board games

### ISSUE THREAD

**Issue by Visne** [space-wizards/space-station-14#10494] opened 2022-08-10 23:25 UTC
## Description

Sometimes weird graphical glitches or unknown objects can be seen inside the board game window.

**Reproduction**

I currently don't know how to reproduce this.

**Screenshot/Video**

Looks like damage overlay:

https://user-images.githubusercontent.com/39844191/184039818-0ddcea43-3563-4316-b55d-a8ff6f265090.mp4

Objects in background (top right):

![image](https://user-images.githubusercontent.com/39844191/184039870-590e10dd-0571-45b9-9daa-bf60f45d7f11.png)

**Comment by EmoGarbage404** [comment] 2022-08-10 23:28
The first one is the damage overlay not working well with multiple viewports. Its known and has been reported before.

The second is an issue with decals drawing across maps. This one is also known about.

**Comment by Visne** [comment] 2022-08-10 23:39
Do they have GitHub issues? If so, this can be closed.

**Comment by EmoGarbage404** [comment] 2022-08-11 02:26
Duplicate of #10010 and #10413.

**Closed by EmoGarbage404** 2022-08-11 02:26 UTC
