### ISSUE TITLE
Item insetion fail bug

### ISSUE THREAD

**Issue by UKNOWH** [space-wizards/space-station-14#7882] opened 2022-04-30 13:32 UTC
## Description

If you tried to insert an item into a container that it cannot be inserted into , it would drop the item to the ground. Where originally it would stay in your hand
**Screenshots**

https://user-images.githubusercontent.com/60119809/166107624-52deb72c-c370-42d7-9709-e428eba2c71d.mov

**Additional context**

**Comment by ElectroJr** [comment] 2022-05-01 00:03
Duplicate of #7864

**Closed by ElectroJr** 2022-05-01 00:03 UTC
