### ISSUE TITLE
Table outline is in the way of things above it 

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/space-station-14#959] opened 2020-05-22 22:27 UTC
For example placing the microwave above a table and selecting the table causes the table to render above the microwave (this happens to all machines, but its more noticeable in the microwave because it should normally be above a table)

**Comment by Clyybber** [comment] 2020-06-04 23:10
Can't reproduce

**Comment by FL-OZ** [comment] 2020-06-04 23:16
I fixed the microwave specifically (in a very hacky way by putting its layer as Items). in #997

**Comment by SweptWasTaken** [comment] 2020-10-02 07:30
Fixed by #2141 , closing.

**Closed by SweptWasTaken** 2020-10-02 07:30 UTC
Labels: Type: Bug
