### ISSUE TITLE
all beacons start with "station-beacon-#######"

### ISSUE THREAD

**Issue by gesaf** [space-wizards/space-station-14#26302] opened 2024-03-21 10:37 UTC
## Description
all the beacons start with "station beacon" and its crowding the map makeing it in some places upreadable, as well as some beacons not working anymore

**Reproduction**
look at any map.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/78671705/4c9c8c66-3686-4a20-93a1-515f723d230b)

**Comment by Tayrtahn** [comment] 2024-03-21 12:01
Duplicate of #24487

But thanks for the additional report!

**Closed** 2024-03-21 12:02 UTC
