### ISSUE TITLE
Players cannot reenter their own brains when they get gibbed

### ISSUE THREAD

**Issue by LordEclipse** [space-wizards/space-station-14#20444] opened 2023-09-23 19:28 UTC
## Description
When players get gibbed, if somebody grabs their brain to make them a cyborg, they cannot enter the cyborg in any way.

**Comment by deltanedas** [comment] 2023-09-23 19:38
dupe of #20425

**Comment by Slava0135** [comment] 2023-09-23 19:41
wow there are multiple close states

**Closed** 2023-09-23 19:40 UTC
