### ISSUE TITLE
Remaining evac time in comms ui has excessive precision displayed.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#30491] opened 2024-07-30 10:18 UTC
## Description
Lots of decimal places in countdown now, see screencap.

**Reproduction**
- Call shuttle
- Check comms console.

**Screenshots**
![image](https://github.com/user-attachments/assets/1601f3d8-97a7-4e04-8510-39786368a3d4)

**Additional context**
NA

**Comment by Brandon-Huu** [comment] 2024-07-30 12:01
Duplicate
https://github.com/space-wizards/space-station-14/issues/30279

**Comment by Tayrtahn** [comment] 2024-07-30 15:22
Duplicate of #30279

**Closed by Tayrtahn** 2024-07-30 15:22 UTC
Labels: Status: Untriaged
