### ISSUE TITLE
Linux Russian layout input bug

### ISSUE THREAD

**Issue by Rorkh** [space-wizards/space-station-14#17820] opened 2023-07-04 15:58 UTC
## Description
When you connect to game with Russian layout selected, backspace has no effect in any of input boxes (regardless of layout)
I'm sure it's Linux only bug as I encountered it before in another game (but it was related to CEF, never fixed in game) only on Linux (as other people)

**Reproduction**

1. Switch to Russian layout in Space Station 14 Launcher
2. Connect to any server
3. Try to delete something in input boxes

**Additional context**
[Report about something similar in SDL repo (for reasons unknown closed)](https://github.com/libsdl-org/SDL/issues/4187)

I use Arch btw
![image](https://github.com/space-wizards/space-station-14/assets/78957156/8f92c667-9a1a-4790-bb2f-538ae7dbeffb)

**Comment by lzk228** [comment] 2023-07-04 16:14
not only russian, any not-englush layout when launching client, and boom, you need to restart

**Comment by PJB3005** [comment] 2023-07-04 17:36
Duplicate of #3486

**Closed by PJB3005** 2023-07-04 17:36 UTC
