### ISSUE TITLE
Chems don't metabolize properly.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#4737] opened 2021-10-02 03:02 UTC
How to reproduce:

- Punch yourself into a low HP state.
- Go to Chemistry and mix up a bunch of bicard.
- Drink it all. You'll eventually get the "You've had enough" message.
- Wait several minutes.
- Your health will still be the same even after the bicard should have started metabolizing.

Interestingly, this also applies to water and other drinks, but not to nutriment.

**Comment by ElectroJr** [comment] 2021-10-02 03:14
I don't know about water & other drinks, but bicaridine is still being metabolized properly.

The issue is just a damage-unit rounding error. It heals 2 brute group damage, which is divided over three damage types (blunt, slash & piercing). Currently this means it just heals 1 slash & 1 piercing. It should be fixed whenever non-integer damage units are added in.

**Closed** 2021-11-03 23:48 UTC
Labels: Type: Bug, Priority: 1-Urgent, Difficulty: 2-Medium, Bug: Needs Replicating
