### ISSUE TITLE
Container Items/Lockers are gunked

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#719] opened 2020-02-17 21:58 UTC
- If an item is placed in a locker the locker can no longer be pushed
- Sometimes when opening/closing a lock you can no longer pickup any items inside the locker
- Toolboxes can get in a weird state that cannot be picked up, instead they just open their inventory on click

**Comment by PrPleGoo** [comment] 2020-03-05 18:25
I'm going to take a look at this

**Comment by PrPleGoo** [comment] 2020-03-05 18:38
Unable to reproduce:

- Sometimes when opening/closing a lock you can no longer pickup any items inside the locker
- Toolboxes can get in a weird state that cannot be picked up, instead they just open their inventory on click

Please provide more details

**Comment by SweptWasTaken** [comment] 2020-03-05 18:40
This might have been fixed by this

https://github.com/space-wizards/RobustToolbox/pull/1004

**Comment by PrPleGoo** [comment] 2020-03-05 18:40
I will look at fixing this then:
- If an item is placed in a locker the locker can no longer be pushed

**Closed** 2020-04-17 19:00 UTC
Labels: Type: Bug
