### ISSUE TITLE
Character preview in lobby doesn't show unless you click save

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#15649] opened 2023-04-22 08:55 UTC
## Description

**Reproduction**

![image](https://user-images.githubusercontent.com/43253663/233774153-e2cebde0-f4c8-4937-a86d-41d7b657155c.png)
after clicking save
![image](https://user-images.githubusercontent.com/43253663/233774165-17320c88-9c91-4c1f-b4d3-d34eaa2c37e2.png)

**Screenshots**

**Additional context**

**Comment by deltanedas** [comment] 2023-04-22 20:55
dupe of #13067

**Comment by metalgearsloth** [comment] 2023-05-18 01:17
Fixed in https://github.com/space-wizards/RobustToolbox/pull/4065

**Closed by metalgearsloth** 2023-05-18 01:17 UTC
