### ISSUE TITLE
Hand held light item status does not update when power cells are charged.

### ISSUE THREAD

**Issue by xRiriq** [space-wizards/space-station-14#5339] opened 2021-11-14 19:45 UTC
## Description

It appears to be some sort of client-side/server-side synchronization issue. I thought it was the wall recharger since I hadn't used one before Packed came out, but something is screwy with how the client gets updated from the server state.

Steps to reproduce:
1. spawn/vend a seclight
2. use it for a bit to have the battery go down below two ticks
3. throw it in a charger, it'll flash green as it charges
4. wait for it to flash yellow indicating 'done'
5. pick it up again and put it in hand, and it likely will show 3 ticks or whatever the charge was when you put it in the charger
6. turn the flashlight on/interact with it
7. charge now is full

**Screenshots**

![image](https://user-images.githubusercontent.com/94037592/141695918-7f268e56-f776-4071-9dcd-d0675449cbe4.png)
![image](https://user-images.githubusercontent.com/94037592/141695923-7045963f-8fe4-4c7f-9cc6-1ed20bd82c0d.png)
![image](https://user-images.githubusercontent.com/94037592/141696013-50e03512-e58e-47ba-b9fa-dc03986764c9.png)

**Additional context**

**Comment by ElectroJr** [comment] 2022-02-15 12:21
Duplicate of #3815

**Closed by ElectroJr** 2022-02-15 12:21 UTC
