### ISSUE TITLE
Meteor swarm abuse

### ISSUE THREAD

**Issue by Futuristic-OK** [space-wizards/space-station-14#29093] opened 2024-06-16 12:45 UTC
## Description

 Meteor swarm can be defeated with any sized puddle or **_flying_** items. Banana peels throw or soap that flew out of the destroyed cabinet from the maints

**Comment by beck-thompson** [comment] 2024-12-20 06:52
Dupe of #29069! Thanks for the report 🫡

**Closed by beck-thompson** 2024-12-20 06:52 UTC
Labels: S: Untriaged
