### ISSUE TITLE
livestock crates should not be airtight

### ISSUE THREAD

**Issue by Stealthbomber16** [space-wizards/space-station-14#14717] opened 2023-03-17 03:27 UTC
## Description
animals spawn in airtight wooden crates that kill them if they aren't let out

**Reproduction**
spawn a cow crate
wait for the cow to run out of air
enjoy free miasma

**Additional context**
this is fucking aids

**Comment by ShadowCommander** [comment] 2023-03-17 04:16
They're supposed to have internal atmos to allow transportation in space. Or at least that's what the sprite looks like, since it has an oxygen canister on the side. Not sure if it was ever implemented.

**Comment by mirrorcult** [comment] 2023-03-17 04:18
this is dupe of some issue. they -should- be airtight they just need higher air capacity

**Closed by mirrorcult** 2023-03-17 04:18 UTC
