### ISSUE TITLE
Short-sighted people can't be converted into revs

### ISSUE THREAD

**Issue by PyteOakOal** [space-wizards/space-station-14#28207] opened 2024-05-22 21:08 UTC
## Description
When playing on a Rev round, short-sighted characters are unable to be flashed or converted by any of the HeadRevs. This still applies if the person is not wearing prescription glasses.

**Reproduction**
Hit a short-sighted character with a flash and nothing will happen to them. They won't even get stunned.

**Additional context**
I believe this could be happening due to the similarities they have to blind characters (the blurry vision that we get when playing as them), therefore the code interprets it as if the person is fully blind.

**Comment by B1essedknight** [comment] 2024-05-22 22:39
dupe of this im pretty sure #27992

**Comment by slarticodefast** [comment] 2024-05-22 22:42
Yeah, this is the same issue as #27992.
My PR fixes this #27369

**Closed** 2024-05-22 23:47 UTC
Labels: Status: Untriaged
