### ISSUE TITLE
WT550 missing bolt/rack action

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#20105] opened 2023-09-13 09:40 UTC
## Description
The WT550 is missing the rack and bolt action in the context menu. This makes it hard to reload with some peoples control styles.
It can only be chambered/bolted with pushing the 'activate item in hand'(default Z) key while holding it.
Other guns such as Lecter and MK57 have these which allow chambering the round after a reload on the ground or selectively in your hands or bag/container.

**Reproduction**
Eject chambered round from WT550 try and use 'activate item in world key'(Default E)

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/9f65ee11-eba9-461f-a2a3-ab9f4ecbae14)
![image](https://github.com/space-wizards/space-station-14/assets/47093363/23b3fed1-4be9-4812-a40a-fd5985a29016)

**Additional context**
Still works and is effective, just not very consistent with other guns.

**Comment by VasilisThePikachu** [comment] 2023-09-13 11:26
Dupe of #19891

**Closed** 2023-09-13 12:18 UTC
