### ISSUE TITLE
Sound no longer plays when you take something out of a storage window

### ISSUE THREAD

**Issue by DummeHytteOst** [space-wizards/space-station-14#20038] opened 2023-09-11 17:01 UTC
sound no longer plays when you take stuff out of backpacks, belts, survival boxes etc. 

also dosen't play sound when using quick binds, shift+e and shift+b, both when taking and inserting

**Comment by deltanedas** [comment] 2023-09-11 17:07
dupe of https://github.com/space-wizards/RobustToolbox/issues/4371

**Comment by deltanedas** [comment] 2023-09-11 17:07
dupe of #20034

**Closed** 2023-09-11 18:32 UTC
