### ISSUE TITLE
Large volumes of liquid in puddle form seemingly never decay.

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#5167] opened 2021-11-05 01:08 UTC
How to replicate:

- Fill a bucket with water, or welder fuel if you're feeling particularly sadistic.
- Spill the bucket in a high-traffic area.
- Watch as the entire 40+ minute round goes by without the puddles decaying.
- Steal one of the janitor's signs, put it down, then sit back and laugh.

**Screenshots**

![image](https://user-images.githubusercontent.com/7907891/140441174-ddc95166-28aa-49e4-90cd-c351261e53fd.png)

![image](https://user-images.githubusercontent.com/7907891/140441243-b8c60360-6685-4882-838f-29b91188fbd3.png)

![image](https://user-images.githubusercontent.com/7907891/140441299-dcc9eccd-5cce-4c0e-ae2f-66800455ab1d.png)

![image](https://user-images.githubusercontent.com/7907891/140441439-2fb9dbec-0a11-482a-b561-e11ced161dae.png)

**Comment by metalgearsloth** [comment] 2021-11-05 01:23
FWIW evaporation has a minimum threshold (where anything below won't evaporate) and a maximum threshold (where anything above won't evaporate).

**Comment by Ygg01** [comment] 2021-11-06 01:08
Upper threshold was a mistake.

**Comment by ElectroJr** [comment] 2021-11-06 01:33
In the case of water I thought that in the puddle overflow volume would prevent the puddle from ever going over the evaporation threshold. But seemingly some of the puddles just end up with more than `OverflowVolume` reagent. 

Is that a bug or intentional? If not, should puddles just cap their volume at `OverflowVolume` or periodically attempt to re-overflow in case neighbours have evaporated?

**Comment by Ygg01** [comment] 2021-11-06 02:11
Not sure. What happens if room is 1x1 and water canisters is destroyed? Logically that tile would become a water field without oxygen and prohibiting movements.

**Comment by Willhelm53** [comment] 2022-01-24 13:26
I'll have a look at this one, but I need to know intended behaviour first. I like the re-overflow attempt idea - this alone might solve it. If OverflowVolume and EvaporationUpperLimit are similar enough, then puddles should always either evaporate or overflow unless they are confined.

**Comment by Ygg01** [comment] 2022-01-24 17:36
@Willhelm53 Check with Vera. From my understanding/recall it's like this:
- If volume > 20u, then overflow
- evaporation has upper and lower limit. 
- By default the evaporation lower limit is 0u i.e. always evaporate, unless some puddle that sticks around like tomato.
- Upper evaporation limit was set to Puddle limit to give janitors something to work on i.e. balance reasons.
-  Nothing prevents systems from setting this value to a random value.

**Comment by Willhelm53** [comment] 2022-01-24 17:43
@Zumorica do you have any changes based on the comment @Ygg01 just made? No rush. Thanks Ygg for these details!

**Comment by Willhelm53** [comment] 2022-02-09 07:00
I do still want to fix this issue, but I'm waiting for the overflow algorithm change in #6280 to be merged.

**Comment by mirrorcult** [comment] 2022-06-30 18:21
this was changed i believe

**Closed by mirrorcult** 2022-06-30 18:21 UTC
