### ISSUE TITLE
Chat filter

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#23244] opened 2023-12-30 22:23 UTC
## Description
The admins want it
Configurable by the admins, should save to the database, should ideally support pattern matching (regex, as long as the regex doesn't take 3 years to compute)

@Chief-Engineer

**Comment by ike709** [comment] 2023-12-30 22:28
It's definitely better to have separate filters for in-character and out-of-character channels so RP servers can filter out netspeak in IC. Anything in the OOC filter can just implicitly be included in the IC filter.

**Comment by Simyon264** [comment] 2023-12-30 22:53
How would the chat filter be configured?

**Comment by Hmeister-fake** [comment] 2023-12-30 23:00
There should be a blacklist on certain words high ranking admins can change universally for wizden, just by simply writing the word. Like for example if theres an issue with speciesm, an admin can just add "Ligger" to the Blacklist, and people who say it simply say #### instead and admins get a notice on who said it, like with explosives. Simple as that

**Comment by ShadowCommander** [comment] 2023-12-30 23:05
Duplicate of https://github.com/space-wizards/space-station-14/issues/17313

**Closed** 2023-12-31 00:01 UTC
Labels: Priority: 1-Urgent, Issue: Feature Request
