### ISSUE TITLE
Admins can no longer talk in dead chat while in a body, nor can aghosts talk in LOOC

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#28827] opened 2024-06-10 17:49 UTC
## Description
While I am not sure if this is intentional (changelog appears to not mention it) it is extremely annoying, as the server allows (if not requires) admins to be both readmin'd and as a character. Admins are unable to talk in dead chat when they are in a body, and ghosts (including aghosts) are not able to talk in LOOC anymore, despite in both cases the option to speak in the restricted channel appearing.

**Reproduction**
1. Spawn in as a character in a server that you are an admin in
2. Try to talk to someone in dead chat
3. Cry
4. Aghost
5. Try to talk to someone in LOOC
6. Cry more

**Screenshots**
![20240610124753_1](https://github.com/space-wizards/space-station-14/assets/104110869/6ac7c147-aadb-4a8d-8827-2964cb8d35fb)

![20240610124823_1](https://github.com/space-wizards/space-station-14/assets/104110869/14560d46-2d2d-4d61-b1e6-4be2ee12716a)

**Additional context**
I'm inclined to believe this is a bug, since I'd imagine the selection of the channels would also be removed.

**Comment by bruhmogus** [comment] 2024-06-10 17:53
someone please merge this with the one created literally three minutes before mine

**Comment by Tayrtahn** [comment] 2024-06-10 18:19
Duplicate of #28826.

**Closed by Tayrtahn** 2024-06-10 18:19 UTC
Labels: Status: Untriaged
