### ISSUE TITLE
help autocomplete crashes

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#8250] opened 2022-05-18 04:14 UTC
Already pinged pjb on it but in case anyone else asks.

**Comment by ElectroJr** [comment] 2022-06-08 18:09
Seems to be fixed? Or was there more to reproducing it than just looking at help completions?

**Comment by Peptide90** [comment] 2022-06-08 18:21
> Seems to be fixed? Or was there more to reproducing it than just looking at help completions?

Yeah going to close this, I recall it happening on master but was fixed on the master after. Someone can reopen if still an issue.

**Closed by Peptide90** 2022-06-08 18:21 UTC
Labels: Issue: Bug, Priority: 1-Urgent, Difficulty: 1-Easy
