### ISSUE TITLE
Clown can't fall when in crit or dead

### ISSUE THREAD

**Issue by Winkarst-cpu** [space-wizards/space-station-14#31352] opened 2024-08-23 09:50 UTC
## Description
Title.

**Reproduction**
Be in crit or dead as a clown.

**Screenshots**
![изображение](https://github.com/user-attachments/assets/8d111439-7861-4c7f-b609-3062b5adf8c1)

**Additional context**

**Comment by lzk228** [comment] 2024-08-23 10:06
i am pretty sure it's a dupe issue

**Comment by UbaserB** [comment] 2024-08-23 10:08
Dupe of #26977

**Closed by UbaserB** 2024-08-23 10:08 UTC
Labels: Status: Untriaged

**Comment by Winkarst-cpu** [comment] 2024-08-23 10:11
> Dupe of #26977

Oh, someone needs to set labels to it...
