### ISSUE TITLE
Something broke piping and wires

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9584] opened 2022-07-10 00:53 UTC
## Description

Following was observed during lengthy sandbox round on Wizard's Den Spider server (could have been Miros, but pretty sure it was Spider) at 30 June 2022, first screenshot taken at 07:09 UTC.

At some point, probably after dual port vent removal, all newly created atmos devices started getting funky "remains" of pipes on sprite on all 4 sides. They also seemingly stopped functioning.

Quite possibly the same bug broke wiring, with newly placed wires forming dots.

**Reproduction**
No idea! Logdive perhaps?

**Screenshots**
![pipe_remains_bug](https://user-images.githubusercontent.com/108953437/178127224-0ea2c1f5-2fc7-4f41-85af-38fbf14ca2df.png)
![bugged_cables_too](https://user-images.githubusercontent.com/108953437/178127239-98e0dd51-ddfe-446b-ab50-ea233e125385.png)

**Comment by metalgearsloth** [comment] 2022-07-10 10:32
Until someone provides steps to repro or contacts an admin who VVs it during the round it's unlikely to get fixed anytime soon. The visual aspect may be related to https://github.com/space-wizards/RobustToolbox/pull/2986 but would need an admin to confirm ingame.

**Comment by ElectroJr** [comment] 2022-07-10 18:07
Duplicate of #9318.

**Closed by ElectroJr** 2022-07-10 18:07 UTC
