### ISSUE TITLE
Pulse rifle projectiles collide with crit characters

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#28494] opened 2024-06-02 00:46 UTC
## Description
The projectiles of the pulse rifle will still collide with the bodies of people who are critical, even when not aiming at them.

**Reproduction**
Step 1. Crit someone
Step 2. Fire past them with a pulse rifle

**Screenshots**
![20240601194629_1](https://github.com/space-wizards/space-station-14/assets/104110869/a881139d-052f-490b-8d8f-93507a166694)

**Additional context**
None

**Comment by Cojoke-dot** [comment] 2024-06-02 21:34
As of current the system that lets bullets pass over people only functions for projectiles

**Comment by B1essedknight** [comment] 2024-06-03 14:13
Considering that it applies to lasers too I think this is a dupe of this one #27988

Then again if you have a pulse rifle you likely are going to be killing everything in your path.

**Closed** 2024-06-14 02:04 UTC
Labels: Status: Untriaged
