### ISSUE TITLE
[BUG]Lava planet texture bug

### ISSUE THREAD

**Issue by noverd** [space-wizards/space-station-14#16314] opened 2023-05-10 16:59 UTC
## Description

All information in the image

**Reproduction**

just load any grid onto a planet with Lava and fly over the lava

**Screenshots**

![bruh](https://media.discordapp.net/attachments/1104269385130053662/1105895679202709625/image.png)

**Comment by deltanedas** [comment] 2023-05-10 18:53
dupe of #15957

**Closed** 2023-05-11 02:11 UTC
