### ISSUE TITLE
Emergency pens can be used as budget hypo

### ISSUE THREAD

**Issue by SphiraI** [space-wizards/space-station-14#26597] opened 2024-03-31 05:31 UTC
## Description

Emergency pens are supposed to be inject only, but you can use the swap modes verb to bypass it and make it draw/inject.

**Reproduction**

- Get a epi pen
- Use it and inject something
- Take the now empty/used pen, and right click it
- Use the "Toggle Container Draw" verb
- Budget Hypo time

**Comment by Tayrtahn** [comment] 2024-04-02 01:08
Fixed by #26595

**Closed by Tayrtahn** 2024-04-02 01:08 UTC
Labels: Issue: Bug, Priority: 2-Before Release

**Comment by nikthechampiongr** [comment] 2024-04-02 17:58
I can't reproduce this.
