### ISSUE TITLE
pAI's can take microbombs

### ISSUE THREAD

**Issue by JoeHammad1844** [space-wizards/space-station-14#20677] opened 2023-10-02 10:31 UTC
## Description

i was a syndicate pAI and my owner gave me a microbomb, turning me into a sentient grenade. a sentient grenade actually isnt a bad idea but could be implemented better, please don't fix this until a sentient grenade item is properly implemented
**Reproduction**

inject pAI with microbomb

**Comment by deltanedas** [comment] 2023-10-02 10:43
dupe of #16900 and the dupe of it

**Comment by GoodWheatley** [comment] 2023-10-02 11:11
Dupe

**Closed by GoodWheatley** 2023-10-02 11:11 UTC
