### ISSUE TITLE
All the jugs in the chemvend are unlabelled

### ISSUE THREAD

**Issue by Madformoose** [space-wizards/space-station-14#29234] opened 2024-06-19 23:09 UTC
## Description
All the jugs in the chemvend are unlabelled, despite what the jug actually has. It also shows just an empty jug as opposed to one containing a chem

**Reproduction**
Load onto the game. Open a chemvend. Observe that all the jugs appear as only "Jug" and are not filled. Cry. Make an issue report on github.

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/148000477/12168db1-e42d-4ad4-894a-d1f456bc1c7b)

**Additional context**
I don't think that pull request #29178 worked...

**Comment by engineer-pearl** [comment] 2024-06-19 23:11
The PR is still open. It hasn't been merged!

**Comment by Tayrtahn** [comment] 2024-06-19 23:19
Duplicate of #29140

**Closed by Tayrtahn** 2024-06-19 23:19 UTC
Labels: Status: Untriaged
