### ISSUE TITLE
Roller beds can't be picked up; players can't unbuckle themselves via click

### ISSUE THREAD

**Issue by thebadman4662** [space-wizards/space-station-14#29282] opened 2024-06-21 03:43 UTC
## Description
Not sure if its Origin roller beds being cursed but ALL rollerbeds were not possible to get picked up by anyone on the station, I also noticed I am not able to unbuckle myself by clicking on myself, had to use unbuckle icon on right side.

**Screenshots**
![obraz](https://github.com/space-wizards/space-station-14/assets/152504929/2ac1e6c8-f206-4e42-bd59-dd32c7106952)

**Comment by MjrLandWhale** [comment] 2024-06-21 04:15
You _technically_ can still unbuckle yourself, but you need to click the entity you are buckled to. Agreed though, the current behavior is wrong. Especially the rollerbeds.

Likely caused by #29031

@ElectroJr any ideas?

**Comment by thebadman4662** [comment] 2024-06-21 04:22
Pretty sure I clicked both myself and bed. Same with self and rollerbed.

**Comment by MjrLandWhale** [comment] 2024-06-21 04:22
Additional issue: Attempting to unbuckle a buckled entity hugs them instead.... unless you ctrl+click them which tracks since it causes you to pull the entity.

**Comment by MjrLandWhale** [comment] 2024-06-21 04:56
Additional additional issue: Entities strapped to beds in motion (FTL for example) causes the entity to rapidly move _visually_ between standing & laying. Likely related

**Comment by thebadman4662** [comment] 2024-06-21 04:57
Ah noticed some patients in medbay being like that... But station was not in motion I think?

**Comment by MjrLandWhale** [comment] 2024-06-21 05:29
> Ah noticed some patients in medbay being like that... But station was not in motion I think?

Oh I had only seen it on the evac shuttle. I might need to dig into that a bit more tomorrow then

**Comment by thebadman4662** [comment] 2024-06-21 05:36
Some folks fine, some not.

https://media.discordapp.net/attachments/675078881425752124/1253578904275521607/SS14.Loader_5D8FSEWg3D.gif?ex=66765dd5&is=66750c55&hm=2d0f6c3e24b6d526af71f87c89f59c0bb936d1a3cbf7188c61956f3df8abb038&=

**Comment by thebadman4662** [comment] 2024-06-21 07:10
Non-crits are also seemingly random.

**Comment by ElectroJr** [comment] 2024-06-21 07:51
For the unbuckling by clicking thing, I know there were some interaction priority issues with the hugging code, but I thought I fixed those, will have a look

**Comment by MilenVolf** [comment] 2024-06-25 11:02
Closed by #29293

**Closed** 2024-06-25 12:10 UTC
Labels: Status: Untriaged
