### ISSUE TITLE
You can jam out in a chair, even when you are dead

### ISSUE THREAD

**Issue by OctoRocket** [space-wizards/space-station-14#16936] opened 2023-05-29 17:03 UTC
## Description

Possibly one of the best bugs of all time, it is as the title says. If you are dead and in a chair, you can still spin around by clicking.

**Reproduction**

Sit in chair, die.

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/88291550/c6e02de8-5da7-46a3-aefb-12c7ec9292e6

**Comment by UbaserB** [comment] 2023-12-30 07:51
Dupe of #8873

**Comment by Ilya246** [comment] 2023-12-30 08:08
the spinning dead

**Closed** 2023-12-30 17:34 UTC
