### ISSUE TITLE
Add the ability to re-open Round End Summary window

### ISSUE THREAD

**Issue by LordCarve** [space-wizards/space-station-14#22967] opened 2023-12-25 16:35 UTC
## Description

Small QoL improvement: Add the ability to re-open Round End Summary window after closing it. This is a frequently asked for feature in OOC chat after a round ends.

**Reproduction**

1. Round ends - Round End Summary window opens
2. Close it
3. Currently there is no way to re-open it

**Additional context**

Even something as simple as a console command `/roundsummary` would suffice initially. Ultimately we probably want UI for this.

It appears there is a PR for it in the works, referencing: #22905

**Comment by BYONDFuckery** [comment] 2023-12-25 16:51
Based and summarypilled. +1. :+1:

**Comment by VasilisThePikachu** [comment] 2024-02-08 15:38
Dupe of #7567

**Closed by VasilisThePikachu** 2024-02-08 15:38 UTC
