### ISSUE TITLE
Radios Broken

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#11763] opened 2022-10-08 08:56 UTC
this happened as of commit 548cee77e22fd52823df8929d4beab3ff660641c 
radios brokey no worky, this error was reporpted by carbonhell on lizard after this publish 
nukie radios seem to work same publish,
![image](https://user-images.githubusercontent.com/99158783/194699086-3a4c562d-7fcb-46ff-8cc8-c6ac7b9feab2.png)

**Comment by Carbonhell** [comment] 2022-10-08 09:09
Other useful error, this is actually the first error that showed up for me at roundstart on my initial attempt to use the radio:
![image](https://user-images.githubusercontent.com/11891037/194699741-37d86a12-196a-4ce4-9fc8-9e9553008bde.png)

**Comment by PaulRitter** [comment] 2022-10-08 10:37
![grafik](https://user-images.githubusercontent.com/16618384/194703306-422ed208-d42c-4fac-ad26-7462f70e82cf.png)
i tried to repro this on latest master but to no avail

**Comment by Carbonhell** [comment] 2022-10-08 11:11
> ![grafik](https://user-images.githubusercontent.com/16618384/194703306-422ed208-d42c-4fac-ad26-7462f70e82cf.png) i tried to repro this on latest master but to no avail

I tried running a local server multiple times on latest master but it cannot be reproduced, it's happening only on live. Also I just noticed that, very rarely, some messages manage to pass. Sometimes they don't, and when this happens the 2 errors posted above can either happen or not. The TransformComponent error seems to be the most common one, and the entity id seems to be the same between rounds. An admin tried to VV this entity id but it seems to not exist (which would explain why it has no TransformComponent, since well, it doesn't exist)

**Comment by Cheackraze** [comment] 2022-10-08 13:27
![chaterror](https://user-images.githubusercontent.com/71046427/194709938-4a1ebdb8-cb98-475c-8c5a-6fc13bd5bb73.png)
here is one i got, not sure if this is related

**Comment by metalgearsloth** [comment] 2022-10-09 11:47
Probably fixed in https://github.com/space-wizards/space-station-14/pull/11792

**Comment by Partmedia** [comment] 2022-10-10 05:14
Per the Discord discussion, it doesn't look like the issue was fixed. Reproduced as far back as a210373972a with corresponding submodule.

**Comment by metalgearsloth** [comment] 2022-10-10 05:35
> Per the Discord discussion, it doesn't look like the issue was fixed. Reproduced as far back as [a210373](https://github.com/space-wizards/space-station-14/commit/a210373972abdaf657beb92ebe9b383a28454eb5) with corresponding submodule.

Which engine version?

**Comment by Partmedia** [comment] 2022-10-10 06:20
> Which engine version?

According to Git, that revision uses 0.50.2.0.

**Comment by metalgearsloth** [comment] 2022-10-10 06:36
that was after the relevant reverted pr

**Comment by mirrorcult** [comment] 2022-10-13 01:47
this should be fixed

**Closed by mirrorcult** 2022-10-13 01:47 UTC
