### ISSUE TITLE
Borg batteries permanently break upon EMP

### ISSUE THREAD

**Issue by MissKay1994** [space-wizards/space-station-14#26221] opened 2024-03-18 02:36 UTC
Upon being hit with an EMP, borg batteries are for the rest of the round unable to charge, or if replaced become infinite power. The steps to reproduce are very simple and easy to reproduce. Just EMP a borg and replace the battery and it gains unlimited battery life. It will indicate a random battery percentage on the HUD, and the examine GUI will say 100%, but it never goes down in power

**Comment by MissKay1994** [comment] 2024-03-18 04:11
Additional issue I have found. Draining your battery to 0% causes it to be permanently depleted until the battery is reinstalled into the borg

**Comment by osjarw** [comment] 2024-04-02 00:45
I can't reproduce this on the current master branch, my guess is that this has been fixed.
#26230 sounds like it could have fixed this, though my testing on the commits before that PR just crash the server upon trying to recharge.

**Comment by Tayrtahn** [comment] 2024-04-02 01:12
That probably did fix it. If your testing was done on a dev build, the error would've caused a crash; release builds generally avoid crashing and just log errors.

**Comment by Tayrtahn** [comment] 2024-04-02 01:13
Closing this; but keep an eye out and please submit a report if it happens again.

**Closed by Tayrtahn** 2024-04-02 01:13 UTC
