### ISSUE TITLE
butchering/gibbing dragons deletes the eaten

### ISSUE THREAD

**Issue by MACMAN2003** [space-wizards/space-station-14#26616] opened 2024-03-31 19:25 UTC
## Description

if you butcher or gib a dragon it doesn't spawn the corpses of the people it ate
**Reproduction**

butcher/gib a dragon that ate a urist
**Screenshots**

**Additional context**

it happened on salamander round 50113

**Comment by Tayrtahn** [comment] 2024-03-31 20:28
Duplicate of #20405

**Closed** 2024-03-31 20:28 UTC
Labels: Status: Untriaged
