### ISSUE TITLE
Chat keeps unfocusing while writing

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#898] opened 2020-05-07 21:19 UTC
And it's quite annoying.

**Comment by PJB3005** [comment] 2020-05-07 21:19
This is because I made `ActivateItemInWorld` `CanFocus`

**Comment by henry2327** [comment] 2020-05-08 14:19
hola me podria ayudar

**Comment by SweptWasTaken** [comment] 2020-05-11 05:48
Can't reproduce. Is this fixed?

**Comment by ShadowCommander** [comment] 2020-05-11 05:54
I think it was fixed by commit: 6ff691c

**Closed by ShadowCommander** 2020-05-11 05:54 UTC
