### ISSUE TITLE
Ghost-following someone using a chameleon projector sends you to (null?)space when they use it.

### ISSUE THREAD

**Issue by Mith-randalf** [space-wizards/space-station-14#28382] opened 2024-05-29 14:15 UTC
## Description
Seems a persons body gets stored somewhere; ghosts go with the body and stay there until the person un-disguises where they come abck.

**Reproduction**

Follow someone with a chameleon projector
Have them use it
Space adventure

**Screenshots**

**Additional context**

**Comment by Mith-randalf** [comment] 2024-05-29 14:17
Also; they show at catatonic. I guess the projector works by possessing a copy of the item, I guess ghosts should be passed to that entity?

**Comment by deltanedas** [comment] 2024-05-29 14:57
wont matter when it doesnt use polymorph

**Comment by slarticodefast** [comment] 2024-05-31 16:04
This is still a problem with polymorph in general. For example, the same thing happens when you follow someone being turned into a lizard from too much weh juice.

**Comment by beck-thompson** [comment] 2024-12-15 23:12
Probably fixed by: #33878 and is a duplicate of #28778. Good report though!

**Closed by beck-thompson** 2024-12-15 23:12 UTC
Labels: S: Untriaged
