### ISSUE TITLE
Incediary magazines cause bugs when bolted

### ISSUE THREAD

**Issue by SpaceyLady** [space-wizards/space-station-14#23895] opened 2024-01-10 22:29 UTC
When bolting a gun with a magazine filled with incendiary round it completely lags your game and turns everything black.

Repro steps:
Spawn a drozd (or any gun)
Load magazine with incendiary round
Bolt the gun
Bug appears

It appears to only be resolved by relogging.

**Comment by GoodWheatley** [comment] 2024-01-11 14:22
Dupe of #23878

**Closed by GoodWheatley** 2024-01-11 14:22 UTC
