### ISSUE TITLE
Medical beds being craftable is stupid

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#17946] opened 2023-07-10 23:16 UTC
it effectively lets you bypass healing as a game mechanic make them uncraftable, maybe also nerf them

**Comment by deltanedas** [comment] 2023-07-11 00:03
why not make them a machine since magic healing vs nanobots or some shit

**Comment by Emisse** [comment] 2023-07-11 00:04
no they just shouldnt be craftable its power gamey as fuck

**Comment by deltanedas** [comment] 2023-07-11 00:05
so instead of salv having 5 medical beds in the shittle they hoard meds instead

**Comment by Emisse** [comment] 2023-07-11 00:06
that would unironically be better

**Comment by EmoGarbage404** [comment] 2023-07-11 00:06
better than "lay on this bed and heal for free"

**Comment by Aisu9** [comment] 2023-07-11 00:09
would setting a healing cap be the best course of action? what if medbay get bombed and lose every medical beds?

**Comment by Emisse** [comment] 2023-07-11 00:12
then the medical beds are gone? i dont see the big deal

**Comment by Aisu9** [comment] 2023-07-11 00:14
so only for the sake of nerfing salvage you nerf the overall availability? they can find medical bed on magnet chunks (i know it can be removed) is duratread purchasable via cargo?

**Comment by Emisse** [comment] 2023-07-11 00:17
it being available doesnt matter, they are boring and reduce gameplay interaction

**Comment by Aisu9** [comment] 2023-07-11 00:19
so the basic beds should go too? they also heal and by rule of a+ b also reduce gameplay interaction

**Comment by Emisse** [comment] 2023-07-11 00:20
we can just remove the function from regular beds im not saying delete all beds

**Comment by EmoGarbage404** [comment] 2023-07-11 00:21
> by rule of a+ b 

genuinely curious what this means.

the issue is having powerful healing tools able to be centralized by salvage ( a job that normally is able to acquire an excess of any given material)

**Comment by Aisu9** [comment] 2023-07-11 00:24
oooh... synthtread is an expedition reward i guess.


> genuinely curious what this means.

in this situation, it should be item interaction + item mechanic = poor gameplay interaction

**Comment by Emisse** [comment] 2023-07-11 00:25
they are interacting with nobody other than themselves to obtain a powerful tool to bypass an entire game mechanic

**Comment by asperger-sind** [comment] 2023-07-11 00:28
Just make medbeds heal like normal beds but have a beaker slot like the cryotube for tricordzarcdine or some shit

**Comment by deltanedas** [comment] 2023-07-11 01:48
then why bother restocking it with tricord when you can just inject yourself

**Comment by lzk228** [comment] 2023-07-11 07:35
lrp moment

**Comment by Anzarot121** [comment] 2023-07-12 23:46
Never noticed such problems on MRP servers. Maybe you just need to forbid by the rules to craft them to everyone except engineers?

**Comment by LankLTE** [comment] 2023-07-12 23:56
> Never noticed such problems on MRP servers. Maybe you just need to forbid by the rules to craft them to everyone except engineers?

That’s a dumb rule to have, especially when something’s so readily available in a construction menu like that. If their use is that important they could be made to require boards and be a Sci research.

**Comment by Anzarot121** [comment] 2023-07-13 00:01
> That’s a dumb rule to have, especially when something’s so readily available in a construction menu like that. If their use is that important they could be made to require boards and be a Sci research.

T1 med technology is really good answer for this problem.

**Comment by UbaserB** [comment] 2023-12-30 07:58
They don't have much of an effect in regards to healing and you can already craft normal beds so i agree with removing the recipe.

**Comment by K-Dynamic** [comment] 2023-12-30 08:14
That's because they got nerfed a lot sometime during or after this issue

Medical beds still retain some roleplay value (at least on mrp where they're regularly built) to give med something to do, and they also provide free healing during critical moments such as without chems/power

**Comment by slarticodefast** [comment] 2024-08-25 19:56
I'm closing this for now, see the discussion in #31316
This can be re-evaluated once NewMed is included.

**Closed by slarticodefast** 2024-08-25 19:56 UTC
Labels: Needs Discussion, Issue: Needs Cleanup, Difficulty: 1-Easy
