### ISSUE TITLE
Voxes that appear on shuttles do not have a nitrogen tank..

### ISSUE THREAD

**Issue by marboww** [space-wizards/space-station-14#30080] opened 2024-07-16 02:34 UTC
## Description

Voxes that appear on shuttles do not have a nitrogen tank. Because of this they simply die after a while.

**Comment by marboww** [comment] 2024-07-16 02:38
#29756

**Comment by Tayrtahn** [comment] 2024-07-16 13:54
Duplicate of #29756

**Closed by Tayrtahn** 2024-07-16 13:55 UTC
Labels: Status: Untriaged
