### ISSUE TITLE
Some replays have their start point in weird locations

### ISSUE THREAD

**Issue by XxSWAG-MASTER-OVERLORDxX** [space-wizards/space-station-14#29812] opened 2024-07-08 06:19 UTC
## Description
Sometimes when you start a replay the start point will be somewhere other than in the middle of the station.
sometimes spawning the observer out in space and unable to ever see the station.

**Comment by IProduceWidgets** [comment] 2024-07-10 18:25
Dupe of #29725

**Closed by IProduceWidgets** 2024-07-10 18:25 UTC
Labels: Status: Untriaged
