### ISSUE TITLE
Expedition maps can exist paused with active ghost roles

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#17115] opened 2023-06-04 05:51 UTC
## Description

Not sure how to reproduce, but a round had a paused expedition map with an active xeno queen ghost role that someone was able to take

**Comment by deltanedas** [comment] 2023-06-04 11:53
dupe of something

**Comment by metalgearsloth** [comment] 2023-06-04 11:55
https://github.com/space-wizards/space-station-14/issues/16975

**Closed by metalgearsloth** 2023-06-04 11:55 UTC
