### ISSUE TITLE
Mouseovering puddles makes them look more transparent 

### ISSUE THREAD

**Issue by Aranclanos** [space-wizards/space-station-14#2327] opened 2020-10-20 16:16 UTC
![image](https://user-images.githubusercontent.com/701959/96614338-67e08200-12d6-11eb-9900-b2a0b3a7c238.png)
left side normal, right side being mouseovered

**Comment by AJCM-git** [comment] 2020-10-20 16:19
duplicate of #1377

**Closed by AJCM-git** 2020-10-20 16:19 UTC
