### ISSUE TITLE
Stunned lizards can pull things with their tails when downed if they hold onto it before they get stunned

### ISSUE THREAD

**Issue by Jarmer123** [space-wizards/space-station-14#27636] opened 2024-05-03 01:03 UTC
## Description
A lizard can for example grab a locker before being stunned and use it to push people away to prevent cuffing. I do not know if this is intended behaviour. 

**Reproduction**
1. Grab an object
2. Get stunned
3. Use the object to move yourself around or push people away
**Screenshots**
N/A

**Additional context**
N/A

**Comment by B1essedknight** [comment] 2024-05-03 14:12
dupe of #27088 

thanks for calling it in though.

**Closed** 2024-05-08 06:49 UTC
Labels: Status: Untriaged
