### ISSUE TITLE
Thieving beacon and crates bug

### ISSUE THREAD

**Issue by lzk228** [space-wizards/space-station-14#31622] opened 2024-08-29 12:11 UTC
somehow thieving beacon counts every item in crate twice for objective
more info in attached video

https://github.com/user-attachments/assets/db84cbaf-7d1a-4605-aef2-15d4381a360a

**Comment by slarticodefast** [comment] 2024-08-29 12:35
Duplicate of #31337

**Closed by slarticodefast** 2024-08-29 12:35 UTC
Labels: Status: Untriaged
