### ISSUE TITLE
You can not unbuckle others from vehicles

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#17275] opened 2023-06-12 05:39 UTC
## Description
If someone gets on a vehicle, you can not unbuckle them. I only experienced this on a unicycle but i heard reports that it is affecting secways so its perhaps all vehicles. 

**Reproduction**
Try to unbuckle someone on a unicycle or any other vehicle.

**Comment by deltanedas** [comment] 2023-06-12 15:49
it should be a doafter so trollers dont just speed unbuckle people on secways

**Comment by Partmedia** [comment] 2023-07-31 17:39
Duplicate of #15462

**Closed by Partmedia** 2023-07-31 17:39 UTC
