### ISSUE TITLE
BUG with Quantum Spin Inverter (free cliping and invisibility without time penalty)

### ISSUE THREAD

**Issue by vanilia123** [space-wizards/space-station-14#24845] opened 2024-02-01 23:56 UTC
## Description

During one of the rounds on mander, SCI Jeremy Sirens with Quantum spin inverter, was able to clip across map, was invisible, and got other weird powers. After taking his quantum spin caused a massive bug for me in which I was in two dimensions, one normal station, and the other almost like luminar space empty station. 
Round number: #45402

**Reproduction**
I assume massive production of quantum spin inverters, and bad luck... (sorry no clue)

**Screenshots**

Videos : 
(I couldnt record first bug encounter when player was abusive this item since I tried to report it via ahelp, but admins didnt see anything weird from ghosts perspective, crewmates could)

https://screenrec.com/share/49TsjQHPpe
https://screenrec.com/share/euCmZsUXDn
https://screenrec.com/share/KqcZhS2J9o (not much information, but provide context of the round I guess)

**Additional context**
That's my first "report", encounter with that item or "contribution" I apologize for lack of details, but thats all I could gather.

**Comment by vanilia123** [comment] 2024-02-02 00:02
I tried to remind myself of any other important information, and its worth to mention that this SCI person was also using regular sci lab closet opening/closing using quantum. Perhaps this could also help out with reproduction of that bug?

**Comment by GoodWheatley** [comment] 2024-02-02 01:38
Duplicate of #24095

**Closed by GoodWheatley** 2024-02-02 01:38 UTC

**Comment by GoodWheatley** [comment] 2024-02-02 01:39
Thank you for the video footage of the bug and the report regardless.
