### ISSUE TITLE
Milk jugs shatter like glass

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/space-station-14#15230] opened 2023-04-09 01:37 UTC
## Description

0/10 inauthentic milk experience

**Comment by Myakot** [comment] 2023-10-26 12:45
Should be closed by #15250

**Comment by scrivoy** [comment] 2024-10-10 21:55
Hi everyone,
I’ve checked the issue and I'm unable to reproduce it.
Could it be that the bug has already been fixed, but the issue hasn’t been closed yet?

**Comment by lzk228** [comment] 2024-10-11 08:10
https://github.com/user-attachments/assets/e05aa87c-2bf8-4224-80d2-a5aa11320aed

**Comment by scrivoy** [comment] 2024-10-11 09:39
Yeah, exactly the same for me.
And also for the other packages like Soy Milk.

**Closed** 2024-10-11 10:42 UTC
Labels: Issue: Bug, No C#, Difficulty: 1-Easy, Bug: Replicated
