### ISSUE TITLE
Loading in space ambiance can make the client freeze for a second.

### ISSUE THREAD

**Issue by TemporalOroboros** [space-wizards/space-station-14#10820] opened 2022-08-24 13:39 UTC
## Description

The client freezes just after entering space and begins playing the space ambiance immediately after the lagspike ends. I am assuming that the lagspike is caused by the client downloading the entire space ambiance track every time the game realizes the player character has moved from the station to space.

**Reproduction**

1. Move from the station grid to space.
2. Wait a fraction of a second.
3. Eat a lagspike.
4. Hear the space ambiance start playing.

**Comment by metalgearsloth** [comment] 2022-08-24 13:47
Dupe of engine issue https://github.com/space-wizards/RobustToolbox/issues/2983

**Closed by metalgearsloth** 2022-08-24 13:47 UTC
