### ISSUE TITLE
Particle Accelerator "Looks Unfinished" Bug

### ISSUE THREAD

**Issue by TexasPeach517** [space-wizards/space-station-14#19795] opened 2023-09-03 19:33 UTC
## Description
When trying to create the PA on maps like Barratry in particular when the PA is all disassembled when reassembling it you can make the PA till the last step and it won't allow you to finish constructing the PA and in the description just says "Looks Unfinished" and states no further steps to complete the computer, or any of the parts in the PA.

**Reproduction**
Go on maps like Barratry, Packed, ... As long as the PA has the boards and empty machine frames and try to make the PA.

**Screenshots**
N/A
**Additional context**
I believe the boards for the PA are bugged, because I disassembled the machine frames and made new ones and etc... Also I believe you can buy the PA from Cargo and it'll work but I have never done due to wanting save money for the station for better use and labor. Also it's kind of a bummer especially on Barratry and set up everything from scratch and then not being able to use it. **Also in the guide book it still shows the PA still needing a HV cable despite it being changed to MV may cause some confusion to newer players**

**Comment by crazybrain23** [comment] 2023-09-07 12:18
Duplicate of #18511.

**Closed** 2024-03-24 18:09 UTC
