### ISSUE TITLE
New mind role heisentest

### ISSUE THREAD

**Issue by slarticodefast** [space-wizards/space-station-14#32740] opened 2024-10-10 19:48 UTC
## Description
See stack trace https://github.com/space-wizards/space-station-14/actions/runs/11279674612/job/31370933705?pr=32737
```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed DeleteAllThenGhost [335 ms]
  Error Message:
   Multiple failures or warnings in test:
  1) SERVER: 0.307s [ERRO] entity: Caught exception while raising event EntityTerminatingEvent on entity Carry Boyer (111683/n111683, MobHuman)
System.Collections.Generic.KeyNotFoundException: Entity 111682 does not have a component of type Content.Shared.Roles.MindRoleComponent
   at Content.Shared.Roles.SharedRoleSystem.CheckAntagonistStatus(EntityUid mindId) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Roles/SharedRoleSystem.cs:line 481
   at Content.Shared.Roles.SharedRoleSystem.MindIsAntagonist(Nullable`1 mindId) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Roles/SharedRoleSystem.cs:line 444
   at Content.Server.Administration.Systems.AdminSystem.GetPlayerInfo(SessionData data, ICommonSession session) in /home/runner/work/space-station-14/space-station-14/Content.Server/Administration/Systems/AdminSystem.cs:line 245
   at Content.Server.Administration.Systems.AdminSystem.UpdatePlayerList(ICommonSession player) in /home/runner/work/space-station-14/space-station-14/Content.Server/Administration/Systems/AdminSystem.cs:line 135
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 200
   at Robust.Shared.Player.SharedPlayerManager.Detach(ICommonSession session) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Player/SharedPlayerManager.Sessions.cs:line 188
   at Robust.Shared.Player.SharedPlayerManager.SetAttachedEntity(ICommonSession session, Nullable`1 uid, ICommonSession& kicked, Boolean force) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Player/SharedPlayerManager.Sessions.cs:line 170
   at Content.Server.Mind.MindSystem.TransferTo(EntityUid mindId, Nullable`1 entity, Boolean ghostCheckOverride, Boolean createGhost, MindComponent mind) in /home/runner/work/space-station-14/space-station-14/Content.Server/Mind/MindSystem.cs:line 259
   at Content.Server.Mind.MindSystem.OnMindContainerTerminating(EntityUid uid, MindContainerComponent component, EntityTerminatingEvent& args) in /home/runner/work/space-station-14/space-station-14/Content.Server/Mind/MindSystem.cs:line 69
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 633
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 218
   at Robust.Shared.GameObjects.EntityManager.RecursiveFlagEntityTermination(EntityUid uid, MetaDataComponent metadata, TransformComponent xform) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 568 Exception: 
  2) Console command encountered an error: Failed to execute toolshed command
  3) SERVER: 0.313s [ERRO] con: [HOST]: ExecuteError - entities delete:
NUnit.Framework.AssertionException: Multiple failures or warnings in test:
  1) SERVER: 0.307s [ERRO] entity: Caught exception while raising event EntityTerminatingEvent on entity Carry Boyer (111683/n111683, MobHuman)
System.Collections.Generic.KeyNotFoundException: Entity 111682 does not have a component of type Content.Shared.Roles.MindRoleComponent
   at Content.Shared.Roles.SharedRoleSystem.CheckAntagonistStatus(EntityUid mindId) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Roles/SharedRoleSystem.cs:line 481
   at Content.Shared.Roles.SharedRoleSystem.MindIsAntagonist(Nullable`1 mindId) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Roles/SharedRoleSystem.cs:line 444
   at Content.Server.Administration.Systems.AdminSystem.GetPlayerInfo(SessionData data, ICommonSession session) in /home/runner/work/space-station-14/space-station-14/Content.Server/Administration/Systems/AdminSystem.cs:line 245
   at Content.Server.Administration.Systems.AdminSystem.UpdatePlayerList(ICommonSession player) in /home/runner/work/space-station-14/space-station-14/Content.Server/Administration/Systems/AdminSystem.cs:line 135
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 200
   at Robust.Shared.Player.SharedPlayerManager.Detach(ICommonSession session) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Player/SharedPlayerManager.Sessions.cs:line 188
   at Robust.Shared.Player.SharedPlayerManager.SetAttachedEntity(ICommonSession session, Nullable`1 uid, ICommonSession& kicked, Boolean force) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Player/SharedPlayerManager.Sessions.cs:line 170
   at Content.Server.Mind.MindSystem.TransferTo(EntityUid mindId, Nullable`1 entity, Boolean ghostCheckOverride, Boolean createGhost, MindComponent mind) in /home/runner/work/space-station-14/space-station-14/Content.Server/Mind/MindSystem.cs:line 259
   at Content.Server.Mind.MindSystem.OnMindContainerTerminating(EntityUid uid, MindContainerComponent component, EntityTerminatingEvent& args) in /home/runner/work/space-station-14/space-station-14/Content.Server/Mind/MindSystem.cs:line 69
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 633
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 218
   at Robust.Shared.GameObjects.EntityManager.RecursiveFlagEntityTermination(EntityUid uid, MetaDataComponent metadata, TransformComponent xform) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 568 Exception: 
  2) Console command encountered an error: Failed to execute toolshed command

   at NUnit.Framework.Assert.ReportFailure(String message)
   at NUnit.Framework.Assert.Fail(String message)
   at Robust.UnitTesting.TestingServerConsoleHost.WriteError(ICommonSession session, String text) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.UnitTesting/TestingConsoleHost.cs:line 13
   at Robust.Shared.Console.ConsoleShell.WriteError(String text) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Console/ConsoleShell.cs:line 60
   at Robust.Server.Console.ServerConsoleHost.ExecuteInShell(IConsoleShell shell, String command) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Console/ServerConsoleHost.cs:line 142 Exception: 

  Stack Trace:
     at Content.IntegrationTests.PoolTestLogHandler.Log(String sawmillName, LogEvent message) in /home/runner/work/space-station-14/space-station-14/Content.IntegrationTests/PoolTestLogHandler.cs:line 66
   at Robust.Shared.Log.LogManager.Sawmill.LogInternal(String sourceSawmill, LogEvent message) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Log/LogManager.Sawmill.cs:line 106
   at Robust.Shared.Log.LogManager.Sawmill.LogInternal(String sourceSawmill, LogEvent message) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Log/LogManager.Sawmill.cs:line 125
   at Robust.Shared.Log.LogManager.Sawmill.Log(LogLevel level, String message, Object[] args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Log/LogManager.Sawmill.cs:line 96
   at Robust.Shared.Log.LogManager.Sawmill.Error(String message) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Log/LogManager.Sawmill.cs:line 174
   at Robust.Server.Console.ServerConsoleHost.ExecuteInShell(IConsoleShell shell, String command) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Console/ServerConsoleHost.cs:line 150
   at Robust.Server.Console.ServerConsoleHost.ExecuteCommand(ICommonSession session, String command) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/Console/ServerConsoleHost.cs:line 36
   at Robust.Shared.Console.ConsoleHost.ExecuteCommand(String command) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Console/ConsoleHost.cs:line 239
   at Content.IntegrationTests.Tests.Minds.MindTests.<>c__DisplayClass0_0.<DeleteAllThenGhost>b__0() in /home/runner/work/space-station-14/space-station-14/Content.IntegrationTests/Tests/Minds/MindTest.DeleteAllThenGhost.cs:line 27
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationGameLoop.SingleThreadRunUntilEmpty() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 1098
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationGameLoop.Run() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 1085
   at Robust.UnitTesting.RobustIntegrationTest.ServerIntegrationInstance._serverMain() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 656
--- End of stack trace from previous location ---
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationInstance.WaitIdleImplAsync(Boolean throwOnUnhandled, CancellationToken cancellationToken) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 450
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationInstance.WaitPost(Action post) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 573
   at Content.IntegrationTests.Tests.Minds.MindTests.DeleteAllThenGhost() in /home/runner/work/space-station-14/space-station-14/Content.IntegrationTests/Tests/Minds/MindTest.DeleteAllThenGhost.cs:line 27
   at Content.IntegrationTests.Tests.Minds.MindTests.DeleteAllThenGhost() in /home/runner/work/space-station-14/space-station-14/Content.IntegrationTests/Tests/Minds/MindTest.DeleteAllThenGhost.cs:line 59
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)

1)    at Content.IntegrationTests.Pair.TestPair.OnDirtyDispose() in /home/runner/work/space-station-14/space-station-14/Content.IntegrationTests/Pair/TestPair.Recycle.cs:line 34
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Content.IntegrationTests.Pair.TestPair.OnDirtyDispose()
   at Content.IntegrationTests.Pair.TestPair.DisposeAsync() in /home/runner/work/space-station-14/space-station-14/Content.IntegrationTests/Pair/TestPair.Recycle.cs:line 121
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Content.IntegrationTests.Pair.TestPair.DisposeAsync()
   at Content.IntegrationTests.Tests.Minds.MindTests.DeleteAllThenGhost() in /home/runner/work/space-station-14/space-station-14/Content.IntegrationTests/Tests/Minds/MindTest.DeleteAllThenGhost.cs:line 59
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
```

**Reproduction**
Run integration tests
Hope that it fails

**Additional context**
Likely introduced in #31318

**Comment by Errant-4** [comment] 2024-10-11 07:13
I have not been able to trigger the test locally on the latest master after an hour of running the test.
In any case, I'm not really sure it's because of mind roles anymore, because I checked and Mind Roles was merged 10 hours before the first occurence, and it has been happening way more frequently than that.

**Comment by Errant-4** [comment] 2024-10-11 07:23
The only merge inbetween is #32700, which itself did have a test fail, which was discarded as a heisenfail. It was not exactly this test that failed, though the scope of that test seems similar
https://github.com/space-wizards/space-station-14/actions/runs/11276037983/job/31358877581#step:10:313

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed SpawnAndDeleteAllEntitiesInTheSameSpot [2 m 52 s]
  Error Message:
   System.InvalidOperationException : Nullable object must have a value.

  1) Test was dirty-disposed.

  Stack Trace:
     at System.Nullable`1.get_Value()
   at Content.Shared.Projectiles.SharedProjectileSystem.OnEmbedProjectileHit(EntityUid uid, EmbeddableProjectileComponent component, ProjectileHitEvent& args) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Projectiles/SharedProjectileSystem.cs:line 107
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass56_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 305
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass67_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 460
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 633
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 240
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 218
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystem.cs:line 170
   at Content.Server.Projectiles.ProjectileSystem.OnStartCollide(EntityUid uid, ProjectileComponent component, StartCollideEvent& args) in /home/runner/work/space-station-14/space-station-14/Content.Server/Projectiles/ProjectileSystem.cs:line 45
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 633
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 218
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.CollideContacts() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Physics/Systems/SharedPhysicsSystem.Contacts.cs:line 563
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.SimulateWorld(Single deltaTime, Boolean prediction) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Physics/Systems/SharedPhysicsSystem.cs:line 301
   at Robust.Shared.GameObjects.EntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 273
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 196
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 704
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationGameLoop.SingleThreadRunUntilEmpty() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 1098
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationGameLoop.Run() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 1085
   at Robust.UnitTesting.RobustIntegrationTest.ServerIntegrationInstance._serverMain() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 656
--- End of stack trace from previous location ---
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationInstance.WaitIdleImplAsync(Boolean throwOnUnhandled, CancellationToken cancellationToken) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 450
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationInstance.WaitRunTicks(Int32 ticks) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 542
   at Content.IntegrationTests.Tests.EntityTest.SpawnAndDeleteAllEntitiesInTheSameSpot() in /home/runner/work/space-station-14/space-station-14/Content.IntegrationTests/Tests/EntityTest.cs:line 110
   at Content.IntegrationTests.Tests.EntityTest.SpawnAndDeleteAllEntitiesInTheSameSpot() in /home/runner/work/space-station-14/space-station-14/Content.IntegrationTests/Tests/EntityTest.cs:line 133
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass3_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
1)    at Content.IntegrationTests.Pair.TestPair.OnDirtyDispose() in /home/runner/work/space-station-14/space-station-14/Content.IntegrationTests/Pair/TestPair.Recycle.cs:line 34
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Content.IntegrationTests.Pair.TestPair.OnDirtyDispose()
   at Content.IntegrationTests.Pair.TestPair.DisposeAsync() in /home/runner/work/space-station-14/space-station-14/Content.IntegrationTests/Pair/TestPair.Recycle.cs:line 121
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Content.IntegrationTests.Pair.TestPair.DisposeAsync()
   at Content.IntegrationTests.Tests.EntityTest.SpawnAndDeleteAllEntitiesInTheSameSpot() in /home/runner/work/space-station-14/space-station-14/Content.IntegrationTests/Tests/EntityTest.cs:line 133
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)

2)    at System.Nullable`1.get_Value()
   at Content.Shared.Projectiles.SharedProjectileSystem.OnEmbedProjectileHit(EntityUid uid, EmbeddableProjectileComponent component, ProjectileHitEvent& args) in /home/runner/work/space-station-14/space-station-14/Content.Shared/Projectiles/SharedProjectileSystem.cs:line 107
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass56_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 305
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass67_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 460
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 633
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 240
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 218
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntitySystem.cs:line 170
   at Content.Server.Projectiles.ProjectileSystem.OnStartCollide(EntityUid uid, ProjectileComponent component, StartCollideEvent& args) in /home/runner/work/space-station-14/space-station-14/Content.Server/Projectiles/ProjectileSystem.cs:line 45
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 633
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent& args, Boolean broadcast) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 218
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.CollideContacts() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Physics/Systems/SharedPhysicsSystem.Contacts.cs:line 563
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.SimulateWorld(Single deltaTime, Boolean prediction) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Physics/Systems/SharedPhysicsSystem.cs:line 301
   at Robust.Shared.GameObjects.EntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 273
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 196
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Server/BaseServer.cs:line 704
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationGameLoop.SingleThreadRunUntilEmpty() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 1098
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationGameLoop.Run() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 1085
   at Robust.UnitTesting.RobustIntegrationTest.ServerIntegrationInstance._serverMain() in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 656
--- End of stack trace from previous location ---
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationInstance.WaitIdleImplAsync(Boolean throwOnUnhandled, CancellationToken cancellationToken) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 450
   at Robust.UnitTesting.RobustIntegrationTest.IntegrationInstance.WaitRunTicks(Int32 ticks) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.UnitTesting/RobustIntegrationTest.cs:line 542
   at Content.IntegrationTests.Tests.EntityTest.SpawnAndDeleteAllEntitiesInTheSameSpot() in /home/runner/work/space-station-14/space-station-14/Content.IntegrationTests/Tests/EntityTest.cs:line 110
   at Content.IntegrationTests.Tests.EntityTest.SpawnAndDeleteAllEntitiesInTheSameSpot() in /home/runner/work/space-station-14/space-station-14/Content.IntegrationTests/Tests/EntityTest.cs:line 133
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass3_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
```

**Comment by Errant-4** [comment] 2024-10-11 07:47
(apparently my mistake was running the failing test by itself)

**Comment by slarticodefast** [comment] 2024-10-11 11:00
Another case of the mindrole heisentest:
https://github.com/space-wizards/space-station-14/actions/runs/11288519971/job/31396451606?pr=32710

> The only merge inbetween is https://github.com/space-wizards/space-station-14/pull/32700, which itself did have a test fail, which was discarded as a heisenfail. It was not exactly this test that failed, though the scope of that test seems similar

That one is old, it's something with embeddable projectiles where the weapon entity does not exist.

**Comment by Errant-4** [comment] 2024-10-11 16:40
Ok I think I see where the problem is, but for some reason it only happens when I run ALL the tests, it never happens when I only run the 24 Mind tests. And I can't run Debug on ALL tests. So I can't catch this running. But I mostly see how I could resolve the anomalous condition, I just don't see how it can possibly occur

**Closed** 2024-10-11 19:17 UTC
Labels: Issue: Heisentest
