### ISSUE TITLE
Binding Pull And Release To The Same Key allows Infinite Pulling

### ISSUE THREAD

**Issue by Monoblaster** [space-wizards/space-station-14#8950] opened 2022-06-19 00:54 UTC
## Description
You are able to pull infinite things by binding pull and release to the same key. Once they are being pulled by you, you cannot release them.

**Reproduction**
Bind pull and release to the same key.
Start pulling something.
Notice something has gone horribly wrong when you can't release it.
Pull many things at once.

**Comment by moonheart08** [comment] 2022-06-19 01:20
This is a duplicate of https://github.com/space-wizards/security-issues/issues/7, which i filed minutes prior, but it's public now so RIP.

**Comment by Errant-4** [comment] 2024-07-23 17:51
Issue can not be reproduced. The second item starts getting pulled, the first one is left behind. This is what one would expect to happen.

Both pull and release are probably triggered, because if I also bind Scream to the same key, the scream does occur in addition to pulling. Whatever code was causing this must have been changed at some point

Can anyone still repro?

**Closed** 2024-11-24 15:45 UTC
Labels: T: Bugfix, P1: High, Issue: Needs Replicating
