### ISSUE TITLE
Air injector sprite still the old one above tile

### ISSUE THREAD

**Issue by Emisse** [space-wizards/space-station-14#9546] opened 2022-07-08 20:24 UTC
![image](https://user-images.githubusercontent.com/99158783/178065274-195d6c3b-31e0-49e1-9dc3-cd7a9faa49af.png)
see image

**Comment by ElectroJr** [comment] 2022-07-08 21:46
Duplicate of #8996? Or is this somehow different?

**Closed by ElectroJr** 2022-07-08 21:46 UTC

**Comment by Emisse** [comment] 2022-07-08 21:55
oh yea i forgot i made this issue already lol
