### ISSUE TITLE
Crafting multiple of a stackable item doesn't add to stack in your hand

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#3482] opened 2021-03-03 07:51 UTC
## Description

Title.

**Comment by Zumorica** [comment] 2021-03-06 13:01
This is very tricky because hand code sucks and I don't want to hardcode it...

**Comment by AJCM-git** [comment] 2021-11-07 04:07
dupe of  #3704

**Closed by AJCM-git** 2021-11-07 04:07 UTC
Labels: Priority: 2-Before Release, Type: Improvement, Difficulty: 2-Medium
