### ISSUE TITLE
Applying carpet to a table uses all carpet in stack

### ISSUE THREAD

**Issue by Moomoobeef** [space-wizards/space-station-14#26423] opened 2024-03-25 05:49 UTC
## Description
You only need 1 peice of carpet to apply it as a table cloth, however if you are holding a stack of say 3 carpet, the whole stack will be used when applying a tablecloth.

**Reproduction**
1. hold multiple pieces of carpet in your hand
2. click on a table to apply it as a table-cloth
3. once applied, it will have used all the carpet in your hand

**Comment by UbaserB** [comment] 2024-03-25 07:02
Duplicate of #25687

**Closed by UbaserB** 2024-03-25 07:02 UTC
Labels: Status: Untriaged
