### ISSUE TITLE
The highlighting hitboxes are fat

### ISSUE THREAD

**Issue by partyaddict** [space-wizards/space-station-14#674] opened 2020-02-09 10:12 UTC
![](https://i.imgur.com/MMd5MLO.gif)
![image](https://user-images.githubusercontent.com/52793290/74100240-89248800-4b24-11ea-8f6c-cf19cd77a8a4.png)
Prevents you from placing floor tiles over wires and getting floortiles from under airlocks

Another complimentary .gif

I already reported this on the discord but I'm just showing more cases of hitboxes being horrible.

**Comment by ShadowCommander** [comment] 2020-02-09 10:18
Duplicate of #601

**Comment by partyaddict** [comment] 2020-02-09 10:22
Still shows off a new case, the airlock

**Comment by AJCM-git** [comment] 2020-06-28 15:43
fixed by #1133

**Closed by AJCM-git** 2020-06-28 15:43 UTC
Labels: Status: Duplicate
