### ISSUE TITLE
[ERRO] runtime: Caught exception in "Component state apply"

### ISSUE THREAD

**Issue by Visne** [space-wizards/space-station-14#1737] opened 2020-08-16 20:54 UTC
```cs
[ERRO] runtime: Caught exception in "Component state apply"
Robust.Client.GameObjects.ComponentStateApplyException: Failed to apply comp state: entity=magazine (.30 rifle) (7568, MagazineLRifle), comp=Transform
 ---> System.Collections.Generic.KeyNotFoundException: The given key '7615' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Robust.Shared.GameObjects.EntityManager.GetEntity(EntityUid uid) in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 122
   at Robust.Shared.GameObjects.Components.Transform.TransformComponent.HandleComponentState(ComponentState curState, ComponentState nextState) in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Shared/GameObjects/Components/Transform/TransformComponent.cs:line 721
   at Robust.Client.GameObjects.ClientEntityManager.HandleEntityState(IComponentManager compMan, IEntity entity, EntityState curState, EntityState nextState) in /var/lib/jenkins/workspace/SS14 Content@2/RobustToolbox/Robust.Client/GameObjects/ClientEntityManager.cs:line 288
   --- End of inner exception stack trace ---
```

**Comment by exp111** [comment] 2020-08-16 21:16
Duplicate of #1691

**Closed** 2020-08-16 21:20 UTC
