### ISSUE TITLE
People are clipping through doors

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#12363] opened 2022-11-03 00:17 UTC
## Description

Supposedly after entering a disposals unit. Reentering the unit and exiting fixes the bug. During the duration of the bug, people can walk through doors freely. Reported by several people on Lizard

**Reproduction**

(?)
1) enter disposals unit
2) exit
3) try to walk through door

**Screenshots**

![image](https://user-images.githubusercontent.com/19853115/199625848-a7ca1008-bf1b-47ac-9835-d7130ac3aac5.png)

**Additional context**

**Comment by mirrorcult** [comment] 2022-11-03 00:18
@ElectroJr ?

**Comment by metalgearsloth** [comment] 2022-11-03 00:18
Pretty sure https://github.com/space-wizards/RobustToolbox/pull/3429 fixes this and I think there's a separate issue.

**Comment by Emisse** [comment] 2022-11-03 00:27
its people clipping through everything not just doors

**Comment by Emisse** [comment] 2022-11-03 00:28
dupe of #12342

**Closed** 2022-11-03 00:31 UTC
