### ISSUE TITLE
carrying infinite wood 

### ISSUE THREAD

**Issue by joris309** [space-wizards/space-station-14#11001] opened 2022-09-03 21:03 UTC
alright so i found this bug with the tower cap mushroom where if you put the logs in the plant bag and then you cut them with the scythe the wood gets stuck to your plant bag it can be picked up of the ground at any time and can only be seen wehn the plant bag is taken out of the inventory it doesnt fill up the plant bag anymore meaning you can carry an infinite amount

sadly i didnt take any screenshots but i think waht i said describes it pretty well

**Comment by joris309** [comment] 2022-09-03 21:05
alright so i found this bug with the tower cap mushroom where if you put the logs in the plant bag and then you cut them with the scythe the wood gets stuck to your plant bag it can be picked up of the ground at any time and can only be seen wehn the plant bag is taken out of the inventory it doesnt fill up the plant bag anymore meaning you can carry an infinite amount

**Comment by Visne** [comment] 2022-09-03 21:10
![image](https://user-images.githubusercontent.com/39844191/188287741-291dec69-d34c-4422-ab35-06e5cbc5e464.png)

More context

**Comment by Visne** [comment] 2022-09-03 21:11
It made it possible to click right next to them, and then you would pick up wood. Really weird bug.

**Comment by ElectroJr** [comment] 2022-09-04 07:54
Probably a duplicate of #6090, so ill close this for now.

AFAIK most instances of this have been fixed, but some things like crafting, specifically wood, still has this issue where it just attaches to the parent, rather than inserting into the containing container or attaching to the grid.

**Closed by ElectroJr** 2022-09-04 07:54 UTC
