### ISSUE TITLE
Chem vends are not showing chem names

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#29292] opened 2024-06-21 07:32 UTC
## Description
On the chemvend window its not showing the names

**Reproduction**
- open chemvend

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/004c8819-fcef-4199-ad02-4f3fbb016e4f)

**Additional context**
NA

**Comment by lzk228** [comment] 2024-06-21 07:39
its the third dupe bruh #29140

**Comment by Tayrtahn** [comment] 2024-06-21 14:42
Duplicate of #29140

A fix is in the works, I assure you!

**Closed by Tayrtahn** 2024-06-21 14:42 UTC
Labels: Status: Untriaged
