### ISSUE TITLE
Nanotrasen Block Game seems to be broken.

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#27615] opened 2024-05-02 09:44 UTC
## Description
Nanotrasen Block Game arcade game doesn't load

**Reproduction**
See screenshot

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/edda1d2a-f702-40df-ae10-b5852fe2f670)

**Additional context**
NA

**Comment by liltenhead** [comment] 2024-05-02 09:46
*Nanotrasen Block Game™️

**Comment by Lukasz825700516** [comment] 2024-05-03 05:58
duplicate of https://github.com/space-wizards/space-station-14/issues/27347 ?

**Closed** 2024-07-26 17:30 UTC
Labels: Status: Untriaged
