### ISSUE TITLE
Reagent Grinders have 1000x negative inertia and are FUCKED

### ISSUE THREAD

**Issue by SebaenSah** [space-wizards/space-station-14#29480] opened 2024-06-26 02:20 UTC
## Description
Reagent grinders become quantum objects when unwrenched and pulled. The grinders push other entities so hard they take damage, go through walls and just teleport randomly. I'ma be honest but quite frankly I don't know what the fuck is happening.

**Reproduction**
-Find reagent grinder.
-Unwrench it.
-Pull it into other character entities.
-Chaos.

**Screenshots**
Screenshots are not needed to reproduce this bug.

**Additional context**
TurboTracker helped confirm the bug and saved multiple people I accidentally flung into walls IM SO SORRY TO WHOEVER YOU ARE!!

**Comment by Cojoke-dot** [comment] 2024-06-26 02:23
The electrolyzer does the same thing, I would bet the centrifuge and hot plate do it to

**Comment by Veritable-Calamity** [comment] 2024-06-26 02:23
> The electrolyzer does the same thing, I would bet the centrifuge and hot plate do it to

You beat me to saying the same thing.

**Comment by metalgearsloth** [comment] 2024-06-26 03:14
The bounds aren't centered around 0 but needs checking so it might just be that.

**Comment by lzk228** [comment] 2024-06-26 06:13
dupe of #28028

**Comment by Plykiya** [comment] 2024-06-26 06:18
> dupe of #28028

Superseded for having better details, though?

**Comment by SebaenSah** [comment] 2024-06-27 04:38
> dupe of #28028
That bug report is more worthy of deletion than anything else. It does not...
-Follow the bug report guidelines
-Give enough detail to bug fixers to triage or even properly understand the issue.
-Doesn't even use a single word like at all? No wonder it's been ignored for nearly two months.

**Closed** 2024-09-14 16:29 UTC
Labels: Status: Untriaged
