### ISSUE TITLE
Using QSI in Cryopod gives you noclip and invisibility

### ISSUE THREAD

**Issue by Scruq445** [space-wizards/space-station-14#27438] opened 2024-04-28 11:41 UTC
## Description
Using a QSI linked to someone in a cryopod gives you a bugged state that makes it so you are invisible, have no clip, and not being interactable (right click and shift click doesn't work when on them)

**Reproduction**
get a person to get into the cryopod
get 2 quantum spin inverters and link them together
get one bag that is not a bag of holding
put one QSI into the bag and put the bag on the person
put the person into the cryopod
activate the other QSI

**Videos**
https://github.com/space-wizards/space-station-14/assets/109207982/f05ec9f5-4359-4dbe-8857-b16d8ce1ea5b

https://github.com/space-wizards/space-station-14/assets/109207982/b8eae1a5-b4b5-4fbd-bc3d-734d43dcff9b

**Additional Context**
After a far enough distance from your cryopod, items in your inventory disappear and items won't register as picked up, but is still held. so when you come back close to your cryopod, you now have the item

**Comment by Scruq445** [comment] 2024-04-28 11:41
https://github.com/space-wizards/space-station-14/assets/109207982/07dd18dc-99f1-4479-8443-401822ee54e1

**Comment by Just-a-Unity-Dev** [comment] 2024-04-28 11:42
dupe of #27437 (?)

**Comment by Scruq445** [comment] 2024-04-28 11:44
dang it you beat me

**Comment by EmoGarbage404** [comment] 2024-04-28 13:24
Dupr

**Closed by EmoGarbage404** 2024-04-28 13:24 UTC
Labels: Status: Untriaged
