### ISSUE TITLE
AI (Xeno) Issues

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/space-station-14#3139] opened 2021-02-11 07:56 UTC
AI xenos often get stuck on doors. ~~If too many are spawned only a few remain active and attack the players while the rest just turns into vegetables.~~ Intended, the getting stuck however is not.

Reported by @"Herbert Falsevor#3037"

**Comment by metalgearsloth** [comment] 2021-02-11 08:05
1st is coz of sliding which physics might help, 2nd is because someone spawned more than 64 which is silly.

**Comment by PaulRitter** [comment] 2021-02-11 08:06
silly man

**Comment by AJCM-git** [comment] 2021-02-11 12:20
Duplicate of #2838

**Closed by AJCM-git** 2021-02-11 12:20 UTC
Labels: Area: AI, Type: Bug
