### ISSUE TITLE
Medical scanners sends you to the backrooms

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#20941] opened 2023-10-12 07:20 UTC
## Description
Trying to climb out of a medial scanner will give you a black screen and you are unable to get out. Even if the board gets removed you will still be suck. Need an admin to teleport you out.

**Reproduction**
1. get into a medical scanner.
2. push a directional key to try to get out.

**Screenshots**
Ahelp message:
![image](https://github.com/space-wizards/space-station-14/assets/106507028/3664f7f3-05c6-4e2d-ab29-bfdb9afd888a)

Right when i jumped in:
![image](https://github.com/space-wizards/space-station-14/assets/106507028/0653e1b6-e89f-4b96-a4b9-8af74741ed0c)

When i pushed on a directional key:
![image](https://github.com/space-wizards/space-station-14/assets/106507028/065d4fad-d560-4691-8d8c-a2bea4544afe)

Error when i teleported to an entity stuck in the scanner
![image](https://github.com/space-wizards/space-station-14/assets/106507028/6bbb5241-bf0b-4981-85a3-3090570fed7d)

F3 menu while in black screen:
![image](https://github.com/space-wizards/space-station-14/assets/106507028/45bbab30-08e2-4109-81f6-3c139e5c9f58)

This error spams the log when i get stuck on a urist:
![image](https://github.com/space-wizards/space-station-14/assets/106507028/d928bbf4-b62e-4458-b97d-ac9459f8612b)

I get this error when i click when in the black screen:
![image](https://github.com/space-wizards/space-station-14/assets/106507028/51e0f66d-120e-446d-b18a-f1de41eedb52)

**Additional context**
I was taking airloss and pressure damage after getting the black screen.
I was unable to aghost out of my body or even teleport to another entity.
When trying to teleport to players stuck inside, i also get stuck in the black screen.
I had to respawn myself to get funcality of the game again.

**Comment by TheArturZh** [comment] 2023-10-18 00:03
Caused by latest Climbing refactor, most likely because of missing zero-length direction check
I'll see if i can fix it

**Comment by DrSmugleaf** [comment] 2023-10-25 14:06
Fixed by https://github.com/space-wizards/space-station-14/pull/21071 and https://github.com/space-wizards/space-station-14/pull/21224

**Closed by DrSmugleaf** 2023-10-25 14:06 UTC
