### ISSUE TITLE
Zombies inherent their name, antag status and appearance changes when cloned

### ISSUE THREAD

**Issue by Stealthbomber16** [space-wizards/space-station-14#10890] opened 2022-08-28 01:59 UTC
![image](https://user-images.githubusercontent.com/100171035/187054191-3c43eb4b-994f-4b58-9bbe-0dc686921b36.png)
Cloning a zombie will not remove any of the changes made by zombification after the cloning rework. This confuses new players into thinking they are still zombies, and other players into shooting the zombies.

Zombies should probably be removed from game rotation until this is fixed.

**Comment by Stealthbomber16** [comment] 2022-08-28 01:59
@EmoGarbage404

**Comment by EmoGarbage404** [comment] 2022-08-28 02:02
dupe of #10530

**Closed by EmoGarbage404** 2022-08-28 02:02 UTC
