### ISSUE TITLE
Kill Objs Picking The Same Target

### ISSUE THREAD

**Issue by Kezu02** [space-wizards/space-station-14#21429] opened 2023-11-04 14:30 UTC
**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/143474299/22c4445f-9e61-466c-9218-19f5cff8bb94)

**Comment by deltanedas** [comment] 2023-11-04 14:33
dupe of #21042

**Closed** 2024-02-08 06:32 UTC
