### ISSUE TITLE
Recycler gibs you instantly

### ISSUE THREAD

**Issue by Veritius** [space-wizards/space-station-14#20493] opened 2023-09-25 09:40 UTC
## Description
Very literally the frame you touch it. It'd be better if it just dealt brute damage very very quickly, since you already gib at high brute.

**Reproduction**
1. Emag the recycler.
2. Jump into it.

**Comment by keronshb** [comment] 2023-09-29 00:55
Dupe of #20426

**Closed** 2023-09-29 00:55 UTC
