### ISSUE TITLE
Make all popups send a chat message.

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#4806] opened 2021-10-08 19:54 UTC
## Description
The idea is simply that popups should be logged in chat.
*However*, since the chat has multiple filters, it should have a filter for popup messages, and have it be disabled by default.
This way, if you need to re-read old popup messages for whatever reason, you can do so by simply enabling the popup filter.

---

The fact that popups aren't logged anywhere right now has always bothered me, specially for popups such as the dice roll popup, which would be *really* nice to log for certain situations (tabletop games, roleplay reasons, etc)
While I do agree that cluttering the chat is bad and that popups are a good way to prevent this, I feel like implementing this feature would have the best of both worlds, with none of the disadvantages: If you want your chat cluttered by popups, you can. But by default, it won't. If you want to see past popups to remember what your dice rolled before, you can enable the filter to see and then disable it again. I feel like doing this has no disadvantages at all, only advantages.

**Comment by Willhelm53** [comment] 2022-01-25 06:37
I think I'll give this one a try next. Also seems related to #190.

**Comment by Willhelm53** [comment] 2022-01-25 17:50
In Content.Shared > Chat > ChatChannel.cs there seems to be a chat channel for "Visual" (comment reads: "Visual events the player can see. Basically like visual_message in SS13")

From what I can tell, this Visual channel seems unused currently. Would this overlap with what I'm doing? I'm currently going to ignore it and try to create a new channel "Popup." I imagine that visual_message would be used for important stuff that we wouldn't want the player to filter out.

**Comment by Willhelm53** [comment] 2022-01-25 23:52
After taking it to the Discord it seems like the chat portion of #5438 is needed first. If I understand it correctly, Speech and other In-Character chat needs an ECS refactor ("SpeechSystem" or the like) whereas Out-of-Character chat would go through IChatManager interface.

Either way I've stopped work on this one for now.

**Comment by AJCM-git** [comment] 2023-09-02 21:29
dupe of  #190

**Closed by AJCM-git** 2023-09-02 21:29 UTC
Labels: Priority: 2-Before Release, Needs Discussion, Issue: Feature Request, Difficulty: 1-Easy
