### ISSUE TITLE
Strangeness with Atmos fires and existing flame sources

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#3727] opened 2021-03-27 03:18 UTC
![image](https://user-images.githubusercontent.com/7907891/112708348-d4643c00-8e87-11eb-8f5a-42b9e6adace6.png)

How to reproduce:

Find (or spawn) a plasma canister. Set the release pressure to whatever.
Set a flame source (any welding tool, lit cigar) down near the plasma canister.
Open the valve on the plasma canister.

The fire will start on the tile with the flame source, and might spread to one tile away, but as long as there's nothing else there to catch on fire (such as a player) that one tile will be on fire forever and the fire won't spread.

**Comment by Zumorica** [comment] 2021-03-28 09:59
Can't replicate at all with your steps.

**Comment by Peptide90** [comment] 2021-03-28 10:11
Is this just not a sufficient amount of plasma near the fire to allow it to spread? @TimrodDX can you try with sandbox commands to add more plasma if you test this again?

**Comment by Zumorica** [comment] 2021-03-28 12:24
Managed to replicate it, turns out you were right, and I managed to find the cause of the problem. Thank you for the report!

**Comment by Zumorica** [comment] 2021-03-28 12:28
Fixed by 0884bcf7eca961f48fa19edd59cb38b9e3f9d9a0

**Closed by Zumorica** 2021-03-28 12:28 UTC
Labels: Area: Atmos, Difficulty: 3 - Intermediate, Priority: 2-medium, Type: Bug
