### ISSUE TITLE
Borgs take damage walking over glass shards

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#27949] opened 2024-05-12 08:00 UTC
## Description
Borgs are taking damage walking over glass shards like when humanoids are not wearing shoes.

**Reproduction**
spawn some glass shards and roll over em as borg.

**Screenshots**
NA

**Additional context**
NA

**Comment by Vermidia** [comment] 2024-05-12 08:04
Dupe of #27492

**Closed** 2024-05-12 08:15 UTC
Labels: Status: Untriaged
