### ISSUE TITLE
Telekinesis

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#21715] opened 2023-11-17 07:22 UTC
## Description

Move things at great distance.

**Reproduction**

Pull something, buckle to a roller bed, pull thing around with ctrl+right click, become Jesus.

**Screenshots**

[Larp as Professor X](https://imgur.com/VZxdT9l)

**Additional context**

Does not work with mind bullets, sorry Jack Black.

**Comment by VasilisThePikachu** [comment] 2023-11-27 11:22
Also dupe of #20948

**Closed** 2023-11-27 12:12 UTC
