### ISSUE TITLE
nukies get spontanously frozen?

### ISSUE THREAD

**Issue by AjexRose** [space-wizards/space-station-14#21474] opened 2023-11-05 22:33 UTC
## Description

Sometimes nuclear operatives might just suddenly freeze up for no discernable reason and be incapable of moving
**Reproduction**

Unsure, was not the victim of the bug, but a third party. All I know is that it involved a moth-person player with jug armor, that was found near a empty docking port on Nukie World
**Screenshots**

**Additional context**

It was resolved by shoving em in a chair, but we only figured that out because another player on the team had faced the issue before.

**Comment by deltanedas** [comment] 2023-11-05 22:33
dupe of other issue and i reprod

**Closed** 2023-11-09 01:43 UTC
