### ISSUE TITLE
electrical anomaly super critical effects can lag the server for a good 10 seconds.

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#17059] opened 2023-06-02 04:17 UTC
## Description
When the electrical anomaly goes crit, the lighting effect and all the equipment getting EMP'ed can cause the server to lag. I witnessed one lag the whole server for a solid 10 seconds before everything settled down.

**Screenshots**
Was around this area on cluster station.
![image](https://github.com/space-wizards/space-station-14/assets/106507028/f680ed05-10eb-4095-b6f1-ed6eb8c196ba)

**Additional context**
Might be dependent on location. An area with more equipment to EMP and more lightening entities might have a bigger effect on the lag.

Was on cluster station around one hour into the round.

**Comment by Slava0135** [comment] 2023-06-02 08:10
duplicate of #16301

**Comment by GoodWheatley** [comment] 2023-09-01 16:25
If it’s a duplicate you close your issue!!!!!!!

**Closed by GoodWheatley** 2023-09-01 16:25 UTC
