### ISSUE TITLE
PA computer won't accept lv cable

### ISSUE THREAD

**Issue by liltenhead** [space-wizards/space-station-14#18255] opened 2023-07-24 09:20 UTC
## Description
When you go to complete the PA where you put the lv cables in, the step doesn't appear in the construction process, and it won't let you put the cable in. Thus making the PA unusable. I can get screenshots later if need be, I'm tired though.

**Comment by Emisse** [comment] 2023-07-24 21:10
![image](https://github.com/space-wizards/space-station-14/assets/99158783/88ee5c98-7f5c-4162-a5d6-79367d012614)
occurred again in lizard, no parts will accept lv cable

**Comment by Emisse** [comment] 2023-07-24 21:13
these were started as machine frames and built normally using machine boards, spawning the unfinished parts and replacing these broken ones let them build it

**Comment by Emisse** [comment] 2023-07-24 23:12
bugged again this time roundstart barratry

**Comment by tetonis** [comment] 2023-08-01 01:43
You can't build them manually anymore, they seem to be bugged right now.

**Comment by GoodWheatley** [comment] 2023-09-01 15:35
Dupe of #18511 and #19342

**Closed by GoodWheatley** 2023-09-01 15:35 UTC
