### ISSUE TITLE
Clothing layers something mess up when you equip them

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/space-station-14#7062] opened 2022-03-10 23:18 UTC
## Description

What the title says

**Comment by Pangogie** [comment] 2022-03-10 23:25
It appears to be based on what order you equip them.

**Comment by metalgearsloth** [comment] 2022-03-10 23:27
https://github.com/space-wizards/space-station-14/pull/6984

**Comment by ElectroJr** [comment] 2022-03-11 02:25
also a dupe of #7001

**Closed by ElectroJr** 2022-03-11 02:25 UTC
