### ISSUE TITLE
Artifact Containers collide with artifacts

### ISSUE THREAD

**Issue by LordEclipse** [space-wizards/space-station-14#10447] opened 2022-08-08 22:52 UTC
## Description
This is especially infuriating because you kind of need them to safely transport artifacts.

**Reproduction**
1. Grab an artifact
2. Grab an artifact container
3. Try to move the artifact onto/into the artifact container to contain it.
4. Notice that you can't and the artifact instead just pushes around the container.

**Comment by EmoGarbage404** [comment] 2022-08-08 22:56
dupe of #9695

**Closed by EmoGarbage404** 2022-08-08 22:56 UTC
