### ISSUE TITLE
Space Dragon's Devour destroy corpses/butcher doesn't give the corpses back

### ISSUE THREAD

**Issue by Aisu9** [space-wizards/space-station-14#20935] opened 2023-10-12 03:23 UTC
## Description

Whenever a Space Dragon devour a corpse and is cut open, no corpse appear 

**Reproduction**

1-Be a space dragon
2-Eat people
3-Die
4-Butcher the dragon
5-No corpses

**Screenshots**

**Additional context**

**Comment by GoodWheatley** [comment] 2023-12-27 02:15
update to this issue: people eaten by the dragon report their client freezing when the dragon is butchered. The bodies still do not appear.

**Comment by chromiumboy** [comment] 2024-03-26 20:09
Thank you for the report!

Closing this as it is a duplicate of #20405

**Closed by chromiumboy** 2024-03-26 20:09 UTC
