### ISSUE TITLE
Singularity eats objects 1 tile behind emitter force field

### ISSUE THREAD

**Issue by AJimmyU** [space-wizards/space-station-14#13141] opened 2022-12-22 19:35 UTC
## Description

Building a wall/cable/emitter/radiation collector directly behind the containment field will cause these objects to be destroyed once the singularity is operational.

**Reproduction**

Build containment field for singularity.
Place radiation collector directly behind containment field.
Turn on singularity with particle accelerator.

**Screenshots**

**Additional context**

Sometimes it even destroys lattice underneath the containment field, which can result in splitting of the grid that holds the shield generators. It's not intuitive to expect things to be eaten behind a force field, as even emitters can be eaten if they are touching the force field.

**Comment by TemporalOroboros** [comment] 2022-12-23 19:09
Might be some combination of the singularity moving towards the containment field at the same time that it expands making it briefly grow beyond the bounds of the containment field before collisions resolve. I don't think collisions care about ordering so that would make the singularity consume whatever it wound up overlapping with.

If it happened both on the same tick and before the singularity scans for turfs to consume it could also make it consume tiles the same way. The tile version would be slightly less obvious since it wouldn't also get the boost from movement.

**Comment by TemporalOroboros** [comment] 2023-01-11 01:37
@AJimmyU apparently I messed up when I was splitting apart singularities. The bit that scans for things to eat wound up scanning for anything overlapping a square instead of a circle. The problem is the square is larger than the circle so if the station is rotated the corner could poke out of the containment field and eat things.

**Closed** 2023-07-19 08:01 UTC
