### ISSUE TITLE
Mice issues

### ISSUE THREAD

**Issue by Zymem** [space-wizards/space-station-14#7463] opened 2022-04-08 00:37 UTC
- ~~Mice sometimes lose the ability to walk below doors.~~ 
- ~~Walking below doors will suffocate you.~~
- ~~There's no way of drinking, so dying of thirst will happen eventually.~~
- ~~This is more of a feature than an issue, but there should probably be way to escape if someone picks you up.~~ (Already an issue)

**Comment by Fishfish458** [comment] 2022-04-08 00:59
the door issue is when slipped or if a mouse "Jumped on the table" the vault impassable mask was removed from them (when they never had it) and forcibly given it when they "step off the table" or "got up from a slip".

There needs to be a check that the mob actually has the mask being taken away before it's actually taken away.

**Comment by mirrorcult** [comment] 2022-04-08 01:04
first one is a dupe of #7098

**Comment by DubiousDoggo** [comment] 2022-04-08 03:47
#7205

**Closed** 2022-05-14 13:33 UTC
Labels: Issue: Bug, Priority: 2-Before Release, Difficulty: 1-Easy
