### ISSUE TITLE
Everyone and everything is bloated

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/space-station-14#15982] opened 2023-05-01 16:00 UTC
## Description

![image](https://user-images.githubusercontent.com/34938708/235477699-fc47875b-e863-467a-99ff-bc22063ea1b9.png)
![image](https://user-images.githubusercontent.com/34938708/235477871-a65d2246-56c2-44a6-bccf-08ee682a65bb.png)

**Reproduction**

1. Inspect someone

**Comment by deltanedas** [comment] 2023-05-01 16:39
dupe of my issue

**Closed** 2023-05-01 16:54 UTC
