### ISSUE TITLE
Frozen input and vision

### ISSUE THREAD

**Issue by fizzle7** [space-wizards/space-station-14#378] opened 2019-10-06 16:02 UTC
![image](https://user-images.githubusercontent.com/10642303/66271864-83175580-e86b-11e9-9a57-ea10d7af01a5.png)
Went to click on the light in the image and this instantly appeared around my vision. Now I can't move, open the closets, remove the light, basically do anything but spawn entities and stuff, which as you can see from the bullets around the circle, works. The bullets can be spawned inside the circle or outside so the circle is not blocking hitscan.

**Comment by PJB3005** [comment] 2019-10-06 16:04
I'm pretty sure what happened is that you died from burning yourself on the light.

**Comment by fizzle7** [comment] 2019-10-07 01:22
Uhh, lol. Is this how death is supposed to look like then?

**Comment by Moneyl** [comment] 2019-10-07 02:09
@fizzle7 Did you perhaps have your UI hidden on accident during this? You can press F4 to toggle it's visibility. I tested clicking on a light with an empty hand I went into crit.
![Robust Client_cYV4kfxKRh](https://user-images.githubusercontent.com/8206401/66280642-a6e79500-e885-11e9-89bb-7d4f8a71461f.png)

**Comment by Injazz** [comment] 2019-10-07 08:03
Current shader for vision blur is my awful contraption, sorry...
Now i see that it doesnt even look like a blurred vision, it looks more like a 3D sphere with a hole in center. Jesus. What have I done?

**Comment by fizzle7** [comment] 2019-10-07 14:46
@Moneyl Nope, my screen is high DPI so the UI is tiny and you can't see it but it's there.

**Comment by Injazz** [comment] 2020-02-25 11:52
so if it's not a bug might close it?

**Comment by Zumorica** [comment] 2020-04-14 02:44
I'll just close this.

**Closed by Zumorica** 2020-04-14 02:44 UTC
Labels: Status: Not A Bug
