### ISSUE TITLE
Timer Triggers cannot be added to Modular Grenades in construction

### ISSUE THREAD

**Issue by Stealthbomber16** [space-wizards/space-station-14#10506] opened 2022-08-11 04:21 UTC
The title is an excellent summary.

The timer trigger will be consumed but will not be added to the grenade.

Steps to reproduce
- Attempt to add a timer trigger to a partially assembled modular grenade
- Attempt to add a timer trigger to a partially assembled modular grenade
- Attempt to add a timer trigger to a partially assembled modular grenade
- Attempt to add a timer trigger to a partially assembled modular grenade
- Attempt to add a timer trigger to a partially assembled modular grenade
- Repeat ad infinitium

Signal triggers CAN be added. Timer triggers cannot.
Special thanks to FacePlus for reporting this to me ingame.

**Comment by ElectroJr** [comment] 2022-08-14 17:37
While trying to reproduce this on a slightly out of date branch, I ran into the engine error that was since fixed by space-wizards/RobustToolbox/pull/3127

Seeing as I can't reproduce it on latest master, I assume that was the only cause of the bug, so closing the issue.

**Closed by ElectroJr** 2022-08-14 17:37 UTC
