### ISSUE TITLE
items will appear titled when droped

### ISSUE THREAD

**Issue by Dutch-VanDerLinde** [space-wizards/space-station-14#26549] opened 2024-03-30 05:09 UTC
**Reproduction**
- drop item

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/45323883/690ba2d9-7d4a-4aaf-a986-8dd8bafe4334)

**Comment by UbaserB** [comment] 2024-03-30 05:39
Duplicate of #26529

**Closed by UbaserB** 2024-03-30 05:39 UTC
Labels: Status: Untriaged
