### ISSUE TITLE
The NukeOpsDeclarationOfWar does not work.

### ISSUE THREAD

**Issue by IProduceWidgets** [space-wizards/space-station-14#20357] opened 2023-09-20 04:53 UTC
## Description

If you try to use it it gives you the pop up message "The device makes beeping noises but nothing happens." despite it being a nukeops round. It does not open the UI.

**Reproduction**

Secret gamemode -> roll nukeops -> have 4 or more nukies -> try to warops -> no ui to warops and the remote is mad at you.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/107586145/e4113266-3434-4001-91ca-30d00ae55b0c)

**Additional context**

**Comment by LankLTE** [comment] 2023-09-20 04:56
Dupe of #20282

**Closed by LankLTE** 2023-09-20 04:56 UTC
