### ISSUE TITLE
Omega soap slippage causes dropped items to be flung through walls

### ISSUE THREAD

**Issue by Kayek14** [space-wizards/space-station-14#11022] opened 2022-09-04 23:12 UTC
## Description
Slipping on an omega soap will cause you to throw any carried items at Mach 6 and will often times phase the items through any nearby wall due to them moving so quickly

**Reproduction**
1. Obtain omega soap.
2. Slip on omega soap while holding an item
3. The item will usually fly out of your hands and will often times be able to phase through a wall

**Additional context**
Items being flung at great speeds due to slipping on an omega soap is hilarious. Is there a way we can fix this without nerfing the soap slip strength factor?

**Comment by Stealthbomber16** [comment] 2022-09-05 16:40
This also occurs with honkbots.

**Comment by keronshb** [comment] 2022-09-08 17:24
This was fixed for other soaps but I left it in for Omega soap because I thought it would be admin spawn only 

#7907 

Duplicate of this but it's relevant. Substepping -should- fix this but we'll see.

tl/dr it has something to do with the speed of the item and if there's a slippery speed modifier of anything above 4 or 5 it'll make items ignore collision since the speed mod is super fast for items.

So the potential fixes are:

Low effort: lower the slipping speed modifier to 4 - 5 down from 9 (same for Traitor Soap)
Mid effort: wait for substepping to be implemented then adjust the speed modifier accordingly
High effort: Modify the speed calculations for items when someone is slipped
Maximum effort: More physics/engines PRs.

**Comment by IProduceWidgets** [comment] 2024-05-14 09:37
Items in hand fall directly down now when you slip.

**Closed by IProduceWidgets** 2024-05-14 09:37 UTC
