### ISSUE TITLE
Six packs dont visually work

### ISSUE THREAD

**Issue by bruhmogus** [space-wizards/space-station-14#28721] opened 2024-06-08 01:38 UTC
## Description
The six-pack item appears to only show how many cola are in it after being opened. This is clearly not how it works in real life.

**Reproduction**
Step 1. Spawn sixpack
Step 2. If necessary, place cola in sixpack
Step 3. Open sixpack container

**Screenshots**
![20240607203734_1](https://github.com/space-wizards/space-station-14/assets/104110869/716d2780-4faa-4aae-9a3a-dfb2cd24978b)

![20240607203738_1](https://github.com/space-wizards/space-station-14/assets/104110869/4ce45204-6506-42af-9b73-670e02a5d3e0)

**Additional context**
It appears to be tied to the code that changes a container's visual varied appearance on opening. Examples include the ore box.

**Comment by TetraGamesTeam** [comment] 2024-06-08 10:40
Might try that. Has something to do with what exactly triggers the appearance change.

**Comment by themias** [comment] 2024-07-10 13:05
Dupe of #22270

**Comment by ShadowCommander** [comment] 2024-07-21 05:50
Fixed by #29309

**Closed by ShadowCommander** 2024-07-21 05:50 UTC
Labels: Status: Untriaged
