### ISSUE TITLE
All cargo shuttle Docks highlight at round start 

### ISSUE THREAD

**Issue by Titian3** [space-wizards/space-station-14#21266] opened 2023-10-26 16:36 UTC
## Description
Very minor visual bug on cargo shuttle console UI where all docks are highlighted when before the first docking at round start, seems to resolve after first docking. Can just be confusing behavior visually.

**Reproduction**
At round start hover over one of the dock buttons on the cargo ship, should see all the station ones highlight not just the one in particular

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/47093363/53cd30c6-d5ef-4f76-b1ec-2b67369346e2)

**Additional context**
Mouse is over dock3 in screen cap

**Comment by exincore** [comment] 2024-02-12 19:35
Related to PR #18935 which changed, among other things, the docking highlighting to use `EntityUid`. 

Here is my hypothesis:

Docks use `EntityUid` for highlighting, which is problematic since the docks are located far enough away from the client's location that they are not loaded and thus have no ID, until the player gets near enough to a dock to load it.

In the case of the screenshot, Dock 3 is located on the shuttle, and that entity is not loaded/instanced by the client, so its ID is null. The UI then attempts to highlight all docks with null IDs, which includes all the other docks that the client has not loaded/instanced yet.

**Comment by metalgearsloth** [comment] 2024-02-13 00:31
I spotted it in https://github.com/space-wizards/space-station-14/pull/24430 though the docking screen is getting reworked so the issue is moot, but I'll leave it open until it's merged.

**Closed** 2024-03-03 07:39 UTC
