### ISSUE TITLE
Accent's not working on radio

### ISSUE THREAD

**Issue by LordEclipse** [space-wizards/space-station-14#11774] opened 2022-10-08 23:45 UTC
## Description
When you have an accent, it doesn't transfer when you're using radio.

**Reproduction**
1. Get an accent
2. Try to talk on radio
3. See that what you're whispering and what is said over the radio aren't quite the same

**Screenshots**
![image](https://user-images.githubusercontent.com/106132477/194731416-7c0dc307-0068-4ad7-9894-6fd8d151babf.png)

**Comment by Willhelm53** [comment] 2022-10-16 16:47
Duplicate of #10888

**Closed** 2022-10-16 16:51 UTC
