### ISSUE TITLE
There's too much food/drink on the station at round start

### ISSUE THREAD

**Issue by FairlySadPanda** [space-wizards/space-station-14#26000] opened 2024-03-11 13:57 UTC
## Description
There's too much food and drink on the station at round start, which is unfair to players who want to produce more food/drink and have no real reason to when the average tider is filled with Dr Gibb and donk pockets.

The game should encourage roles to matter and at the moment the bar/kitchen, which should be the beating heart of the station's social life, are only really used by people who want to dodge doing their job, play midis, or be a shitter to undervalued service staff.

**Comment by metalgearsloth** [comment] 2024-03-11 14:03
Dupe of https://github.com/space-wizards/space-station-14/issues/12462

**Closed** 2024-03-11 15:13 UTC
