### ISSUE TITLE
Lizard tail sprites clip over magboot sprites

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/space-station-14#20543] opened 2023-09-27 12:13 UTC
## Description
**Reproduction**
- Spawn as a lizard
- Have a tail
- Equip magboots
- 
**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/10968691/e55a7427-ea08-4b02-b14a-b43d7ceb67a9)

**Comment by lzk228** [comment] 2023-09-27 12:17
what if make tails a body parts?

**Comment by PixelTheKermit** [comment] 2023-09-27 21:40
> what if make tails a body parts?

This will most likely not fix that.

**Comment by UbaserB** [comment] 2023-12-30 08:08
dupe of #15132

**Closed** 2023-12-30 17:36 UTC
