### ISSUE TITLE
Gaining Dead Status (seemingly) randomly

### ISSUE THREAD

**Issue by Mephisto72** [space-wizards/space-station-14#24339] opened 2024-01-20 14:50 UTC
## Description

For unknown reasons, I've received "Dead" Status on seemingly random times. I've had it happen most often while on the Evacuation shuttle arriving at Centcom. This does not cause usual death interactions like falling over or being ghosted, but it severely bugs out the game. For example: Not being able to use the context menu, Not being able to inspect items, Click interactions which cause messages to appear (locking and unlocking security barricades) not having messages, etc. 
If I had to guess, this is because a dead player would also not have these interactions available. Usually the time in which the player is shown as dead lasts shortly, at least for me. Going into a chair or similar also seems to cause the "dead" UI to change back to alive. The UI change back to alive does not fix the other problems I've mentioned. 
Reconnecting to the Server causes the Context Menu and such to work again, but the wounded overlay (The Screen getting more red as you take damage), still does not work, neither will gaining critical condition.

**Reproduction**

Currently steps to reproduce are unknown (to me), as it seems to occur randomly.
I've encountered it most after the forceful knock out caused by evac arriving.

**Screenshots**

Currently cannot provide a screenshot from what I can confirm to be this bug, but the Screenshot from issue #23715 seems to be very similar.

**Additional context**

This may or may not be the same bug as #23715 but that issue mentions specifically that it is only client-side and cannot be detected via. the health analyser, which I cannot confirm, as this would leave me without explanation for other cases of players showing up with 300 bloodloss to other players including on health scans. Additionally, if these are different bugs, having mentions of effects from the other bug each be included in the same Issue could cause issues when trying to debug, i.e. conflicting information, as I've already mentioned.

Encountered, also on Leviathan, Round 44382 on 20.1.2024 between 14:XX and 15:11
Incase this PR is deemed a dupe, I apologize, but I was fairly sure these are distinct bugs.

**Comment by ColdDead** [comment] 2024-01-20 16:27
Additional to this, when the peo
![Uploading 20240120172149_1.jpg…]()
pel have the "Dead" show they healt bar is empty same when person is dead on the medic hud

**Comment by VasilisThePikachu** [comment] 2024-01-20 20:09
probably it is a dupe of #23715

**Closed** 2024-01-20 20:08 UTC
