### ISSUE TITLE
Built SMES and substations default to 1 kJ of storage + localization issue

### ISSUE THREAD

**Issue by BasedUser** [space-wizards/space-station-14#6239] opened 2022-01-19 15:37 UTC
## Description

1. Build a SMES/substation with a machine frame, attach it to a HV network.

**Screenshots**

![image](https://user-images.githubusercontent.com/21104932/150163573-445e4c1f-c680-4159-9b81-e60cc5a4f8c9.png)

**Comment by Peptide90** [comment] 2022-01-19 16:15
This is an issue with the starting charge of the entity so that when they're mapped the station isn't powerless on round start.

Solution right now not to break that behaviour is to have a new ID for constructed substations that's parented to `BaseSubstation` and changing `  - type: Battery
    maxCharge: 1000
    startingCharge: 1000`

**Comment by BasedUser** [comment] 2022-01-19 16:27
the 1E+03 doesn't turn into k (no unit for thousands?)

**Comment by Peptide90** [comment] 2022-01-19 16:31
> the 1E+03 doesn't turn into k (no unit for thousands?)

Oh right, I'm used to seeing that form so didn't catch that. I'll check that out too. Thanks.

**Comment by Peptide90** [comment] 2022-01-19 19:58
> the 1E+03 doesn't turn into k (no unit for thousands?)

Could not reproduce this however I noticed the cable you were actually inspecting was not connected to anything. Still showed 0 J when I tried however. PR will close this issue but if localisation happens again we can reopen / specific issue.

**Closed** 2022-01-23 17:47 UTC
Labels: Type: Bug, Priority: 2-Before Release, Difficulty: 1-Easy
