### ISSUE TITLE
Controls/Chat breaks when your character is deleted

### ISSUE THREAD

**Issue by ProfanedBane** [space-wizards/space-station-14#638] opened 2020-02-08 15:00 UTC
When deleted the b key (and anything else) doesn't work to respawn and chat stops displaying new messages or letting you type new ones.
Console also stops responding.

**Comment by ShadowCommander** [comment] 2020-02-08 15:29
For now, this can usually be fixed by closing and opening the game.

**Comment by tentekal** [comment] 2020-02-08 18:19
I'll take a look at this

**Comment by tentekal** [comment] 2020-02-08 20:28
Looks like I can't for the life of me recreate this, if anyone can give me a text file or something with stdout when it happens I'd appreciate it.

**Comment by ProfanedBane** [comment] 2020-02-09 11:31
Didn't encounter it during the post-cm wizard den game, wonder if it's been fixed by something else or it's harder to repro that I thought?

**Comment by ShadowCommander** [comment] 2020-02-10 08:49
I can reproduce it. It only happens when you delete your character after saying something over local chat. Doesn't work with OOC.

**Comment by tentekal** [comment] 2020-02-10 14:14
Great, thanks guys. Someone (might have been ShadowCommander) gave me a trace log too during the CM test, should be a good start. ShadowCommander, did you wanna collab on this? I'll get that trace to you so we can see if your issue was the same (if you weren't the one who captured it).

**Comment by ShadowCommander** [comment] 2020-02-12 00:02
Alright it is the same error:
```
[ERRO] runtime: Caught exception in GameLoop Update: System.InvalidOperationException: Nullable object must have a value.
   at Robust.Client.UserInterface.RichTextEntry.Update(Font font, Single maxSizeX, Single uiScale) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/UserInterface/RichTextEntry.cs:line 99
   at Robust.Client.UserInterface.Controls.OutputPanel._invalidateEntries() in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/UserInterface/Controls/OutputPanel.cs:line 179
   at Robust.Client.UserInterface.Controls.OutputPanel.Resized() in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/UserInterface/Controls/OutputPanel.cs:line 163
   at Robust.Client.UserInterface.Control.set_Size(Vector2 value) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/UserInterface/Control.Layout.cs:line 57
   at Robust.Client.UserInterface.Control.FitChildInBox(Control child, UIBox2 box) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/UserInterface/Control.Layout.cs:line 389
   at Robust.Client.UserInterface.Controls.MarginContainer.LayoutUpdateOverride() in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/UserInterface/Controls/MarginContainer.cs:line 23
   at Robust.Client.UserInterface.UserInterfaceManager.FrameUpdate(FrameEventArgs args) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/UserInterface/UserInterfaceManager.cs:line 186
   at Robust.Client.GameController._frameProcessMain(FrameEventArgs frameEventArgs) in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Client/GameController.cs:line 271
   at Robust.Shared.Timing.GameLoop.Run() in /var/lib/jenkins/workspace/SS14 Content/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 222
```
Something's failing when the text is getting rendered. Seems like the window size or something gets set to 0 and it fails because of that.

**Comment by tentekal** [comment] 2020-02-18 12:41
@ShadowCommander could you dump what you've found on here so I can follow up?

**Comment by AJCM-git** [comment] 2020-04-29 23:06
Now you spawn as a ghost. This can be closed

**Closed** 2020-04-29 23:07 UTC
Labels: Priority: 2-medium, Type: Bug
