### ISSUE TITLE
Lasers dont shoot straight in space

### ISSUE THREAD

**Issue by Graded5** [space-wizards/space-station-14#27549] opened 2024-04-30 19:53 UTC
## Description

When shooting a laser based weapon into or in space, the laser does not shoot straight. 
**Reproduction**

>Obtain Laser Rifle
>Shoot into space
>Observe how the laser is rotated incorrectly

**Screenshots**

**Additional context**

This has no actual gameplay effect, just visual.

**Comment by deltanedas** [comment] 2024-04-30 19:56
dupe of other issue

**Comment by Graded5** [comment] 2024-04-30 20:11
i looked and didnt see this issue so...

**Comment by deltanedas** [comment] 2024-04-30 20:12
#23699

**Closed** 2024-04-30 22:11 UTC
Labels: Status: Untriaged
