### ISSUE TITLE
Depressurization and low pressure damage

### ISSUE THREAD

**Issue by Mirino97** [space-wizards/space-station-14#7568] opened 2022-04-15 21:12 UTC
## Description

[HIGHLY OPINIONATED AND OPEN FOR DISCUSSION]

While explosive depressurization is very cool to witness, it absolutely sucks to experience. 
At the moment, a single tile breach will kill anyone around in seconds. While the concept is not bad by itself, what sucks about it is the lack of response time, or even, response possibilities.

Now, if you're positioned well enough, either from being far away from the breach, or closer to a door, your chances of survival increase by a lot. The problem is that if you open a door to a pressurized room, that room will almost instantly depressurize. It sorta becomes a game of cat and mouse where: You're in a depressurized room. You go to another room to survive. That room is now depressurized. You go to another room to survive. That room is now... and so on and so forth. Not even mentioning that firelocks instantly close, forcing you to crowbar them open, which eats away at the precious seconds you have to live.

I'd like to see the lethality of this decreased a bit. 
Perhaps make it so that adjacent rooms won't depressurize as quickly, or decrease the damage low pressure/no oxy does, to give players an acceptable possibility of survival.
I believe I'd be okay with any changes, as long as they increase the survival rate a bit. Maybe instead of dying in 5-10 seconds, it'd take around 20 seconds. Still lethal and fast, just... a bit more fair?

I'm making this issue more as an easier place to discuss this as I don't believe most people join the forums.
Feel free to pitch in and agree/disagree.

**Comment by Mirino97** [comment] 2022-04-15 21:13
Damn, that was a quick thumbsdown lmao

**Comment by juliangiebel** [comment] 2022-04-15 21:21
I would go for lowering the damage low pressure does and adding something to the starting loadout you can use to buy yourself some time. 

Explosive depressurization should definitely stay the same (No reason to react with a thumbs down smh).

Raising the survivability just a bit could make pressure damage (It's not just about explosive depressurization) feel a lot better even if it might take some amount of skill as it is still a very deadly situation.

Also it's not just pressure killing you but temperature.

**Comment by ProfanedBane** [comment] 2022-04-15 21:28
In my mind ideally atmos should be deadly as hell, but the station is equipped to deal with it.
So firelocks already should work to partition breaches into smaller areas, from there they should also indicate if there's a dangerous pressure diff between it's two sides (codebases often have it start flashing a light/give a kpa output on examine).

I found it reasonably balanced in a few codebases where total oxygen loss gives you about 20-60 seconds minimum before you enter crit, so you can scramble to get a mask on. Whilst pressure damage is reasonably light, it will kill you after 2-6 minutes or so.

**Comment by mirrorcult** [comment] 2022-04-15 21:28
my opinions

![image](https://user-images.githubusercontent.com/19853115/163634427-dc3df3b5-4d69-45eb-9780-06e94bc367a5.png)

![image](https://user-images.githubusercontent.com/19853115/163634433-c4add088-90a8-4d9e-b4c3-2df45235da2e.png)

**Comment by Fishfish458** [comment] 2022-04-15 21:29
I do agree with lowering the damage a decent bit for low pressure, but also do believe that the rate at which a room depressurizes is also a good bit to blame.

currently no matter what size the room is, as long as there is a hole anywhere in it, the room will instantaneously lose pressure, this also means that any adjacent room you attempt to escape to will immediately lose pressure and oxygen as well the very moment you open the doors. Anyone in that adjacent room are immediately put in danger of the same fate because someone is trying to save their own life by opening a door and it turns into this weird game of putting yourself through 2-3 separate rooms just to get away.

I do believe air alarms might alleviate some of it but I don't believe opening a door for 2 seconds should completely expose an entire room to the same fate if there is a 1 tile opening.

**Comment by ProfanedBane** [comment] 2022-04-16 04:27
>currently no matter what size the room is, as long as there is a hole anywhere in it, the room will instantaneously lose pressure
I feel this also applies to gas filled rooms too. From a visual and gameplay aspect it's a bit weird to see a room instantly fill with overlayed vapour/gas the second you open the door, vs there being a fast flow into it visually.

**Comment by lightcat** [comment] 2022-04-16 12:21
As impressive as the code is, the rate at which rooms vent is way to much. I accidentally opened an outer airlock and spaced roughly half the station. 6 people died in cargo, an additional trying to flee, and possible three secoffs somehow. https://imgur.com/a/JT3hG0e

**Comment by Zumorica** [comment] 2022-04-16 13:00
> As impressive as the code is, the rate at which rooms vent is way to much. I accidentally opened an outer airlock and spaced roughly half the station. 6 people died in cargo, an additional trying to flee, and possible three secoffs somehow. [imgur.com/a/JT3hG0e](https://imgur.com/a/JT3hG0e)

That looks like both a mapping issue (no double edge firelocks on the same tile to allow people to cross areas without venting them) and a player issue. With monstermos, you need to place firelocks *everywhere*, with double edge firelocks being recommend over full-tile ones.

Nerfing the explosive depressurization/tile equalization rate is unfeasible and would require rethinking the algorithms entirely.
Any hacks to reduce their rate would only tank performance. I'm not willing to rewrite a huge chunk of atmos so you'd have to get someone else to do it.

Of course, there are CVars to disable the monstermos steps entirely and get boring old LINDA, but that'd be slower than what we have right now (both performance and atmos wise).

**Comment by juliangiebel** [comment] 2022-04-16 13:07
> I accidentally opened an outer airlock ...
Airlocks that cycle automatically would solve that specific problem entirely

**Comment by Peptide90** [comment] 2022-04-16 14:08
To add, I've already reduced the damage from low pressure once so that EVA without a suit is partially possible and not death in under 30 seconds.

Explosive atmos is interesting but I've been told you can simply disable monstermos and have classic LINDA if you want which would be neat to experience on 14. Could even be a fun event where it can randomly change.

**Comment by Mirino97** [comment] 2022-04-16 14:53
> > I accidentally opened an outer airlock ...
> 
> Airlocks that cycle automatically would solve that specific problem entirely

This is my next PR, depending if I'm able to make it or not : D

**Comment by Peptide90** [comment] 2022-04-16 17:46
> > > I accidentally opened an outer airlock ...
> 
> > 
> 
> > Airlocks that cycle automatically would solve that specific problem entirely
> 
> 
> 
> This is my next PR, depending if I'm able to make it or not : D

My recommendation if you do would be follow suit with machine linking. That way you can link N number of airlocks to one controller as well as vents / scrubbers.

**Comment by lightcat** [comment] 2022-04-17 08:04
> > As impressive as the code is, the rate at which rooms vent is way to much. I accidentally opened an outer airlock and spaced roughly half the station. 6 people died in cargo, an additional trying to flee, and possible three secoffs somehow. [imgur.com/a/JT3hG0e](https://imgur.com/a/JT3hG0e)
> 
> That looks like both a mapping issue (no double edge firelocks on the same tile to allow people to cross areas without venting them) and a player issue. With monstermos, you need to place firelocks _everywhere_, with double edge firelocks being recommend over full-tile ones.
> 
> Nerfing the explosive depressurization/tile equalization rate is unfeasible and would require rethinking the algorithms entirely. Any hacks to reduce their rate would only tank performance. I'm not willing to rewrite a huge chunk of atmos so you'd have to get someone else to do it.
> 
> Of course, there are CVars to disable the monstermos steps entirely and get boring old LINDA, but that'd be slower than what we have right now (both performance and atmos wise).

You have done a great job with the coding for it. My only critique is that it should've been more focused on performance rather than "how fast can we destroy a station?"

**Comment by Zumorica** [comment] 2022-04-17 08:38
> You have done a great job with the coding for it. My only critique is that it should've been more focused on performance rather than "how fast can we destroy a station?"

Performance has been my main concern with atmos from the very start. From this comment alone, I can tell that you have no idea at all about the topic so please don't speak about things you have no idea about, thank you.

**Comment by Peptide90** [comment] 2022-04-17 08:42
> > > As impressive as the code is, the rate at which rooms vent is way to much. I accidentally opened an outer airlock and spaced roughly half the station. 6 people died in cargo, an additional trying to flee, and possible three secoffs somehow. [imgur.com/a/JT3hG0e](https://imgur.com/a/JT3hG0e)
> 
> > 
> 
> > That looks like both a mapping issue (no double edge firelocks on the same tile to allow people to cross areas without venting them) and a player issue. With monstermos, you need to place firelocks _everywhere_, with double edge firelocks being recommend over full-tile ones.
> 
> > 
> 
> > Nerfing the explosive depressurization/tile equalization rate is unfeasible and would require rethinking the algorithms entirely. Any hacks to reduce their rate would only tank performance. I'm not willing to rewrite a huge chunk of atmos so you'd have to get someone else to do it.
> 
> > 
> 
> > Of course, there are CVars to disable the monstermos steps entirely and get boring old LINDA, but that'd be slower than what we have right now (both performance and atmos wise).
> 
> 
> 
> You have done a great job with the coding for it. My only critique is that it should've been more focused on performance rather than "how fast can we destroy a station?"

I assume instead of performance you meant gameplay? I've discussed it once or twice with Zumorica before and the gist of it is try out LINDA.

Monstermos is more realism which has pros and cons. It's also a nice demonstration when paired with stuff like physics but the trade off is it's deadly. Once we have working air alarms again that should lessen the issue a lot.

**Comment by lightcat** [comment] 2022-04-17 09:36
I don't feel that the current implementation is good for any form of gameplay. If Linda acts slower than only it should be enabled by default.

Regardless of how rude you are, spacing half the station in a few seconds or less is not good gameplay no matter how you put it. You speak so highly of gameplay and tell people to "Shut up" and that they don't know how to design a game. Well then, what you designed doesn't make any sense unless this is a accurate real life simulation over than being a game.

You might as well have given everyone a bomb. The problem is bombs keep going off. Your solution? Add a safety pin. When people criticize having the bomb in the first place? Tell them to code it out, you didn't spend years on the algorithm for nothing.

**Comment by Zumorica** [comment] 2022-04-17 10:03
> I don't feel that the current implementation is good for any form of gameplay.

Give me some valid reasons why. I have already explained how to make monstermos less lethal...

> If Linda acts slower than only it should be enabled by default.

LINDA is already enabled. It can't be disabled at all. What you mean is "disabling monstermos by default".
LINDA is slower both from a gameplay perspective and a performance perspective. Personally, I like violent atmos systems that raise the stakes and requires people to be careful around the vacuum of space and gas in general.

> Regardless of how rude you are, spacing half the station in a few seconds or less is not good gameplay no matter how you put it.

Rude? I only asked you to not speak of topics you know nothing about. I think that's a fair request.
If you knew anything about our atmos implementation, you would know that I did not code it, I only *ported* it.

> You speak so highly of gameplay and tell people to "Shut up" and that they don't know how to design a game.

...When have I or anyone here done this? If anything, I only told you to shut up when you decided to assume that I "focused too much on destroying the station fast instead of performance". If you knew anything about me or about our atmos system, you would know that from the very beginning, two years ago, I've been trying to make atmos perform better and take as little tick usage as possible. Let me reiterate: you are assuming things about people you don't know and systems you don't know the history of. 

> Well then, what you designed doesn't make any sense unless this is a accurate real life simulation over than being a game.

It's a little bit of both. It's realistic as depressurization is violent and fast, but it's also gamey as firelocks help prevent the whole station from being depressurized.
 
> You might as well have given everyone a bomb. The problem is bombs keep going off. Your solution? Add a safety pin. When people criticize having the bomb in the first place? Tell them to code it out, you didn't spend years on the algorithm for nothing.

Once again, you demonstrate you don't know anything about our atmos... I only ported the algorithms, but I did spend countless hours porting them, optimizing all of it so it doesn't lag the server to shit, rethinking and rewriting my own code.

I'm just a volunteer here, a contributor. I might have the title of "maintainer and wizard", but I'm unpaid just like everyone else that contributes to the game. When I spend hundreds of hours porting and optimizing a complex atmospherics system I don't even enjoy coding just for people to decide they want something else, of course I'm not gonna be particularly motivated or in the mood to rewrite it. It's only fair, I'm not forced to code atmos for the rest of my life, and honestly I would prefer not to. I have a life, and there are things I don't particularly like coding.

I've given everyone here the ideas and tools needed to make atmos less lethal: balance the pressure damage, balance the airloss damage, be careful when opening airlocks that lead to space and use double edge firelocks. If you want to keep monstermos' explosive depressurization, using those is enough to make atmos fair. If everyone decides that they want to disabled monstermos entirely and use plain LINDA, they can do this by changing two CVars. Hell, these can even be changed in the middle of a round on live servers. *What else do you want me to do?* Rude and entitled people like you make me want to stop coding for SS14 entirely.

**Comment by Peptide90** [comment] 2022-04-17 11:11
Closed by request, discussion derailed.

**Closed by Peptide90** 2022-04-17 11:11 UTC
Labels: Needs Discussion, Issue: Balance
