### ISSUE TITLE
Door Remotes respect line of effect?

### ISSUE THREAD

**Issue by LordEclipse** [space-wizards/space-station-14#19999] opened 2023-09-11 04:27 UTC
## Description
When you try to use a door remote, it has to be completely unblocked by anything in order for the remote to actually do anything to the door. Lockers, Players, Animals. They all block the signal to open the door.
Fairly certain they aren't supposed to be blocked by physical entities, but I could be wrong. But it definitely doesn't feel good in game to try to remotely open a door only for it to not open because the person was standing in front of it. You also can't bolt the door, or set it to emergency access.

**Reproduction**
1. Be a member of command
2. Attempt to use your cool remote door opener!
3. Despair when it doesn't open because you weren't standing directly in front of an unblocked door.

**Screenshots**

With a fellow Urist

https://github.com/space-wizards/space-station-14/assets/106132477/be399826-b9d6-4fe8-addd-bfbab2bb0046

With a locker

https://github.com/space-wizards/space-station-14/assets/106132477/190feaef-f915-456b-b8cc-f06dddafeb2d

**Comment by LankLTE** [comment] 2023-09-11 04:40
I had thought this was (to some extent) intentional but wouldn't mind changing it to just use LOS, might make door remotes more useful or something

**Comment by LordEclipse** [comment] 2023-09-11 04:45
> I had thought this was (to some extent) intentional but wouldn't mind changing it to just use LOS, might make door remotes more useful or something

It honestly just feels weird when you try to use it in round. I THINK it used to work with just LOS too? But I could just be misremembering.

**Comment by deltanedas** [comment] 2023-09-11 13:05
dupe of something

**Comment by B1essedknight** [comment] 2023-09-11 16:14
Pretty sure it is similar to #18583

**Comment by deltanedas** [comment] 2023-09-11 16:28
yes thats the one

**Comment by Plykiya** [comment] 2024-02-10 09:22
I've created a PR that fixes this.

**Closed** 2024-02-11 01:59 UTC
