### ISSUE TITLE
Puddles block anchoring on every, single, entity.

### ISSUE THREAD

**Issue by TurboTrackerss14** [space-wizards/space-station-14#31816] opened 2024-09-04 02:53 UTC
## Description
On EVERY anchorable/unanchorable entity, if there is even 0.01u of any reagent in a puddle under it. 
Anchoring is blocked. 
Why.

**Reproduction**
>have puddle in place you want to anchor something
>cry

**Screenshots**

https://github.com/user-attachments/assets/2b553209-66fc-4398-ba82-a0cd1518b873

**Additional context**
This even occurs with shiftstart puddles. Leading to the hilarious (painful) event where you have to move the entire Particle accelerator back one tile layer due to a vomit spill spawning under it.

**Comment by JIPDawg** [comment] 2024-09-04 05:28
Dupe of #31645 but you've got a fancy video

**Closed** 2024-09-12 06:08 UTC
Labels: Status: Untriaged
