### ISSUE TITLE
Deconstructing chairs while someone is cuffed to it deletes that someone

### ISSUE THREAD

**Issue by retequizzle** [space-wizards/space-station-14#29622] opened 2024-06-30 16:52 UTC
## Description
it's in the title

**Reproduction**
step 1: cuff entity capable of being cuffed
step 2: force entity into chair or seat
step 3: unwrench chair or seat
step 4: begin dragging chair or seat while person is in it
step 5: apply screwdriver to said chair or seat
step 6: be accused of witchcraft because the person disappears

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/67210376/ee09a133-ad1d-4317-8c23-86c49b060811)

**Additional context**
cuffing appears to be optional based on ahelp feedback, just put yourself into chair and then deconstruct said chair

**Comment by lzk228** [comment] 2024-06-30 17:09
dupe of #29526

**Comment by baddiePRO** [comment] 2024-06-30 18:00
kill objectives have never been easier, just send your target to the chair dimension

**Comment by baddiePRO** [comment] 2024-06-30 18:00
what happens if you deconstruct the chair with someone holding the nuke disk?

**Comment by Brandon-Huu** [comment] 2024-06-30 18:04
> what happens if you deconstruct the chair with someone holding the nuke disk?

Pretty sure it just respawns somewhere on the station

**Closed** 2024-07-06 04:01 UTC
Labels: Status: Untriaged
