### ISSUE TITLE
Paradox Cloning!!

### ISSUE THREAD

**Issue by Erisfiregamer1** [space-wizards/space-station-14#27824] opened 2024-05-09 00:43 UTC
## Description
Bodies of those that are cloned can be cogged, and cogged people (taken by ghost role) can be cloned multiple times (each clone being a ghost role)

**Reproduction**
Make a cloning setup
Kill a guy and clone him
Revive and cognizine his now dead body
Put the cogged body (WITH A SOUL) in the cloner after they die
Clone them MULTIPLE TIMES, making MULTIPLE FUNCTIONING CLONES of ONE MAN

**Screenshots**
![image](https://github.com/space-wizards/space-station-14/assets/54373833/c23ab103-12c3-4da3-b0e4-c80db087e365)
The DobtreTide, AKA levi round 53155

**Additional context**
Only the multicloning thing is a bug probably

**Comment by K-Dynamic** [comment] 2024-05-09 02:33
Bug of the year?

Also I wonder what the rules are on cognizined _people_ (i.e. are they neutral)

**Comment by UbaserB** [comment] 2024-05-09 04:01
This will be fixed when cloning is removed, someone still needs to do it

**Comment by deltanedas** [comment] 2024-05-09 04:27
can do the same on /ghosted people, deltav had a pr a few months ago to disable cogni on humanoids

**Comment by Hmeister-real** [comment] 2024-05-09 07:41
best bug/feature ever

**Comment by MZwart** [comment] 2024-05-09 13:24
I've never cried of laughing in this game, but as Dobre nr. 6, this was way too funny. This has been one of the rounds I'll tell friends about when they ask about this game. Can we keep this feature please

**Comment by KingOnBudget** [comment] 2024-05-11 06:37
damn this is a bug?!?!

**Comment by Erisfiregamer1** [comment] 2024-05-12 12:30
hi, person who commited the first paradox cloning incident here

- Cloning should be at least tried to be kept in, even IF it's salvage only
- You should still be able to cognizine the catatonic to give them a soul
- Being able to clone one person repeatedly should be patched, and if a person is cloned the cognizine property should **NOT** carry over

**Comment by MZwart** [comment] 2024-05-12 22:45
This "bug" is a prime example of emergent gameplay, which in my opinion is what SS14 is all about. It would be a shame to patch this into nonexistence, since it is such a niche edgecase; it requires Salvage to find AND build cloning AND acquire cognizine AND have the mental capacity to combine the two in a clever way, which is why it took this long to even find out about this.

I don't think you shouldn't be able to clone the same person multiple times. It wouldn't make sense for lore reasons (there's no good in-game explanation why you shouldn't be able to clone the same person twice) and would completely eradicate this from ever happening again, which honestly would be a shame.
Cognizine not carrying over would be a cool middle ground, limiting how much people can use this system by linking it with a hard-to-get chemical. That way a couple dobres could still occur WITHOUT flooding the station with 20+ dobres.

I've unfortunately seen too many games become bland and uninteresting because the developers patched all the fun out. Please don't let that happen to this feature.

**Comment by Strol20** [comment] 2024-05-12 22:47
Not a bug but a feature

**Comment by mirrorcult** [comment] 2024-05-12 22:48
yeah i more or less agree there isnt really a big issue here, mostly when you factor in that a round with both a bunch of cog and cloning and someone willing to orchestrate this is not going to happen very often. if cloning was more prevalent we should probably triage this again but for the moment this is just funny

**Closed by mirrorcult** 2024-05-12 22:48 UTC
Labels: Issue: Bug, Priority: 2-Before Release, Difficulty: 2-Medium, Bug of the Year 2024 Candidate
