### ISSUE TITLE
Roleban didn't work with antags

### ISSUE THREAD

**Issue by Fromoriss** [space-wizards/space-station-14#21590] opened 2023-11-11 21:48 UTC
Description
You can't ban a player from antags with any method
Reproduction
1. Somebody breaks rule
2. Try to roleban antagonists for they
3. It not works both with banpanel and console
Additional context
It is useful.

**Comment by IProduceWidgets** [comment] 2023-11-15 00:24
This will need a broader ability to prevent players from taking ghost roles as well.

**Comment by EmoGarbage404** [comment] 2023-11-15 00:24
antag bans aren't supported so this is just a dupe of #16032

**Closed by EmoGarbage404** 2023-11-15 00:24 UTC
