### ISSUE TITLE
Walking along a row of lockers while also walking into them causes you to stop.

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/space-station-14#629] opened 2020-02-08 07:25 UTC
Basically when I walk down this row of lockers, if I press down and to the right, it will make me stop in place. This doesn't happen with normal walls or when I just press down normally. I've tried to demonstrate it with a video.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/49448379/74081195-18387f80-4a01-11ea-917b-91d85f8ae4e5.gif)

This happens whether you walk from the start of the locker line, or when you're in the middle.

**Comment by Tyler-IN** [comment] 2020-02-08 07:30
![image](https://user-images.githubusercontent.com/33945568/74081259-f0eeac00-4a1a-11ea-82da-48efcfefef7d.png)
Reproduced. Use `showbb` to show collision hitboxes.
Has to do w/ the corners I'm sure...

**Comment by Tyler-IN** [comment] 2020-02-08 07:32
![image](https://user-images.githubusercontent.com/33945568/74081268-25fafe80-4a1b-11ea-808b-e6301597c6f6.png)
Works in either direction against lockers.

**Comment by PrPleGoo** [comment] 2020-03-06 09:19
You are bumping into the lockers and attempting to shove them. However, due to the total mass being too great or friction slowing the lockers down there is no resulting movement.

**Comment by AJCM-git** [comment] 2020-05-23 19:01
fixed by physics rewrite

**Closed by AJCM-git** 2020-05-23 19:01 UTC
Labels: Priority: 3-low, Type: Bug
