### ISSUE TITLE
Stoping wielding breaks walls

### ISSUE THREAD

**Issue by Tunguso4ka** [space-wizards/space-station-14#14607] opened 2023-03-12 15:37 UTC
## Description
You loses the ability to wield wall again if you fail it the first time.

**Reproduction**
1. Get the reinforced wall
2. Disassemble it to the "wielding" stage
3. Stop the wielding at the any moment.
4. Now you cant disassemble it (even with the powers of RCD)

**Comment by mirrorcult** [comment] 2023-03-12 23:33
dupe of #14583

**Closed by mirrorcult** 2023-03-12 23:33 UTC
