### ISSUE TITLE
Suggestion: Eliminate drag in vacuum

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9814] opened 2022-07-16 18:34 UTC
## Description
Eliminate drag in vacuum. Or at least heavily reduce it. This would apply to mobs and grids, allowing either continue accelerating as they please. Have mobs escaping coasting grid inherit velocity (and thus have their velocity relative to shuttle at 0, as long as shuttle is not applying thrust).

**Additional context**
I perhaps enjoy Newtonian physics in sci-fi and game too much?
Somewhat related: counter-thrust with Brake as described in issue #9813.

**Comment by metalgearsloth** [comment] 2022-07-16 18:37
Dupe of https://github.com/space-wizards/space-station-14/issues/7685 and https://github.com/space-wizards/space-station-14/issues/8175

Also setting mob damping to 0 isn't happening because that's a performance sinkhole for no gain and content already goes hard on physics.

**Closed** 2022-07-16 18:37 UTC

**Comment by metalgearsloth** [comment] 2022-07-16 18:41
The island solver's already run in parallel per-map so it probably needs subscriptions to moveevents looked at because that's normally the bottleneck.
