### ISSUE TITLE
Parapen / Syndicate Pen can't accept reagents

### ISSUE THREAD

**Issue by TimrodDX** [space-wizards/space-station-14#7496] opened 2022-04-11 00:56 UTC
## Description

How to reproduce:

- Spawn a syndicate pen (not the Cybersun one)
- Attempt to load it with any reagent
- Doesn't work

**Comment by Macoron** [comment] 2022-04-21 22:14
I can't reproduce this behavior. Maybe you was expecting parapen to work as dropper (draw from reagent container by click)?

https://user-images.githubusercontent.com/6161335/164560054-fa1f062a-c411-46e6-880e-58412f76e59e.mp4

**Comment by EmoGarbage404** [comment] 2022-07-22 12:58
going to close this as the original issue is fixed and can't be reproduced.

**Closed by EmoGarbage404** 2022-07-22 12:58 UTC
Labels: Issue: Bug, Priority: 2-Before Release, No C#, Difficulty: 1-Easy
