### ISSUE TITLE
ban_exemption_update can crash the server

### ISSUE THREAD

**Issue by Chief-Engineer** [space-wizards/space-station-14#15816] opened 2023-04-26 08:29 UTC
## Description

Removing an exemption via `ban_exemption_update` then trying to add one crashes the server.

**Reproduction**

1. `ban_exemption_update localhost@JoeGenero Datacenter`
2. `ban_exemption_update localhost@JoeGenero None`
3. `ban_exemption_update localhost@JoeGenero Datacenter`

**Screenshots**

**Additional context**

I tested this with SQLite, I don't know if PostgreSQL will make a difference

**Comment by nikthechampiongr** [comment] 2024-04-19 16:19
Cannot reproduce with reproduction steps. Was this resolved?

**Comment by PJB3005** [comment] 2024-04-19 16:20
Closing unless somebody has repro steps/stack trace.

**Closed by PJB3005** 2024-04-19 16:20 UTC
