### ISSUE TITLE
Headphones issue

### ISSUE THREAD

**Issue by EEASAS** [space-wizards/space-station-14#16510] opened 2023-05-16 16:12 UTC
## Description

Game does not detect headphones after unplugging it and plugging it back in

**Reproduction**

1. Open the game on any server
2. Plug in headphones
3. No audio in game, but audio anywhere else.
4. Same thing happens if you unplug it and plug it back in.

**Screenshots**

Not needed

**Additional context**

Game will detect headphones if you rejoin

**Comment by asperger-sind** [comment] 2023-05-16 16:33
I can confirm this happens.
This is a pretty common bug over a lot of games and some games have worked around it, not sure how tho.

**Comment by VasilisThePikachu** [comment] 2023-05-17 06:52
Duplicate of #14634

**Comment by GoodWheatley** [comment] 2023-09-01 16:24
Dupe of #14634

**Closed by GoodWheatley** 2023-09-01 16:24 UTC
