### ISSUE TITLE
Gas Overlay Bug affecting Gas Miners

### ISSUE THREAD

**Issue by 5150Con** [space-wizards/space-station-14#9892] opened 2022-07-19 18:29 UTC
## Description
Was messing with gas for a while, 30+ minutes, with another Atmos tech when familiar gas overlay bug occurred, as seen in images. The mixers started reporting 0 pressure despite not changing anything, so I assume gas overlay issue had to something to do with it.

**Reproduction**
Be near gas a long time, notice that that fire has been burning for a while without dying. Honestly, it seems to happen to me more often when I am using mixing chamber/fires for a long time, never have this glitch as a non engineering role. Maybe due to proximity to gases?

**Screenshots**

![20220718224727_1](https://user-images.githubusercontent.com/104950325/179822478-855c4950-2281-4cd2-bcea-bc53ca79d0db.jpg)
![20220718224849_1](https://user-images.githubusercontent.com/104950325/179822482-20eb2556-1995-420f-871e-d60448f842ec.jpg)

**Additional context**

**Comment by metalgearsloth** [comment] 2022-07-20 04:12
Dupe of https://github.com/space-wizards/space-station-14/issues/9294 and some older issue I forget.

**Closed by metalgearsloth** 2022-07-20 04:12 UTC
