### ISSUE TITLE
Sentient monkeys have only one hand

### ISSUE THREAD

**Issue by Myctai** [space-wizards/space-station-14#9652] opened 2022-07-12 15:18 UTC
## Description
Sentient monkeys have only one hand.

**Reproduction**
- Adminbus monkey into ghostrole
- Control the monkey
- See just one left hand

**Screenshots**
![monkey_with_hat_and_baseball_bat](https://user-images.githubusercontent.com/108953437/178525037-1db44ef3-dc0f-4f9e-bc87-42adb93ab7ce.png)
(also pictured: something is off with bat in-hand sprite rendering)
![entirety_of_inventory](https://user-images.githubusercontent.com/108953437/178525135-d1bdc2d6-6354-4454-b1cb-fdce65e00b1b.png)

**Additional context**
Makes me really not excited about #9637's final stage effect.

**Comment by EmoGarbage404** [comment] 2022-07-12 15:30
Monkeys were given one hand as a nerf a while ago back when they were ghost roles. The sprite issue is just an issue with how inhands are drawn and layered.

**Comment by EmoGarbage404** [comment] 2022-07-22 01:29
closing this as it's not a bug,and was done intentionally.

**Closed by EmoGarbage404** 2022-07-22 01:29 UTC
